// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: darwin.proto

package railreader_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Formation_Coach_Toilet_Status int32

const (
	Formation_Coach_Toilet_STATUS_UNKNOWN        Formation_Coach_Toilet_Status = 0
	Formation_Coach_Toilet_STATUS_IN_SERVICE     Formation_Coach_Toilet_Status = 1
	Formation_Coach_Toilet_STATUS_NOT_IN_SERVICE Formation_Coach_Toilet_Status = 2
)

// Enum value maps for Formation_Coach_Toilet_Status.
var (
	Formation_Coach_Toilet_Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_IN_SERVICE",
		2: "STATUS_NOT_IN_SERVICE",
	}
	Formation_Coach_Toilet_Status_value = map[string]int32{
		"STATUS_UNKNOWN":        0,
		"STATUS_IN_SERVICE":     1,
		"STATUS_NOT_IN_SERVICE": 2,
	}
)

func (x Formation_Coach_Toilet_Status) Enum() *Formation_Coach_Toilet_Status {
	p := new(Formation_Coach_Toilet_Status)
	*p = x
	return p
}

func (x Formation_Coach_Toilet_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Formation_Coach_Toilet_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_darwin_proto_enumTypes[0].Descriptor()
}

func (Formation_Coach_Toilet_Status) Type() protoreflect.EnumType {
	return &file_darwin_proto_enumTypes[0]
}

func (x Formation_Coach_Toilet_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Formation_Coach_Toilet_Status.Descriptor instead.
func (Formation_Coach_Toilet_Status) EnumDescriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{2, 0, 0, 0}
}

type ScheduleLocation_Type int32

const (
	ScheduleLocation_TYPE_LOCATION_UNKNOWN                  ScheduleLocation_Type = 0
	ScheduleLocation_TYPE_LOCATION_ORIGIN                   ScheduleLocation_Type = 1
	ScheduleLocation_TYPE_LOCATION_OPERATIONAL_ORIGIN       ScheduleLocation_Type = 2
	ScheduleLocation_TYPE_LOCATION_INTERMEDIATE             ScheduleLocation_Type = 3
	ScheduleLocation_TYPE_LOCATION_OPERATIONAL_INTERMEDIATE ScheduleLocation_Type = 4
	ScheduleLocation_TYPE_LOCATION_INTERMEDIATE_PASSING     ScheduleLocation_Type = 5
	ScheduleLocation_TYPE_LOCATION_DESTINATION              ScheduleLocation_Type = 6
	ScheduleLocation_TYPE_LOCATION_OPERATIONAL_DESTINATION  ScheduleLocation_Type = 7
)

// Enum value maps for ScheduleLocation_Type.
var (
	ScheduleLocation_Type_name = map[int32]string{
		0: "TYPE_LOCATION_UNKNOWN",
		1: "TYPE_LOCATION_ORIGIN",
		2: "TYPE_LOCATION_OPERATIONAL_ORIGIN",
		3: "TYPE_LOCATION_INTERMEDIATE",
		4: "TYPE_LOCATION_OPERATIONAL_INTERMEDIATE",
		5: "TYPE_LOCATION_INTERMEDIATE_PASSING",
		6: "TYPE_LOCATION_DESTINATION",
		7: "TYPE_LOCATION_OPERATIONAL_DESTINATION",
	}
	ScheduleLocation_Type_value = map[string]int32{
		"TYPE_LOCATION_UNKNOWN":                  0,
		"TYPE_LOCATION_ORIGIN":                   1,
		"TYPE_LOCATION_OPERATIONAL_ORIGIN":       2,
		"TYPE_LOCATION_INTERMEDIATE":             3,
		"TYPE_LOCATION_OPERATIONAL_INTERMEDIATE": 4,
		"TYPE_LOCATION_INTERMEDIATE_PASSING":     5,
		"TYPE_LOCATION_DESTINATION":              6,
		"TYPE_LOCATION_OPERATIONAL_DESTINATION":  7,
	}
)

func (x ScheduleLocation_Type) Enum() *ScheduleLocation_Type {
	p := new(ScheduleLocation_Type)
	*p = x
	return p
}

func (x ScheduleLocation_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduleLocation_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_darwin_proto_enumTypes[1].Descriptor()
}

func (ScheduleLocation_Type) Type() protoreflect.EnumType {
	return &file_darwin_proto_enumTypes[1]
}

func (x ScheduleLocation_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduleLocation_Type.Descriptor instead.
func (ScheduleLocation_Type) EnumDescriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{5, 0}
}

type ServiceLoading_Type int32

const (
	ServiceLoading_TYPE_LOADING_UNKNOWN  ServiceLoading_Type = 0
	ServiceLoading_TYPE_LOADING_TYPICAL  ServiceLoading_Type = 1
	ServiceLoading_TYPE_LOADING_EXPECTED ServiceLoading_Type = 2
)

// Enum value maps for ServiceLoading_Type.
var (
	ServiceLoading_Type_name = map[int32]string{
		0: "TYPE_LOADING_UNKNOWN",
		1: "TYPE_LOADING_TYPICAL",
		2: "TYPE_LOADING_EXPECTED",
	}
	ServiceLoading_Type_value = map[string]int32{
		"TYPE_LOADING_UNKNOWN":  0,
		"TYPE_LOADING_TYPICAL":  1,
		"TYPE_LOADING_EXPECTED": 2,
	}
)

func (x ServiceLoading_Type) Enum() *ServiceLoading_Type {
	p := new(ServiceLoading_Type)
	*p = x
	return p
}

func (x ServiceLoading_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceLoading_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_darwin_proto_enumTypes[2].Descriptor()
}

func (ServiceLoading_Type) Type() protoreflect.EnumType {
	return &file_darwin_proto_enumTypes[2]
}

func (x ServiceLoading_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceLoading_Type.Descriptor instead.
func (ServiceLoading_Type) EnumDescriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{6, 0}
}

type DisruptionReason struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReasonId         uint32                 `protobuf:"varint,1,opt,name=reason_id,json=reasonId,proto3" json:"reason_id,omitempty"`
	ReasonLocationId *string                `protobuf:"bytes,2,opt,name=reason_location_id,json=reasonLocationId,proto3,oneof" json:"reason_location_id,omitempty"`
	// When true, the provided reason_id is 'near to' the provided reason_location_id.
	// When false, the reason_id is 'at' the reason_location_id.
	ReasonIsNearLocation bool `protobuf:"varint,3,opt,name=reason_is_near_location,json=reasonIsNearLocation,proto3" json:"reason_is_near_location,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DisruptionReason) Reset() {
	*x = DisruptionReason{}
	mi := &file_darwin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisruptionReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisruptionReason) ProtoMessage() {}

func (x *DisruptionReason) ProtoReflect() protoreflect.Message {
	mi := &file_darwin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisruptionReason.ProtoReflect.Descriptor instead.
func (*DisruptionReason) Descriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{0}
}

func (x *DisruptionReason) GetReasonId() uint32 {
	if x != nil {
		return x.ReasonId
	}
	return 0
}

func (x *DisruptionReason) GetReasonLocationId() string {
	if x != nil && x.ReasonLocationId != nil {
		return *x.ReasonLocationId
	}
	return ""
}

func (x *DisruptionReason) GetReasonIsNearLocation() bool {
	if x != nil {
		return x.ReasonIsNearLocation
	}
	return false
}

type Schedule struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Uuid                  string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ScheduleId            string                 `protobuf:"bytes,4,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Uid                   string                 `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Headcode              string                 `protobuf:"bytes,8,opt,name=headcode,proto3" json:"headcode,omitempty"`
	RetailServiceId       *string                `protobuf:"bytes,9,opt,name=retail_service_id,json=retailServiceId,proto3,oneof" json:"retail_service_id,omitempty"`
	TocId                 string                 `protobuf:"bytes,10,opt,name=toc_id,json=tocId,proto3" json:"toc_id,omitempty"`
	Service               ServiceType            `protobuf:"varint,11,opt,name=service,proto3,enum=ServiceType" json:"service,omitempty"`
	Category              CategoryType           `protobuf:"varint,12,opt,name=category,proto3,enum=CategoryType" json:"category,omitempty"`
	IsPassengerService    bool                   `protobuf:"varint,13,opt,name=is_passenger_service,json=isPassengerService,proto3" json:"is_passenger_service,omitempty"`
	IsActive              bool                   `protobuf:"varint,14,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsCharter             bool                   `protobuf:"varint,16,opt,name=is_charter,json=isCharter,proto3" json:"is_charter,omitempty"`
	IsCancelled           bool                   `protobuf:"varint,17,opt,name=is_cancelled,json=isCancelled,proto3" json:"is_cancelled,omitempty"`
	CancellationReason    *DisruptionReason      `protobuf:"bytes,18,opt,name=cancellation_reason,json=cancellationReason,proto3,oneof" json:"cancellation_reason,omitempty"`
	DivertedViaLocationId *string                `protobuf:"bytes,19,opt,name=diverted_via_location_id,json=divertedViaLocationId,proto3,oneof" json:"diverted_via_location_id,omitempty"`
	DiversionReason       *DisruptionReason      `protobuf:"bytes,20,opt,name=diversion_reason,json=diversionReason,proto3,oneof" json:"diversion_reason,omitempty"`
	Forecast              *Schedule_Forecast     `protobuf:"bytes,21,opt,name=forecast,proto3,oneof" json:"forecast,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_darwin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_darwin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{1}
}

func (x *Schedule) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Schedule) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *Schedule) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Schedule) GetHeadcode() string {
	if x != nil {
		return x.Headcode
	}
	return ""
}

func (x *Schedule) GetRetailServiceId() string {
	if x != nil && x.RetailServiceId != nil {
		return *x.RetailServiceId
	}
	return ""
}

func (x *Schedule) GetTocId() string {
	if x != nil {
		return x.TocId
	}
	return ""
}

func (x *Schedule) GetService() ServiceType {
	if x != nil {
		return x.Service
	}
	return ServiceType_SERVICE_TYPE_SERVICE_UNKNOWN
}

func (x *Schedule) GetCategory() CategoryType {
	if x != nil {
		return x.Category
	}
	return CategoryType_CATEGORY_TYPE_CATEGORY_UNKNOWN
}

func (x *Schedule) GetIsPassengerService() bool {
	if x != nil {
		return x.IsPassengerService
	}
	return false
}

func (x *Schedule) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Schedule) GetIsCharter() bool {
	if x != nil {
		return x.IsCharter
	}
	return false
}

func (x *Schedule) GetIsCancelled() bool {
	if x != nil {
		return x.IsCancelled
	}
	return false
}

func (x *Schedule) GetCancellationReason() *DisruptionReason {
	if x != nil {
		return x.CancellationReason
	}
	return nil
}

func (x *Schedule) GetDivertedViaLocationId() string {
	if x != nil && x.DivertedViaLocationId != nil {
		return *x.DivertedViaLocationId
	}
	return ""
}

func (x *Schedule) GetDiversionReason() *DisruptionReason {
	if x != nil {
		return x.DiversionReason
	}
	return nil
}

func (x *Schedule) GetForecast() *Schedule_Forecast {
	if x != nil {
		return x.Forecast
	}
	return nil
}

type Formation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormationId   string                 `protobuf:"bytes,4,opt,name=formation_id,json=formationId,proto3" json:"formation_id,omitempty"`
	Source        *string                `protobuf:"bytes,5,opt,name=source,proto3,oneof" json:"source,omitempty"`
	SourceSystem  *string                `protobuf:"bytes,6,opt,name=source_system,json=sourceSystem,proto3,oneof" json:"source_system,omitempty"`
	Coaches       []*Formation_Coach     `protobuf:"bytes,7,rep,name=coaches,proto3" json:"coaches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Formation) Reset() {
	*x = Formation{}
	mi := &file_darwin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Formation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Formation) ProtoMessage() {}

func (x *Formation) ProtoReflect() protoreflect.Message {
	mi := &file_darwin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Formation.ProtoReflect.Descriptor instead.
func (*Formation) Descriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{2}
}

func (x *Formation) GetFormationId() string {
	if x != nil {
		return x.FormationId
	}
	return ""
}

func (x *Formation) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *Formation) GetSourceSystem() string {
	if x != nil && x.SourceSystem != nil {
		return *x.SourceSystem
	}
	return ""
}

func (x *Formation) GetCoaches() []*Formation_Coach {
	if x != nil {
		return x.Coaches
	}
	return nil
}

type ForecastLocation struct {
	state                        protoimpl.MessageState     `protogen:"open.v1"`
	Arrival                      *ForecastLocation_Times    `protobuf:"bytes,9,opt,name=arrival,proto3,oneof" json:"arrival,omitempty"`
	Passing                      *ForecastLocation_Times    `protobuf:"bytes,10,opt,name=passing,proto3,oneof" json:"passing,omitempty"`
	Departure                    *ForecastLocation_Times    `protobuf:"bytes,11,opt,name=departure,proto3,oneof" json:"departure,omitempty"`
	LateReason                   *DisruptionReason          `protobuf:"bytes,12,opt,name=late_reason,json=lateReason,proto3,oneof" json:"late_reason,omitempty"`
	DisruptionRisk               *string                    `protobuf:"bytes,13,opt,name=disruption_risk,json=disruptionRisk,proto3,oneof" json:"disruption_risk,omitempty"`
	DisruptionRiskReason         *DisruptionReason          `protobuf:"bytes,14,opt,name=disruption_risk_reason,json=disruptionRiskReason,proto3,oneof" json:"disruption_risk_reason,omitempty"`
	AffectedBy                   *string                    `protobuf:"bytes,15,opt,name=affected_by,json=affectedBy,proto3,oneof" json:"affected_by,omitempty"`
	ForecastLength               *uint32                    `protobuf:"varint,16,opt,name=forecast_length,json=forecastLength,proto3,oneof" json:"forecast_length,omitempty"`
	ForecastPlatform             *ForecastLocation_Platform `protobuf:"bytes,17,opt,name=forecast_platform,json=forecastPlatform,proto3,oneof" json:"forecast_platform,omitempty"`
	ServiceIsSuppressedHere      bool                       `protobuf:"varint,18,opt,name=service_is_suppressed_here,json=serviceIsSuppressedHere,proto3" json:"service_is_suppressed_here,omitempty"`
	ServiceDetachesFromFrontHere bool                       `protobuf:"varint,19,opt,name=service_detaches_from_front_here,json=serviceDetachesFromFrontHere,proto3" json:"service_detaches_from_front_here,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ForecastLocation) Reset() {
	*x = ForecastLocation{}
	mi := &file_darwin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastLocation) ProtoMessage() {}

func (x *ForecastLocation) ProtoReflect() protoreflect.Message {
	mi := &file_darwin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastLocation.ProtoReflect.Descriptor instead.
func (*ForecastLocation) Descriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{3}
}

func (x *ForecastLocation) GetArrival() *ForecastLocation_Times {
	if x != nil {
		return x.Arrival
	}
	return nil
}

func (x *ForecastLocation) GetPassing() *ForecastLocation_Times {
	if x != nil {
		return x.Passing
	}
	return nil
}

func (x *ForecastLocation) GetDeparture() *ForecastLocation_Times {
	if x != nil {
		return x.Departure
	}
	return nil
}

func (x *ForecastLocation) GetLateReason() *DisruptionReason {
	if x != nil {
		return x.LateReason
	}
	return nil
}

func (x *ForecastLocation) GetDisruptionRisk() string {
	if x != nil && x.DisruptionRisk != nil {
		return *x.DisruptionRisk
	}
	return ""
}

func (x *ForecastLocation) GetDisruptionRiskReason() *DisruptionReason {
	if x != nil {
		return x.DisruptionRiskReason
	}
	return nil
}

func (x *ForecastLocation) GetAffectedBy() string {
	if x != nil && x.AffectedBy != nil {
		return *x.AffectedBy
	}
	return ""
}

func (x *ForecastLocation) GetForecastLength() uint32 {
	if x != nil && x.ForecastLength != nil {
		return *x.ForecastLength
	}
	return 0
}

func (x *ForecastLocation) GetForecastPlatform() *ForecastLocation_Platform {
	if x != nil {
		return x.ForecastPlatform
	}
	return nil
}

func (x *ForecastLocation) GetServiceIsSuppressedHere() bool {
	if x != nil {
		return x.ServiceIsSuppressedHere
	}
	return false
}

func (x *ForecastLocation) GetServiceDetachesFromFrontHere() bool {
	if x != nil {
		return x.ServiceDetachesFromFrontHere
	}
	return false
}

type FormationLoading struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Coaches       []*FormationLoading_Coach `protobuf:"bytes,11,rep,name=coaches,proto3" json:"coaches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormationLoading) Reset() {
	*x = FormationLoading{}
	mi := &file_darwin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormationLoading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormationLoading) ProtoMessage() {}

func (x *FormationLoading) ProtoReflect() protoreflect.Message {
	mi := &file_darwin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormationLoading.ProtoReflect.Descriptor instead.
func (*FormationLoading) Descriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{4}
}

func (x *FormationLoading) GetCoaches() []*FormationLoading_Coach {
	if x != nil {
		return x.Coaches
	}
	return nil
}

// 'Working' times are used internally by staff
// 'Public' times are used for display to passengers
// Working and Public timetables may differ, typically to allow services to experience very minor (30 to 60s) delays without appearing late to the public.
// There is no scheduled_public_passing_time because locations through which a service passes without stopping do not need to display any times to the public.
type ScheduleLocation struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ScheduleUuid               string                 `protobuf:"bytes,2,opt,name=schedule_uuid,json=scheduleUuid,proto3" json:"schedule_uuid,omitempty"`
	ComputedId                 []byte                 `protobuf:"bytes,3,opt,name=computed_id,json=computedId,proto3" json:"computed_id,omitempty"`
	LocationId                 string                 `protobuf:"bytes,5,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Activities                 []ActivityType         `protobuf:"varint,6,rep,packed,name=activities,proto3,enum=ActivityType" json:"activities,omitempty"`
	PlannedActivities          []ActivityType         `protobuf:"varint,7,rep,packed,name=planned_activities,json=plannedActivities,proto3,enum=ActivityType" json:"planned_activities,omitempty"`
	FormationId                *string                `protobuf:"bytes,8,opt,name=formation_id,json=formationId,proto3,oneof" json:"formation_id,omitempty"`
	IsAffectedByDiversion      bool                   `protobuf:"varint,9,opt,name=is_affected_by_diversion,json=isAffectedByDiversion,proto3" json:"is_affected_by_diversion,omitempty"`
	Type                       ScheduleLocation_Type  `protobuf:"varint,10,opt,name=type,proto3,enum=ScheduleLocation_Type" json:"type,omitempty"`
	WorkingArrivalTime         *string                `protobuf:"bytes,11,opt,name=working_arrival_time,json=workingArrivalTime,proto3,oneof" json:"working_arrival_time,omitempty"`
	WorkingPassingTime         *string                `protobuf:"bytes,12,opt,name=working_passing_time,json=workingPassingTime,proto3,oneof" json:"working_passing_time,omitempty"`
	WorkingDepartureTime       *string                `protobuf:"bytes,13,opt,name=working_departure_time,json=workingDepartureTime,proto3,oneof" json:"working_departure_time,omitempty"`
	PublicArrivalTime          *string                `protobuf:"bytes,14,opt,name=public_arrival_time,json=publicArrivalTime,proto3,oneof" json:"public_arrival_time,omitempty"`
	PublicDepartureTime        *string                `protobuf:"bytes,15,opt,name=public_departure_time,json=publicDepartureTime,proto3,oneof" json:"public_departure_time,omitempty"`
	RoutingDelay               int32                  `protobuf:"varint,16,opt,name=routing_delay,json=routingDelay,proto3" json:"routing_delay,omitempty"` // in minutes
	FalseDestinationLocationId *string                `protobuf:"bytes,17,opt,name=false_destination_location_id,json=falseDestinationLocationId,proto3,oneof" json:"false_destination_location_id,omitempty"`
	IsCancelled                bool                   `protobuf:"varint,18,opt,name=is_cancelled,json=isCancelled,proto3" json:"is_cancelled,omitempty"`
	LocationCancellationReason *DisruptionReason      `protobuf:"bytes,19,opt,name=location_cancellation_reason,json=locationCancellationReason,proto3,oneof" json:"location_cancellation_reason,omitempty"`
	TimetabledPlatform         *string                `protobuf:"bytes,20,opt,name=timetabled_platform,json=timetabledPlatform,proto3,oneof" json:"timetabled_platform,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ScheduleLocation) Reset() {
	*x = ScheduleLocation{}
	mi := &file_darwin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleLocation) ProtoMessage() {}

func (x *ScheduleLocation) ProtoReflect() protoreflect.Message {
	mi := &file_darwin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleLocation.ProtoReflect.Descriptor instead.
func (*ScheduleLocation) Descriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{5}
}

func (x *ScheduleLocation) GetScheduleUuid() string {
	if x != nil {
		return x.ScheduleUuid
	}
	return ""
}

func (x *ScheduleLocation) GetComputedId() []byte {
	if x != nil {
		return x.ComputedId
	}
	return nil
}

func (x *ScheduleLocation) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *ScheduleLocation) GetActivities() []ActivityType {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *ScheduleLocation) GetPlannedActivities() []ActivityType {
	if x != nil {
		return x.PlannedActivities
	}
	return nil
}

func (x *ScheduleLocation) GetFormationId() string {
	if x != nil && x.FormationId != nil {
		return *x.FormationId
	}
	return ""
}

func (x *ScheduleLocation) GetIsAffectedByDiversion() bool {
	if x != nil {
		return x.IsAffectedByDiversion
	}
	return false
}

func (x *ScheduleLocation) GetType() ScheduleLocation_Type {
	if x != nil {
		return x.Type
	}
	return ScheduleLocation_TYPE_LOCATION_UNKNOWN
}

func (x *ScheduleLocation) GetWorkingArrivalTime() string {
	if x != nil && x.WorkingArrivalTime != nil {
		return *x.WorkingArrivalTime
	}
	return ""
}

func (x *ScheduleLocation) GetWorkingPassingTime() string {
	if x != nil && x.WorkingPassingTime != nil {
		return *x.WorkingPassingTime
	}
	return ""
}

func (x *ScheduleLocation) GetWorkingDepartureTime() string {
	if x != nil && x.WorkingDepartureTime != nil {
		return *x.WorkingDepartureTime
	}
	return ""
}

func (x *ScheduleLocation) GetPublicArrivalTime() string {
	if x != nil && x.PublicArrivalTime != nil {
		return *x.PublicArrivalTime
	}
	return ""
}

func (x *ScheduleLocation) GetPublicDepartureTime() string {
	if x != nil && x.PublicDepartureTime != nil {
		return *x.PublicDepartureTime
	}
	return ""
}

func (x *ScheduleLocation) GetRoutingDelay() int32 {
	if x != nil {
		return x.RoutingDelay
	}
	return 0
}

func (x *ScheduleLocation) GetFalseDestinationLocationId() string {
	if x != nil && x.FalseDestinationLocationId != nil {
		return *x.FalseDestinationLocationId
	}
	return ""
}

func (x *ScheduleLocation) GetIsCancelled() bool {
	if x != nil {
		return x.IsCancelled
	}
	return false
}

func (x *ScheduleLocation) GetLocationCancellationReason() *DisruptionReason {
	if x != nil {
		return x.LocationCancellationReason
	}
	return nil
}

func (x *ScheduleLocation) GetTimetabledPlatform() string {
	if x != nil && x.TimetabledPlatform != nil {
		return *x.TimetabledPlatform
	}
	return ""
}

type ServiceLoading struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Category      *ServiceLoading_Category   `protobuf:"bytes,10,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Percentage    *ServiceLoading_Percentage `protobuf:"bytes,11,opt,name=percentage,proto3,oneof" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceLoading) Reset() {
	*x = ServiceLoading{}
	mi := &file_darwin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceLoading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceLoading) ProtoMessage() {}

func (x *ServiceLoading) ProtoReflect() protoreflect.Message {
	mi := &file_darwin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceLoading.ProtoReflect.Descriptor instead.
func (*ServiceLoading) Descriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceLoading) GetCategory() *ServiceLoading_Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *ServiceLoading) GetPercentage() *ServiceLoading_Percentage {
	if x != nil {
		return x.Percentage
	}
	return nil
}

type Schedule_Forecast struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IsReverseFormation bool                   `protobuf:"varint,4,opt,name=is_reverse_formation,json=isReverseFormation,proto3" json:"is_reverse_formation,omitempty"`
	LateReason         *DisruptionReason      `protobuf:"bytes,5,opt,name=late_reason,json=lateReason,proto3,oneof" json:"late_reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Schedule_Forecast) Reset() {
	*x = Schedule_Forecast{}
	mi := &file_darwin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule_Forecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule_Forecast) ProtoMessage() {}

func (x *Schedule_Forecast) ProtoReflect() protoreflect.Message {
	mi := &file_darwin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule_Forecast.ProtoReflect.Descriptor instead.
func (*Schedule_Forecast) Descriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Schedule_Forecast) GetIsReverseFormation() bool {
	if x != nil {
		return x.IsReverseFormation
	}
	return false
}

func (x *Schedule_Forecast) GetLateReason() *DisruptionReason {
	if x != nil {
		return x.LateReason
	}
	return nil
}

type Formation_Coach struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Identifier    string                  `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Class         *string                 `protobuf:"bytes,3,opt,name=class,proto3,oneof" json:"class,omitempty"`
	ToiletData    *Formation_Coach_Toilet `protobuf:"bytes,4,opt,name=toilet_data,json=toiletData,proto3,oneof" json:"toilet_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Formation_Coach) Reset() {
	*x = Formation_Coach{}
	mi := &file_darwin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Formation_Coach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Formation_Coach) ProtoMessage() {}

func (x *Formation_Coach) ProtoReflect() protoreflect.Message {
	mi := &file_darwin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Formation_Coach.ProtoReflect.Descriptor instead.
func (*Formation_Coach) Descriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Formation_Coach) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Formation_Coach) GetClass() string {
	if x != nil && x.Class != nil {
		return *x.Class
	}
	return ""
}

func (x *Formation_Coach) GetToiletData() *Formation_Coach_Toilet {
	if x != nil {
		return x.ToiletData
	}
	return nil
}

type Formation_Coach_Toilet struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Type          string                        `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status        Formation_Coach_Toilet_Status `protobuf:"varint,2,opt,name=status,proto3,enum=Formation_Coach_Toilet_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Formation_Coach_Toilet) Reset() {
	*x = Formation_Coach_Toilet{}
	mi := &file_darwin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Formation_Coach_Toilet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Formation_Coach_Toilet) ProtoMessage() {}

func (x *Formation_Coach_Toilet) ProtoReflect() protoreflect.Message {
	mi := &file_darwin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Formation_Coach_Toilet.ProtoReflect.Descriptor instead.
func (*Formation_Coach_Toilet) Descriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Formation_Coach_Toilet) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Formation_Coach_Toilet) GetStatus() Formation_Coach_Toilet_Status {
	if x != nil {
		return x.Status
	}
	return Formation_Coach_Toilet_STATUS_UNKNOWN
}

type ForecastLocation_Times struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	EstimatedPublicTime            *string                `protobuf:"bytes,1,opt,name=estimated_public_time,json=estimatedPublicTime,proto3,oneof" json:"estimated_public_time,omitempty"`
	EstimatedWorkingTime           *string                `protobuf:"bytes,2,opt,name=estimated_working_time,json=estimatedWorkingTime,proto3,oneof" json:"estimated_working_time,omitempty"`
	MinimumEstimatedTime           *string                `protobuf:"bytes,3,opt,name=minimum_estimated_time,json=minimumEstimatedTime,proto3,oneof" json:"minimum_estimated_time,omitempty"`
	EstimationManuallySetToDelayed bool                   `protobuf:"varint,4,opt,name=estimation_manually_set_to_delayed,json=estimationManuallySetToDelayed,proto3" json:"estimation_manually_set_to_delayed,omitempty"`
	EstimatedAsDelayed             bool                   `protobuf:"varint,5,opt,name=estimated_as_delayed,json=estimatedAsDelayed,proto3" json:"estimated_as_delayed,omitempty"`
	ActualTime                     *string                `protobuf:"bytes,6,opt,name=actual_time,json=actualTime,proto3,oneof" json:"actual_time,omitempty"`
	ActualTimeClass                *string                `protobuf:"bytes,7,opt,name=actual_time_class,json=actualTimeClass,proto3,oneof" json:"actual_time_class,omitempty"`
	Source                         *string                `protobuf:"bytes,8,opt,name=source,proto3,oneof" json:"source,omitempty"`
	SourceSystem                   *string                `protobuf:"bytes,9,opt,name=source_system,json=sourceSystem,proto3,oneof" json:"source_system,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ForecastLocation_Times) Reset() {
	*x = ForecastLocation_Times{}
	mi := &file_darwin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastLocation_Times) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastLocation_Times) ProtoMessage() {}

func (x *ForecastLocation_Times) ProtoReflect() protoreflect.Message {
	mi := &file_darwin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastLocation_Times.ProtoReflect.Descriptor instead.
func (*ForecastLocation_Times) Descriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ForecastLocation_Times) GetEstimatedPublicTime() string {
	if x != nil && x.EstimatedPublicTime != nil {
		return *x.EstimatedPublicTime
	}
	return ""
}

func (x *ForecastLocation_Times) GetEstimatedWorkingTime() string {
	if x != nil && x.EstimatedWorkingTime != nil {
		return *x.EstimatedWorkingTime
	}
	return ""
}

func (x *ForecastLocation_Times) GetMinimumEstimatedTime() string {
	if x != nil && x.MinimumEstimatedTime != nil {
		return *x.MinimumEstimatedTime
	}
	return ""
}

func (x *ForecastLocation_Times) GetEstimationManuallySetToDelayed() bool {
	if x != nil {
		return x.EstimationManuallySetToDelayed
	}
	return false
}

func (x *ForecastLocation_Times) GetEstimatedAsDelayed() bool {
	if x != nil {
		return x.EstimatedAsDelayed
	}
	return false
}

func (x *ForecastLocation_Times) GetActualTime() string {
	if x != nil && x.ActualTime != nil {
		return *x.ActualTime
	}
	return ""
}

func (x *ForecastLocation_Times) GetActualTimeClass() string {
	if x != nil && x.ActualTimeClass != nil {
		return *x.ActualTimeClass
	}
	return ""
}

func (x *ForecastLocation_Times) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *ForecastLocation_Times) GetSourceSystem() string {
	if x != nil && x.SourceSystem != nil {
		return *x.SourceSystem
	}
	return ""
}

type ForecastLocation_Platform struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	IsSuppressed              bool                   `protobuf:"varint,1,opt,name=is_suppressed,json=isSuppressed,proto3" json:"is_suppressed,omitempty"`
	IsManuallySuppressedByCis bool                   `protobuf:"varint,2,opt,name=is_manually_suppressed_by_cis,json=isManuallySuppressedByCis,proto3" json:"is_manually_suppressed_by_cis,omitempty"`
	Source                    string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	IsConfirmed               bool                   `protobuf:"varint,4,opt,name=is_confirmed,json=isConfirmed,proto3" json:"is_confirmed,omitempty"`
	Platform                  string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ForecastLocation_Platform) Reset() {
	*x = ForecastLocation_Platform{}
	mi := &file_darwin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastLocation_Platform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastLocation_Platform) ProtoMessage() {}

func (x *ForecastLocation_Platform) ProtoReflect() protoreflect.Message {
	mi := &file_darwin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastLocation_Platform.ProtoReflect.Descriptor instead.
func (*ForecastLocation_Platform) Descriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ForecastLocation_Platform) GetIsSuppressed() bool {
	if x != nil {
		return x.IsSuppressed
	}
	return false
}

func (x *ForecastLocation_Platform) GetIsManuallySuppressedByCis() bool {
	if x != nil {
		return x.IsManuallySuppressedByCis
	}
	return false
}

func (x *ForecastLocation_Platform) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ForecastLocation_Platform) GetIsConfirmed() bool {
	if x != nil {
		return x.IsConfirmed
	}
	return false
}

func (x *ForecastLocation_Platform) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type FormationLoading_Coach struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identifier     string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Source         *string                `protobuf:"bytes,3,opt,name=source,proto3,oneof" json:"source,omitempty"`
	SourceSystem   *string                `protobuf:"bytes,4,opt,name=source_system,json=sourceSystem,proto3,oneof" json:"source_system,omitempty"`
	PercentageLoad uint32                 `protobuf:"varint,5,opt,name=percentage_load,json=percentageLoad,proto3" json:"percentage_load,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FormationLoading_Coach) Reset() {
	*x = FormationLoading_Coach{}
	mi := &file_darwin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormationLoading_Coach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormationLoading_Coach) ProtoMessage() {}

func (x *FormationLoading_Coach) ProtoReflect() protoreflect.Message {
	mi := &file_darwin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormationLoading_Coach.ProtoReflect.Descriptor instead.
func (*FormationLoading_Coach) Descriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{4, 0}
}

func (x *FormationLoading_Coach) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *FormationLoading_Coach) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *FormationLoading_Coach) GetSourceSystem() string {
	if x != nil && x.SourceSystem != nil {
		return *x.SourceSystem
	}
	return ""
}

func (x *FormationLoading_Coach) GetPercentageLoad() uint32 {
	if x != nil {
		return x.PercentageLoad
	}
	return 0
}

type ServiceLoading_Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Source        *string                `protobuf:"bytes,2,opt,name=source,proto3,oneof" json:"source,omitempty"`
	SourceSystem  *string                `protobuf:"bytes,3,opt,name=source_system,json=sourceSystem,proto3,oneof" json:"source_system,omitempty"`
	Type          ServiceLoading_Type    `protobuf:"varint,4,opt,name=type,proto3,enum=ServiceLoading_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceLoading_Category) Reset() {
	*x = ServiceLoading_Category{}
	mi := &file_darwin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceLoading_Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceLoading_Category) ProtoMessage() {}

func (x *ServiceLoading_Category) ProtoReflect() protoreflect.Message {
	mi := &file_darwin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceLoading_Category.ProtoReflect.Descriptor instead.
func (*ServiceLoading_Category) Descriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ServiceLoading_Category) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ServiceLoading_Category) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *ServiceLoading_Category) GetSourceSystem() string {
	if x != nil && x.SourceSystem != nil {
		return *x.SourceSystem
	}
	return ""
}

func (x *ServiceLoading_Category) GetType() ServiceLoading_Type {
	if x != nil {
		return x.Type
	}
	return ServiceLoading_TYPE_LOADING_UNKNOWN
}

type ServiceLoading_Percentage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PercentageLoad uint32                 `protobuf:"varint,1,opt,name=percentage_load,json=percentageLoad,proto3" json:"percentage_load,omitempty"`
	Source         *string                `protobuf:"bytes,2,opt,name=source,proto3,oneof" json:"source,omitempty"`
	SourceSystem   *string                `protobuf:"bytes,3,opt,name=source_system,json=sourceSystem,proto3,oneof" json:"source_system,omitempty"`
	Type           ServiceLoading_Type    `protobuf:"varint,4,opt,name=type,proto3,enum=ServiceLoading_Type" json:"type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServiceLoading_Percentage) Reset() {
	*x = ServiceLoading_Percentage{}
	mi := &file_darwin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceLoading_Percentage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceLoading_Percentage) ProtoMessage() {}

func (x *ServiceLoading_Percentage) ProtoReflect() protoreflect.Message {
	mi := &file_darwin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceLoading_Percentage.ProtoReflect.Descriptor instead.
func (*ServiceLoading_Percentage) Descriptor() ([]byte, []int) {
	return file_darwin_proto_rawDescGZIP(), []int{6, 1}
}

func (x *ServiceLoading_Percentage) GetPercentageLoad() uint32 {
	if x != nil {
		return x.PercentageLoad
	}
	return 0
}

func (x *ServiceLoading_Percentage) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *ServiceLoading_Percentage) GetSourceSystem() string {
	if x != nil && x.SourceSystem != nil {
		return *x.SourceSystem
	}
	return ""
}

func (x *ServiceLoading_Percentage) GetType() ServiceLoading_Type {
	if x != nil {
		return x.Type
	}
	return ServiceLoading_TYPE_LOADING_UNKNOWN
}

var File_darwin_proto protoreflect.FileDescriptor

const file_darwin_proto_rawDesc = "" +
	"\n" +
	"\fdarwin.proto\x1a\x0frailtypes.proto\"\xb0\x01\n" +
	"\x10DisruptionReason\x12\x1b\n" +
	"\treason_id\x18\x01 \x01(\rR\breasonId\x121\n" +
	"\x12reason_location_id\x18\x02 \x01(\tH\x00R\x10reasonLocationId\x88\x01\x01\x125\n" +
	"\x17reason_is_near_location\x18\x03 \x01(\bR\x14reasonIsNearLocationB\x15\n" +
	"\x13_reason_location_id\"\xa5\a\n" +
	"\bSchedule\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vschedule_id\x18\x04 \x01(\tR\n" +
	"scheduleId\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\tR\x03uid\x12\x1a\n" +
	"\bheadcode\x18\b \x01(\tR\bheadcode\x12/\n" +
	"\x11retail_service_id\x18\t \x01(\tH\x00R\x0fretailServiceId\x88\x01\x01\x12\x15\n" +
	"\x06toc_id\x18\n" +
	" \x01(\tR\x05tocId\x12&\n" +
	"\aservice\x18\v \x01(\x0e2\f.ServiceTypeR\aservice\x12)\n" +
	"\bcategory\x18\f \x01(\x0e2\r.CategoryTypeR\bcategory\x120\n" +
	"\x14is_passenger_service\x18\r \x01(\bR\x12isPassengerService\x12\x1b\n" +
	"\tis_active\x18\x0e \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"is_charter\x18\x10 \x01(\bR\tisCharter\x12!\n" +
	"\fis_cancelled\x18\x11 \x01(\bR\visCancelled\x12G\n" +
	"\x13cancellation_reason\x18\x12 \x01(\v2\x11.DisruptionReasonH\x01R\x12cancellationReason\x88\x01\x01\x12<\n" +
	"\x18diverted_via_location_id\x18\x13 \x01(\tH\x02R\x15divertedViaLocationId\x88\x01\x01\x12A\n" +
	"\x10diversion_reason\x18\x14 \x01(\v2\x11.DisruptionReasonH\x03R\x0fdiversionReason\x88\x01\x01\x123\n" +
	"\bforecast\x18\x15 \x01(\v2\x12.Schedule.ForecastH\x04R\bforecast\x88\x01\x01\x1a\x8b\x01\n" +
	"\bForecast\x120\n" +
	"\x14is_reverse_formation\x18\x04 \x01(\bR\x12isReverseFormation\x127\n" +
	"\vlate_reason\x18\x05 \x01(\v2\x11.DisruptionReasonH\x00R\n" +
	"lateReason\x88\x01\x01B\x0e\n" +
	"\f_late_reasonJ\x04\b\x01\x10\x04B\x14\n" +
	"\x12_retail_service_idB\x16\n" +
	"\x14_cancellation_reasonB\x1b\n" +
	"\x19_diverted_via_location_idB\x13\n" +
	"\x11_diversion_reasonB\v\n" +
	"\t_forecastJ\x04\b\x02\x10\x04J\x04\b\x06\x10\bJ\x04\b\x0f\x10\x10\"\x8f\x04\n" +
	"\tFormation\x12!\n" +
	"\fformation_id\x18\x04 \x01(\tR\vformationId\x12\x1b\n" +
	"\x06source\x18\x05 \x01(\tH\x00R\x06source\x88\x01\x01\x12(\n" +
	"\rsource_system\x18\x06 \x01(\tH\x01R\fsourceSystem\x88\x01\x01\x12*\n" +
	"\acoaches\x18\a \x03(\v2\x10.Formation.CoachR\acoaches\x1a\xc8\x02\n" +
	"\x05Coach\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x19\n" +
	"\x05class\x18\x03 \x01(\tH\x00R\x05class\x88\x01\x01\x12=\n" +
	"\vtoilet_data\x18\x04 \x01(\v2\x17.Formation.Coach.ToiletH\x01R\n" +
	"toiletData\x88\x01\x01\x1a\xa4\x01\n" +
	"\x06Toilet\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.Formation.Coach.Toilet.StatusR\x06status\"N\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11STATUS_IN_SERVICE\x10\x01\x12\x19\n" +
	"\x15STATUS_NOT_IN_SERVICE\x10\x02B\b\n" +
	"\x06_classB\x0e\n" +
	"\f_toilet_dataJ\x04\b\x01\x10\x02B\t\n" +
	"\a_sourceB\x10\n" +
	"\x0e_source_systemJ\x04\b\x01\x10\x04\"\xf2\f\n" +
	"\x10ForecastLocation\x126\n" +
	"\aarrival\x18\t \x01(\v2\x17.ForecastLocation.TimesH\x00R\aarrival\x88\x01\x01\x126\n" +
	"\apassing\x18\n" +
	" \x01(\v2\x17.ForecastLocation.TimesH\x01R\apassing\x88\x01\x01\x12:\n" +
	"\tdeparture\x18\v \x01(\v2\x17.ForecastLocation.TimesH\x02R\tdeparture\x88\x01\x01\x127\n" +
	"\vlate_reason\x18\f \x01(\v2\x11.DisruptionReasonH\x03R\n" +
	"lateReason\x88\x01\x01\x12,\n" +
	"\x0fdisruption_risk\x18\r \x01(\tH\x04R\x0edisruptionRisk\x88\x01\x01\x12L\n" +
	"\x16disruption_risk_reason\x18\x0e \x01(\v2\x11.DisruptionReasonH\x05R\x14disruptionRiskReason\x88\x01\x01\x12$\n" +
	"\vaffected_by\x18\x0f \x01(\tH\x06R\n" +
	"affectedBy\x88\x01\x01\x12,\n" +
	"\x0fforecast_length\x18\x10 \x01(\rH\aR\x0eforecastLength\x88\x01\x01\x12L\n" +
	"\x11forecast_platform\x18\x11 \x01(\v2\x1a.ForecastLocation.PlatformH\bR\x10forecastPlatform\x88\x01\x01\x12;\n" +
	"\x1aservice_is_suppressed_here\x18\x12 \x01(\bR\x17serviceIsSuppressedHere\x12F\n" +
	" service_detaches_from_front_here\x18\x13 \x01(\bR\x1cserviceDetachesFromFrontHere\x1a\xe5\x04\n" +
	"\x05Times\x127\n" +
	"\x15estimated_public_time\x18\x01 \x01(\tH\x00R\x13estimatedPublicTime\x88\x01\x01\x129\n" +
	"\x16estimated_working_time\x18\x02 \x01(\tH\x01R\x14estimatedWorkingTime\x88\x01\x01\x129\n" +
	"\x16minimum_estimated_time\x18\x03 \x01(\tH\x02R\x14minimumEstimatedTime\x88\x01\x01\x12J\n" +
	"\"estimation_manually_set_to_delayed\x18\x04 \x01(\bR\x1eestimationManuallySetToDelayed\x120\n" +
	"\x14estimated_as_delayed\x18\x05 \x01(\bR\x12estimatedAsDelayed\x12$\n" +
	"\vactual_time\x18\x06 \x01(\tH\x03R\n" +
	"actualTime\x88\x01\x01\x12/\n" +
	"\x11actual_time_class\x18\a \x01(\tH\x04R\x0factualTimeClass\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\b \x01(\tH\x05R\x06source\x88\x01\x01\x12(\n" +
	"\rsource_system\x18\t \x01(\tH\x06R\fsourceSystem\x88\x01\x01B\x18\n" +
	"\x16_estimated_public_timeB\x19\n" +
	"\x17_estimated_working_timeB\x19\n" +
	"\x17_minimum_estimated_timeB\x0e\n" +
	"\f_actual_timeB\x14\n" +
	"\x12_actual_time_classB\t\n" +
	"\a_sourceB\x10\n" +
	"\x0e_source_system\x1a\xc8\x01\n" +
	"\bPlatform\x12#\n" +
	"\ris_suppressed\x18\x01 \x01(\bR\fisSuppressed\x12@\n" +
	"\x1dis_manually_suppressed_by_cis\x18\x02 \x01(\bR\x19isManuallySuppressedByCis\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12!\n" +
	"\fis_confirmed\x18\x04 \x01(\bR\visConfirmed\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatformB\n" +
	"\n" +
	"\b_arrivalB\n" +
	"\n" +
	"\b_passingB\f\n" +
	"\n" +
	"_departureB\x0e\n" +
	"\f_late_reasonB\x12\n" +
	"\x10_disruption_riskB\x19\n" +
	"\x17_disruption_risk_reasonB\x0e\n" +
	"\f_affected_byB\x12\n" +
	"\x10_forecast_lengthB\x14\n" +
	"\x12_forecast_platformJ\x04\b\x01\x10\t\"\x88\x02\n" +
	"\x10FormationLoading\x121\n" +
	"\acoaches\x18\v \x03(\v2\x17.FormationLoading.CoachR\acoaches\x1a\xba\x01\n" +
	"\x05Coach\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x1b\n" +
	"\x06source\x18\x03 \x01(\tH\x00R\x06source\x88\x01\x01\x12(\n" +
	"\rsource_system\x18\x04 \x01(\tH\x01R\fsourceSystem\x88\x01\x01\x12'\n" +
	"\x0fpercentage_load\x18\x05 \x01(\rR\x0epercentageLoadB\t\n" +
	"\a_sourceB\x10\n" +
	"\x0e_source_systemJ\x04\b\x01\x10\x02J\x04\b\x01\x10\v\"\xc3\v\n" +
	"\x10ScheduleLocation\x12#\n" +
	"\rschedule_uuid\x18\x02 \x01(\tR\fscheduleUuid\x12\x1f\n" +
	"\vcomputed_id\x18\x03 \x01(\fR\n" +
	"computedId\x12\x1f\n" +
	"\vlocation_id\x18\x05 \x01(\tR\n" +
	"locationId\x12-\n" +
	"\n" +
	"activities\x18\x06 \x03(\x0e2\r.ActivityTypeR\n" +
	"activities\x12<\n" +
	"\x12planned_activities\x18\a \x03(\x0e2\r.ActivityTypeR\x11plannedActivities\x12&\n" +
	"\fformation_id\x18\b \x01(\tH\x00R\vformationId\x88\x01\x01\x127\n" +
	"\x18is_affected_by_diversion\x18\t \x01(\bR\x15isAffectedByDiversion\x12*\n" +
	"\x04type\x18\n" +
	" \x01(\x0e2\x16.ScheduleLocation.TypeR\x04type\x125\n" +
	"\x14working_arrival_time\x18\v \x01(\tH\x01R\x12workingArrivalTime\x88\x01\x01\x125\n" +
	"\x14working_passing_time\x18\f \x01(\tH\x02R\x12workingPassingTime\x88\x01\x01\x129\n" +
	"\x16working_departure_time\x18\r \x01(\tH\x03R\x14workingDepartureTime\x88\x01\x01\x123\n" +
	"\x13public_arrival_time\x18\x0e \x01(\tH\x04R\x11publicArrivalTime\x88\x01\x01\x127\n" +
	"\x15public_departure_time\x18\x0f \x01(\tH\x05R\x13publicDepartureTime\x88\x01\x01\x12#\n" +
	"\rrouting_delay\x18\x10 \x01(\x05R\froutingDelay\x12F\n" +
	"\x1dfalse_destination_location_id\x18\x11 \x01(\tH\x06R\x1afalseDestinationLocationId\x88\x01\x01\x12!\n" +
	"\fis_cancelled\x18\x12 \x01(\bR\visCancelled\x12X\n" +
	"\x1clocation_cancellation_reason\x18\x13 \x01(\v2\x11.DisruptionReasonH\aR\x1alocationCancellationReason\x88\x01\x01\x124\n" +
	"\x13timetabled_platform\x18\x14 \x01(\tH\bR\x12timetabledPlatform\x88\x01\x01\"\x9f\x02\n" +
	"\x04Type\x12\x19\n" +
	"\x15TYPE_LOCATION_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14TYPE_LOCATION_ORIGIN\x10\x01\x12$\n" +
	" TYPE_LOCATION_OPERATIONAL_ORIGIN\x10\x02\x12\x1e\n" +
	"\x1aTYPE_LOCATION_INTERMEDIATE\x10\x03\x12*\n" +
	"&TYPE_LOCATION_OPERATIONAL_INTERMEDIATE\x10\x04\x12&\n" +
	"\"TYPE_LOCATION_INTERMEDIATE_PASSING\x10\x05\x12\x1d\n" +
	"\x19TYPE_LOCATION_DESTINATION\x10\x06\x12)\n" +
	"%TYPE_LOCATION_OPERATIONAL_DESTINATION\x10\aB\x0f\n" +
	"\r_formation_idB\x17\n" +
	"\x15_working_arrival_timeB\x17\n" +
	"\x15_working_passing_timeB\x19\n" +
	"\x17_working_departure_timeB\x16\n" +
	"\x14_public_arrival_timeB\x18\n" +
	"\x16_public_departure_timeB \n" +
	"\x1e_false_destination_location_idB\x1f\n" +
	"\x1d_location_cancellation_reasonB\x16\n" +
	"\x14_timetabled_platformJ\x04\b\x01\x10\x02J\x04\b\x04\x10\x05\"\xfa\x04\n" +
	"\x0eServiceLoading\x129\n" +
	"\bcategory\x18\n" +
	" \x01(\v2\x18.ServiceLoading.CategoryH\x00R\bcategory\x88\x01\x01\x12?\n" +
	"\n" +
	"percentage\x18\v \x01(\v2\x1a.ServiceLoading.PercentageH\x01R\n" +
	"percentage\x88\x01\x01\x1a\xac\x01\n" +
	"\bCategory\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\x06source\x18\x02 \x01(\tH\x00R\x06source\x88\x01\x01\x12(\n" +
	"\rsource_system\x18\x03 \x01(\tH\x01R\fsourceSystem\x88\x01\x01\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.ServiceLoading.TypeR\x04typeB\t\n" +
	"\a_sourceB\x10\n" +
	"\x0e_source_system\x1a\xc3\x01\n" +
	"\n" +
	"Percentage\x12'\n" +
	"\x0fpercentage_load\x18\x01 \x01(\rR\x0epercentageLoad\x12\x1b\n" +
	"\x06source\x18\x02 \x01(\tH\x00R\x06source\x88\x01\x01\x12(\n" +
	"\rsource_system\x18\x03 \x01(\tH\x01R\fsourceSystem\x88\x01\x01\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.ServiceLoading.TypeR\x04typeB\t\n" +
	"\a_sourceB\x10\n" +
	"\x0e_source_system\"U\n" +
	"\x04Type\x12\x18\n" +
	"\x14TYPE_LOADING_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14TYPE_LOADING_TYPICAL\x10\x01\x12\x19\n" +
	"\x15TYPE_LOADING_EXPECTED\x10\x02B\v\n" +
	"\t_categoryB\r\n" +
	"\v_percentageJ\x04\b\x01\x10\n" +
	"B*Z(github.com/headblockhead/railreader-grpcb\x06proto3"

var (
	file_darwin_proto_rawDescOnce sync.Once
	file_darwin_proto_rawDescData []byte
)

func file_darwin_proto_rawDescGZIP() []byte {
	file_darwin_proto_rawDescOnce.Do(func() {
		file_darwin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_darwin_proto_rawDesc), len(file_darwin_proto_rawDesc)))
	})
	return file_darwin_proto_rawDescData
}

var file_darwin_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_darwin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_darwin_proto_goTypes = []any{
	(Formation_Coach_Toilet_Status)(0), // 0: Formation.Coach.Toilet.Status
	(ScheduleLocation_Type)(0),         // 1: ScheduleLocation.Type
	(ServiceLoading_Type)(0),           // 2: ServiceLoading.Type
	(*DisruptionReason)(nil),           // 3: DisruptionReason
	(*Schedule)(nil),                   // 4: Schedule
	(*Formation)(nil),                  // 5: Formation
	(*ForecastLocation)(nil),           // 6: ForecastLocation
	(*FormationLoading)(nil),           // 7: FormationLoading
	(*ScheduleLocation)(nil),           // 8: ScheduleLocation
	(*ServiceLoading)(nil),             // 9: ServiceLoading
	(*Schedule_Forecast)(nil),          // 10: Schedule.Forecast
	(*Formation_Coach)(nil),            // 11: Formation.Coach
	(*Formation_Coach_Toilet)(nil),     // 12: Formation.Coach.Toilet
	(*ForecastLocation_Times)(nil),     // 13: ForecastLocation.Times
	(*ForecastLocation_Platform)(nil),  // 14: ForecastLocation.Platform
	(*FormationLoading_Coach)(nil),     // 15: FormationLoading.Coach
	(*ServiceLoading_Category)(nil),    // 16: ServiceLoading.Category
	(*ServiceLoading_Percentage)(nil),  // 17: ServiceLoading.Percentage
	(ServiceType)(0),                   // 18: ServiceType
	(CategoryType)(0),                  // 19: CategoryType
	(ActivityType)(0),                  // 20: ActivityType
}
var file_darwin_proto_depIdxs = []int32{
	18, // 0: Schedule.service:type_name -> ServiceType
	19, // 1: Schedule.category:type_name -> CategoryType
	3,  // 2: Schedule.cancellation_reason:type_name -> DisruptionReason
	3,  // 3: Schedule.diversion_reason:type_name -> DisruptionReason
	10, // 4: Schedule.forecast:type_name -> Schedule.Forecast
	11, // 5: Formation.coaches:type_name -> Formation.Coach
	13, // 6: ForecastLocation.arrival:type_name -> ForecastLocation.Times
	13, // 7: ForecastLocation.passing:type_name -> ForecastLocation.Times
	13, // 8: ForecastLocation.departure:type_name -> ForecastLocation.Times
	3,  // 9: ForecastLocation.late_reason:type_name -> DisruptionReason
	3,  // 10: ForecastLocation.disruption_risk_reason:type_name -> DisruptionReason
	14, // 11: ForecastLocation.forecast_platform:type_name -> ForecastLocation.Platform
	15, // 12: FormationLoading.coaches:type_name -> FormationLoading.Coach
	20, // 13: ScheduleLocation.activities:type_name -> ActivityType
	20, // 14: ScheduleLocation.planned_activities:type_name -> ActivityType
	1,  // 15: ScheduleLocation.type:type_name -> ScheduleLocation.Type
	3,  // 16: ScheduleLocation.location_cancellation_reason:type_name -> DisruptionReason
	16, // 17: ServiceLoading.category:type_name -> ServiceLoading.Category
	17, // 18: ServiceLoading.percentage:type_name -> ServiceLoading.Percentage
	3,  // 19: Schedule.Forecast.late_reason:type_name -> DisruptionReason
	12, // 20: Formation.Coach.toilet_data:type_name -> Formation.Coach.Toilet
	0,  // 21: Formation.Coach.Toilet.status:type_name -> Formation.Coach.Toilet.Status
	2,  // 22: ServiceLoading.Category.type:type_name -> ServiceLoading.Type
	2,  // 23: ServiceLoading.Percentage.type:type_name -> ServiceLoading.Type
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_darwin_proto_init() }
func file_darwin_proto_init() {
	if File_darwin_proto != nil {
		return
	}
	file_railtypes_proto_init()
	file_darwin_proto_msgTypes[0].OneofWrappers = []any{}
	file_darwin_proto_msgTypes[1].OneofWrappers = []any{}
	file_darwin_proto_msgTypes[2].OneofWrappers = []any{}
	file_darwin_proto_msgTypes[3].OneofWrappers = []any{}
	file_darwin_proto_msgTypes[5].OneofWrappers = []any{}
	file_darwin_proto_msgTypes[6].OneofWrappers = []any{}
	file_darwin_proto_msgTypes[7].OneofWrappers = []any{}
	file_darwin_proto_msgTypes[8].OneofWrappers = []any{}
	file_darwin_proto_msgTypes[10].OneofWrappers = []any{}
	file_darwin_proto_msgTypes[12].OneofWrappers = []any{}
	file_darwin_proto_msgTypes[13].OneofWrappers = []any{}
	file_darwin_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_darwin_proto_rawDesc), len(file_darwin_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_darwin_proto_goTypes,
		DependencyIndexes: file_darwin_proto_depIdxs,
		EnumInfos:         file_darwin_proto_enumTypes,
		MessageInfos:      file_darwin_proto_msgTypes,
	}.Build()
	File_darwin_proto = out.File
	file_darwin_proto_goTypes = nil
	file_darwin_proto_depIdxs = nil
}
