// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: describeResponse.proto

package railreader_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory int32

const (
	DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_ASSOCIATION_CATEGORY_UNKNOWN DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory = 0
	DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_ASSOCIATION_CATEGORY_JOIN    DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory = 1
	DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_ASSOCIATION_CATEGORY_DIVIDE  DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory = 2
	DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_ASSOCIATION_CATEGORY_LINK    DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory = 3
	DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_ASSOCIATION_CATEGORY_NEXT    DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory = 4
)

// Enum value maps for DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory.
var (
	DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory_name = map[int32]string{
		0: "ASSOCIATION_CATEGORY_UNKNOWN",
		1: "ASSOCIATION_CATEGORY_JOIN",
		2: "ASSOCIATION_CATEGORY_DIVIDE",
		3: "ASSOCIATION_CATEGORY_LINK",
		4: "ASSOCIATION_CATEGORY_NEXT",
	}
	DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory_value = map[string]int32{
		"ASSOCIATION_CATEGORY_UNKNOWN": 0,
		"ASSOCIATION_CATEGORY_JOIN":    1,
		"ASSOCIATION_CATEGORY_DIVIDE":  2,
		"ASSOCIATION_CATEGORY_LINK":    3,
		"ASSOCIATION_CATEGORY_NEXT":    4,
	}
)

func (x DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory) Enum() *DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory {
	p := new(DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory)
	*p = x
	return p
}

func (x DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_describeResponse_proto_enumTypes[0].Descriptor()
}

func (DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory) Type() protoreflect.EnumType {
	return &file_describeResponse_proto_enumTypes[0]
}

func (x DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory.Descriptor instead.
func (DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory) EnumDescriptor() ([]byte, []int) {
	return file_describeResponse_proto_rawDescGZIP(), []int{1, 2, 0, 1, 0}
}

type DescribeResponse_RouteLocation_ScheduleLocation_LocationType int32

const (
	DescribeResponse_RouteLocation_ScheduleLocation_LOCATION_TYPE_LOCATION_UNKNOWN                  DescribeResponse_RouteLocation_ScheduleLocation_LocationType = 0
	DescribeResponse_RouteLocation_ScheduleLocation_LOCATION_TYPE_LOCATION_ORIGIN                   DescribeResponse_RouteLocation_ScheduleLocation_LocationType = 1
	DescribeResponse_RouteLocation_ScheduleLocation_LOCATION_TYPE_LOCATION_OPERATIONAL_ORIGIN       DescribeResponse_RouteLocation_ScheduleLocation_LocationType = 2
	DescribeResponse_RouteLocation_ScheduleLocation_LOCATION_TYPE_LOCATION_INTERMEDIATE             DescribeResponse_RouteLocation_ScheduleLocation_LocationType = 3
	DescribeResponse_RouteLocation_ScheduleLocation_LOCATION_TYPE_LOCATION_OPERATIONAL_INTERMEDIATE DescribeResponse_RouteLocation_ScheduleLocation_LocationType = 4
	DescribeResponse_RouteLocation_ScheduleLocation_LOCATION_TYPE_LOCATION_INTERMEDIATE_PASSING     DescribeResponse_RouteLocation_ScheduleLocation_LocationType = 5
	DescribeResponse_RouteLocation_ScheduleLocation_LOCATION_TYPE_LOCATION_DESTINATION              DescribeResponse_RouteLocation_ScheduleLocation_LocationType = 6
	DescribeResponse_RouteLocation_ScheduleLocation_LOCATION_TYPE_LOCATION_OPERATIONAL_DESTINATION  DescribeResponse_RouteLocation_ScheduleLocation_LocationType = 7
)

// Enum value maps for DescribeResponse_RouteLocation_ScheduleLocation_LocationType.
var (
	DescribeResponse_RouteLocation_ScheduleLocation_LocationType_name = map[int32]string{
		0: "LOCATION_TYPE_LOCATION_UNKNOWN",
		1: "LOCATION_TYPE_LOCATION_ORIGIN",
		2: "LOCATION_TYPE_LOCATION_OPERATIONAL_ORIGIN",
		3: "LOCATION_TYPE_LOCATION_INTERMEDIATE",
		4: "LOCATION_TYPE_LOCATION_OPERATIONAL_INTERMEDIATE",
		5: "LOCATION_TYPE_LOCATION_INTERMEDIATE_PASSING",
		6: "LOCATION_TYPE_LOCATION_DESTINATION",
		7: "LOCATION_TYPE_LOCATION_OPERATIONAL_DESTINATION",
	}
	DescribeResponse_RouteLocation_ScheduleLocation_LocationType_value = map[string]int32{
		"LOCATION_TYPE_LOCATION_UNKNOWN":                  0,
		"LOCATION_TYPE_LOCATION_ORIGIN":                   1,
		"LOCATION_TYPE_LOCATION_OPERATIONAL_ORIGIN":       2,
		"LOCATION_TYPE_LOCATION_INTERMEDIATE":             3,
		"LOCATION_TYPE_LOCATION_OPERATIONAL_INTERMEDIATE": 4,
		"LOCATION_TYPE_LOCATION_INTERMEDIATE_PASSING":     5,
		"LOCATION_TYPE_LOCATION_DESTINATION":              6,
		"LOCATION_TYPE_LOCATION_OPERATIONAL_DESTINATION":  7,
	}
)

func (x DescribeResponse_RouteLocation_ScheduleLocation_LocationType) Enum() *DescribeResponse_RouteLocation_ScheduleLocation_LocationType {
	p := new(DescribeResponse_RouteLocation_ScheduleLocation_LocationType)
	*p = x
	return p
}

func (x DescribeResponse_RouteLocation_ScheduleLocation_LocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DescribeResponse_RouteLocation_ScheduleLocation_LocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_describeResponse_proto_enumTypes[1].Descriptor()
}

func (DescribeResponse_RouteLocation_ScheduleLocation_LocationType) Type() protoreflect.EnumType {
	return &file_describeResponse_proto_enumTypes[1]
}

func (x DescribeResponse_RouteLocation_ScheduleLocation_LocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DescribeResponse_RouteLocation_ScheduleLocation_LocationType.Descriptor instead.
func (DescribeResponse_RouteLocation_ScheduleLocation_LocationType) EnumDescriptor() ([]byte, []int) {
	return file_describeResponse_proto_rawDescGZIP(), []int{1, 2, 1, 0}
}

type Forecast_PlatformDataSource int32

const (
	Forecast_PLATFORM_DATA_SOURCE_PLATFORM_UNKNOWN   Forecast_PlatformDataSource = 0
	Forecast_PLATFORM_DATA_SOURCE_PLATFORM_PLANNED   Forecast_PlatformDataSource = 1
	Forecast_PLATFORM_DATA_SOURCE_PLATFORM_AUTOMATIC Forecast_PlatformDataSource = 2
	Forecast_PLATFORM_DATA_SOURCE_PLATFORM_MANUAL    Forecast_PlatformDataSource = 3
)

// Enum value maps for Forecast_PlatformDataSource.
var (
	Forecast_PlatformDataSource_name = map[int32]string{
		0: "PLATFORM_DATA_SOURCE_PLATFORM_UNKNOWN",
		1: "PLATFORM_DATA_SOURCE_PLATFORM_PLANNED",
		2: "PLATFORM_DATA_SOURCE_PLATFORM_AUTOMATIC",
		3: "PLATFORM_DATA_SOURCE_PLATFORM_MANUAL",
	}
	Forecast_PlatformDataSource_value = map[string]int32{
		"PLATFORM_DATA_SOURCE_PLATFORM_UNKNOWN":   0,
		"PLATFORM_DATA_SOURCE_PLATFORM_PLANNED":   1,
		"PLATFORM_DATA_SOURCE_PLATFORM_AUTOMATIC": 2,
		"PLATFORM_DATA_SOURCE_PLATFORM_MANUAL":    3,
	}
)

func (x Forecast_PlatformDataSource) Enum() *Forecast_PlatformDataSource {
	p := new(Forecast_PlatformDataSource)
	*p = x
	return p
}

func (x Forecast_PlatformDataSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Forecast_PlatformDataSource) Descriptor() protoreflect.EnumDescriptor {
	return file_describeResponse_proto_enumTypes[2].Descriptor()
}

func (Forecast_PlatformDataSource) Type() protoreflect.EnumType {
	return &file_describeResponse_proto_enumTypes[2]
}

func (x Forecast_PlatformDataSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Forecast_PlatformDataSource.Descriptor instead.
func (Forecast_PlatformDataSource) EnumDescriptor() ([]byte, []int) {
	return file_describeResponse_proto_rawDescGZIP(), []int{2, 0}
}

type DisruptionReason struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReasonId         uint32                 `protobuf:"varint,1,opt,name=reason_id,json=reasonId,proto3" json:"reason_id,omitempty"`
	ReasonLocationId *string                `protobuf:"bytes,2,opt,name=reason_location_id,json=reasonLocationId,proto3,oneof" json:"reason_location_id,omitempty"`
	// When true, the provided reason_id is 'near to' the provided reason_location_id.
	// When false, the reason_id is 'at' the reason_location_id.
	ReasonIsNearLocation bool `protobuf:"varint,3,opt,name=reason_is_near_location,json=reasonIsNearLocation,proto3" json:"reason_is_near_location,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DisruptionReason) Reset() {
	*x = DisruptionReason{}
	mi := &file_describeResponse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisruptionReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisruptionReason) ProtoMessage() {}

func (x *DisruptionReason) ProtoReflect() protoreflect.Message {
	mi := &file_describeResponse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisruptionReason.ProtoReflect.Descriptor instead.
func (*DisruptionReason) Descriptor() ([]byte, []int) {
	return file_describeResponse_proto_rawDescGZIP(), []int{0}
}

func (x *DisruptionReason) GetReasonId() uint32 {
	if x != nil {
		return x.ReasonId
	}
	return 0
}

func (x *DisruptionReason) GetReasonLocationId() string {
	if x != nil && x.ReasonLocationId != nil {
		return *x.ReasonLocationId
	}
	return ""
}

func (x *DisruptionReason) GetReasonIsNearLocation() bool {
	if x != nil {
		return x.ReasonIsNearLocation
	}
	return false
}

type DescribeResponse struct {
	state                         protoimpl.MessageState            `protogen:"open.v1"`
	Schedules                     []*DescribeResponse_Schedule      `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	Formations                    []*DescribeResponse_Formation     `protobuf:"bytes,2,rep,name=formations,proto3" json:"formations,omitempty"`
	Route                         []*DescribeResponse_RouteLocation `protobuf:"bytes,3,rep,name=route,proto3" json:"route,omitempty"`
	RequestedScheduleLocationUuid string                            `protobuf:"bytes,4,opt,name=requested_schedule_location_uuid,json=requestedScheduleLocationUuid,proto3" json:"requested_schedule_location_uuid,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_describeResponse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_describeResponse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_describeResponse_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeResponse) GetSchedules() []*DescribeResponse_Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *DescribeResponse) GetFormations() []*DescribeResponse_Formation {
	if x != nil {
		return x.Formations
	}
	return nil
}

func (x *DescribeResponse) GetRoute() []*DescribeResponse_RouteLocation {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *DescribeResponse) GetRequestedScheduleLocationUuid() string {
	if x != nil {
		return x.RequestedScheduleLocationUuid
	}
	return ""
}

// estimated_public_*_time and estimated_working_*_time are Darwin's estimations of the most likely times.
// estimated_minimum_*_time is Darwin's estimation of the first possible times.
// actual_*_time are time reports from the physical train
type Forecast struct {
	state                             protoimpl.MessageState       `protogen:"open.v1"`
	IsReverseFormation                bool                         `protobuf:"varint,1,opt,name=is_reverse_formation,json=isReverseFormation,proto3" json:"is_reverse_formation,omitempty"`
	ScheduleLateReason                *DisruptionReason            `protobuf:"bytes,2,opt,name=schedule_late_reason,json=scheduleLateReason,proto3,oneof" json:"schedule_late_reason,omitempty"`
	EstimatedPublicArrivalTime        *string                      `protobuf:"bytes,3,opt,name=estimated_public_arrival_time,json=estimatedPublicArrivalTime,proto3,oneof" json:"estimated_public_arrival_time,omitempty"`
	EstimatedWorkingArrivalTime       *string                      `protobuf:"bytes,4,opt,name=estimated_working_arrival_time,json=estimatedWorkingArrivalTime,proto3,oneof" json:"estimated_working_arrival_time,omitempty"`
	EstimatedMinimumArrivalTime       *string                      `protobuf:"bytes,5,opt,name=estimated_minimum_arrival_time,json=estimatedMinimumArrivalTime,proto3,oneof" json:"estimated_minimum_arrival_time,omitempty"`
	ArrivalIsDelayed                  *bool                        `protobuf:"varint,6,opt,name=arrival_is_delayed,json=arrivalIsDelayed,proto3,oneof" json:"arrival_is_delayed,omitempty"`
	ArrivalIsDelayedByUnknownAmount   *bool                        `protobuf:"varint,7,opt,name=arrival_is_delayed_by_unknown_amount,json=arrivalIsDelayedByUnknownAmount,proto3,oneof" json:"arrival_is_delayed_by_unknown_amount,omitempty"`
	EstimatedPassingTime              *string                      `protobuf:"bytes,8,opt,name=estimated_passing_time,json=estimatedPassingTime,proto3,oneof" json:"estimated_passing_time,omitempty"`
	EstimatedMinimumPassingTime       *string                      `protobuf:"bytes,9,opt,name=estimated_minimum_passing_time,json=estimatedMinimumPassingTime,proto3,oneof" json:"estimated_minimum_passing_time,omitempty"`
	PassingIsDelayed                  *bool                        `protobuf:"varint,10,opt,name=passing_is_delayed,json=passingIsDelayed,proto3,oneof" json:"passing_is_delayed,omitempty"`
	PassingIsDelayedByUnknownAmount   *bool                        `protobuf:"varint,11,opt,name=passing_is_delayed_by_unknown_amount,json=passingIsDelayedByUnknownAmount,proto3,oneof" json:"passing_is_delayed_by_unknown_amount,omitempty"`
	EstimatedPublicDepartureTime      *string                      `protobuf:"bytes,12,opt,name=estimated_public_departure_time,json=estimatedPublicDepartureTime,proto3,oneof" json:"estimated_public_departure_time,omitempty"`
	EstimatedWorkingDepartureTime     *string                      `protobuf:"bytes,13,opt,name=estimated_working_departure_time,json=estimatedWorkingDepartureTime,proto3,oneof" json:"estimated_working_departure_time,omitempty"`
	EstimatedMinimumDepartureTime     *string                      `protobuf:"bytes,14,opt,name=estimated_minimum_departure_time,json=estimatedMinimumDepartureTime,proto3,oneof" json:"estimated_minimum_departure_time,omitempty"`
	DepartureIsDelayed                *bool                        `protobuf:"varint,15,opt,name=departure_is_delayed,json=departureIsDelayed,proto3,oneof" json:"departure_is_delayed,omitempty"`
	DepartureIsDelayedByUnknownAmount *bool                        `protobuf:"varint,16,opt,name=departure_is_delayed_by_unknown_amount,json=departureIsDelayedByUnknownAmount,proto3,oneof" json:"departure_is_delayed_by_unknown_amount,omitempty"`
	ActualArrivalTime                 *string                      `protobuf:"bytes,17,opt,name=actual_arrival_time,json=actualArrivalTime,proto3,oneof" json:"actual_arrival_time,omitempty"`
	ActualArrivalDataClass            *string                      `protobuf:"bytes,18,opt,name=actual_arrival_data_class,json=actualArrivalDataClass,proto3,oneof" json:"actual_arrival_data_class,omitempty"`
	ActualArrivalDataSource           *string                      `protobuf:"bytes,19,opt,name=actual_arrival_data_source,json=actualArrivalDataSource,proto3,oneof" json:"actual_arrival_data_source,omitempty"`
	ActualArrivalDataSourceSystem     *string                      `protobuf:"bytes,20,opt,name=actual_arrival_data_source_system,json=actualArrivalDataSourceSystem,proto3,oneof" json:"actual_arrival_data_source_system,omitempty"`
	ActualPassingTime                 *string                      `protobuf:"bytes,21,opt,name=actual_passing_time,json=actualPassingTime,proto3,oneof" json:"actual_passing_time,omitempty"`
	ActualPassingDataClass            *string                      `protobuf:"bytes,22,opt,name=actual_passing_data_class,json=actualPassingDataClass,proto3,oneof" json:"actual_passing_data_class,omitempty"`
	ActualPassingDataSource           *string                      `protobuf:"bytes,23,opt,name=actual_passing_data_source,json=actualPassingDataSource,proto3,oneof" json:"actual_passing_data_source,omitempty"`
	ActualPassingDataSourceSystem     *string                      `protobuf:"bytes,24,opt,name=actual_passing_data_source_system,json=actualPassingDataSourceSystem,proto3,oneof" json:"actual_passing_data_source_system,omitempty"`
	ActualDepartureTime               *string                      `protobuf:"bytes,25,opt,name=actual_departure_time,json=actualDepartureTime,proto3,oneof" json:"actual_departure_time,omitempty"`
	ActualDepartureDataClass          *string                      `protobuf:"bytes,26,opt,name=actual_departure_data_class,json=actualDepartureDataClass,proto3,oneof" json:"actual_departure_data_class,omitempty"`
	ActualDepartureDataSource         *string                      `protobuf:"bytes,27,opt,name=actual_departure_data_source,json=actualDepartureDataSource,proto3,oneof" json:"actual_departure_data_source,omitempty"`
	ActualDepartureDataSourceSystem   *string                      `protobuf:"bytes,28,opt,name=actual_departure_data_source_system,json=actualDepartureDataSourceSystem,proto3,oneof" json:"actual_departure_data_source_system,omitempty"`
	LocationLateReason                *DisruptionReason            `protobuf:"bytes,29,opt,name=location_late_reason,json=locationLateReason,proto3,oneof" json:"location_late_reason,omitempty"`
	LocationDisruptionRisk            *string                      `protobuf:"bytes,30,opt,name=location_disruption_risk,json=locationDisruptionRisk,proto3,oneof" json:"location_disruption_risk,omitempty"`
	LocationDisruptionRiskReason      *DisruptionReason            `protobuf:"bytes,31,opt,name=location_disruption_risk_reason,json=locationDisruptionRiskReason,proto3,oneof" json:"location_disruption_risk_reason,omitempty"`
	AffectedBy                        *string                      `protobuf:"bytes,32,opt,name=affected_by,json=affectedBy,proto3,oneof" json:"affected_by,omitempty"`
	PlatformIsSuppressed              *bool                        `protobuf:"varint,33,opt,name=platform_is_suppressed,json=platformIsSuppressed,proto3,oneof" json:"platform_is_suppressed,omitempty"` // do not display platform information if true
	PlatformIsSuppressedByCis         *bool                        `protobuf:"varint,34,opt,name=platform_is_suppressed_by_cis,json=platformIsSuppressedByCis,proto3,oneof" json:"platform_is_suppressed_by_cis,omitempty"`
	PlatformDataSource                *Forecast_PlatformDataSource `protobuf:"varint,35,opt,name=platform_data_source,json=platformDataSource,proto3,enum=Forecast_PlatformDataSource,oneof" json:"platform_data_source,omitempty"`
	PlatformIsConfirmed               *bool                        `protobuf:"varint,36,opt,name=platform_is_confirmed,json=platformIsConfirmed,proto3,oneof" json:"platform_is_confirmed,omitempty"`
	ServiceIsSuppressed               bool                         `protobuf:"varint,37,opt,name=service_is_suppressed,json=serviceIsSuppressed,proto3" json:"service_is_suppressed,omitempty"`
	ServiceDetatchesFromFront         bool                         `protobuf:"varint,38,opt,name=service_detatches_from_front,json=serviceDetatchesFromFront,proto3" json:"service_detatches_from_front,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *Forecast) Reset() {
	*x = Forecast{}
	mi := &file_describeResponse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forecast) ProtoMessage() {}

func (x *Forecast) ProtoReflect() protoreflect.Message {
	mi := &file_describeResponse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forecast.ProtoReflect.Descriptor instead.
func (*Forecast) Descriptor() ([]byte, []int) {
	return file_describeResponse_proto_rawDescGZIP(), []int{2}
}

func (x *Forecast) GetIsReverseFormation() bool {
	if x != nil {
		return x.IsReverseFormation
	}
	return false
}

func (x *Forecast) GetScheduleLateReason() *DisruptionReason {
	if x != nil {
		return x.ScheduleLateReason
	}
	return nil
}

func (x *Forecast) GetEstimatedPublicArrivalTime() string {
	if x != nil && x.EstimatedPublicArrivalTime != nil {
		return *x.EstimatedPublicArrivalTime
	}
	return ""
}

func (x *Forecast) GetEstimatedWorkingArrivalTime() string {
	if x != nil && x.EstimatedWorkingArrivalTime != nil {
		return *x.EstimatedWorkingArrivalTime
	}
	return ""
}

func (x *Forecast) GetEstimatedMinimumArrivalTime() string {
	if x != nil && x.EstimatedMinimumArrivalTime != nil {
		return *x.EstimatedMinimumArrivalTime
	}
	return ""
}

func (x *Forecast) GetArrivalIsDelayed() bool {
	if x != nil && x.ArrivalIsDelayed != nil {
		return *x.ArrivalIsDelayed
	}
	return false
}

func (x *Forecast) GetArrivalIsDelayedByUnknownAmount() bool {
	if x != nil && x.ArrivalIsDelayedByUnknownAmount != nil {
		return *x.ArrivalIsDelayedByUnknownAmount
	}
	return false
}

func (x *Forecast) GetEstimatedPassingTime() string {
	if x != nil && x.EstimatedPassingTime != nil {
		return *x.EstimatedPassingTime
	}
	return ""
}

func (x *Forecast) GetEstimatedMinimumPassingTime() string {
	if x != nil && x.EstimatedMinimumPassingTime != nil {
		return *x.EstimatedMinimumPassingTime
	}
	return ""
}

func (x *Forecast) GetPassingIsDelayed() bool {
	if x != nil && x.PassingIsDelayed != nil {
		return *x.PassingIsDelayed
	}
	return false
}

func (x *Forecast) GetPassingIsDelayedByUnknownAmount() bool {
	if x != nil && x.PassingIsDelayedByUnknownAmount != nil {
		return *x.PassingIsDelayedByUnknownAmount
	}
	return false
}

func (x *Forecast) GetEstimatedPublicDepartureTime() string {
	if x != nil && x.EstimatedPublicDepartureTime != nil {
		return *x.EstimatedPublicDepartureTime
	}
	return ""
}

func (x *Forecast) GetEstimatedWorkingDepartureTime() string {
	if x != nil && x.EstimatedWorkingDepartureTime != nil {
		return *x.EstimatedWorkingDepartureTime
	}
	return ""
}

func (x *Forecast) GetEstimatedMinimumDepartureTime() string {
	if x != nil && x.EstimatedMinimumDepartureTime != nil {
		return *x.EstimatedMinimumDepartureTime
	}
	return ""
}

func (x *Forecast) GetDepartureIsDelayed() bool {
	if x != nil && x.DepartureIsDelayed != nil {
		return *x.DepartureIsDelayed
	}
	return false
}

func (x *Forecast) GetDepartureIsDelayedByUnknownAmount() bool {
	if x != nil && x.DepartureIsDelayedByUnknownAmount != nil {
		return *x.DepartureIsDelayedByUnknownAmount
	}
	return false
}

func (x *Forecast) GetActualArrivalTime() string {
	if x != nil && x.ActualArrivalTime != nil {
		return *x.ActualArrivalTime
	}
	return ""
}

func (x *Forecast) GetActualArrivalDataClass() string {
	if x != nil && x.ActualArrivalDataClass != nil {
		return *x.ActualArrivalDataClass
	}
	return ""
}

func (x *Forecast) GetActualArrivalDataSource() string {
	if x != nil && x.ActualArrivalDataSource != nil {
		return *x.ActualArrivalDataSource
	}
	return ""
}

func (x *Forecast) GetActualArrivalDataSourceSystem() string {
	if x != nil && x.ActualArrivalDataSourceSystem != nil {
		return *x.ActualArrivalDataSourceSystem
	}
	return ""
}

func (x *Forecast) GetActualPassingTime() string {
	if x != nil && x.ActualPassingTime != nil {
		return *x.ActualPassingTime
	}
	return ""
}

func (x *Forecast) GetActualPassingDataClass() string {
	if x != nil && x.ActualPassingDataClass != nil {
		return *x.ActualPassingDataClass
	}
	return ""
}

func (x *Forecast) GetActualPassingDataSource() string {
	if x != nil && x.ActualPassingDataSource != nil {
		return *x.ActualPassingDataSource
	}
	return ""
}

func (x *Forecast) GetActualPassingDataSourceSystem() string {
	if x != nil && x.ActualPassingDataSourceSystem != nil {
		return *x.ActualPassingDataSourceSystem
	}
	return ""
}

func (x *Forecast) GetActualDepartureTime() string {
	if x != nil && x.ActualDepartureTime != nil {
		return *x.ActualDepartureTime
	}
	return ""
}

func (x *Forecast) GetActualDepartureDataClass() string {
	if x != nil && x.ActualDepartureDataClass != nil {
		return *x.ActualDepartureDataClass
	}
	return ""
}

func (x *Forecast) GetActualDepartureDataSource() string {
	if x != nil && x.ActualDepartureDataSource != nil {
		return *x.ActualDepartureDataSource
	}
	return ""
}

func (x *Forecast) GetActualDepartureDataSourceSystem() string {
	if x != nil && x.ActualDepartureDataSourceSystem != nil {
		return *x.ActualDepartureDataSourceSystem
	}
	return ""
}

func (x *Forecast) GetLocationLateReason() *DisruptionReason {
	if x != nil {
		return x.LocationLateReason
	}
	return nil
}

func (x *Forecast) GetLocationDisruptionRisk() string {
	if x != nil && x.LocationDisruptionRisk != nil {
		return *x.LocationDisruptionRisk
	}
	return ""
}

func (x *Forecast) GetLocationDisruptionRiskReason() *DisruptionReason {
	if x != nil {
		return x.LocationDisruptionRiskReason
	}
	return nil
}

func (x *Forecast) GetAffectedBy() string {
	if x != nil && x.AffectedBy != nil {
		return *x.AffectedBy
	}
	return ""
}

func (x *Forecast) GetPlatformIsSuppressed() bool {
	if x != nil && x.PlatformIsSuppressed != nil {
		return *x.PlatformIsSuppressed
	}
	return false
}

func (x *Forecast) GetPlatformIsSuppressedByCis() bool {
	if x != nil && x.PlatformIsSuppressedByCis != nil {
		return *x.PlatformIsSuppressedByCis
	}
	return false
}

func (x *Forecast) GetPlatformDataSource() Forecast_PlatformDataSource {
	if x != nil && x.PlatformDataSource != nil {
		return *x.PlatformDataSource
	}
	return Forecast_PLATFORM_DATA_SOURCE_PLATFORM_UNKNOWN
}

func (x *Forecast) GetPlatformIsConfirmed() bool {
	if x != nil && x.PlatformIsConfirmed != nil {
		return *x.PlatformIsConfirmed
	}
	return false
}

func (x *Forecast) GetServiceIsSuppressed() bool {
	if x != nil {
		return x.ServiceIsSuppressed
	}
	return false
}

func (x *Forecast) GetServiceDetatchesFromFront() bool {
	if x != nil {
		return x.ServiceDetatchesFromFront
	}
	return false
}

type DescribeResponse_Schedule struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Uuid                  string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ScheduleId            string                 `protobuf:"bytes,4,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Uid                   string                 `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Headcode              string                 `protobuf:"bytes,8,opt,name=headcode,proto3" json:"headcode,omitempty"`
	RetailServiceId       *string                `protobuf:"bytes,9,opt,name=retail_service_id,json=retailServiceId,proto3,oneof" json:"retail_service_id,omitempty"`
	TocId                 string                 `protobuf:"bytes,10,opt,name=toc_id,json=tocId,proto3" json:"toc_id,omitempty"`
	Service               ServiceType            `protobuf:"varint,11,opt,name=service,proto3,enum=ServiceType" json:"service,omitempty"`
	Category              CategoryType           `protobuf:"varint,12,opt,name=category,proto3,enum=CategoryType" json:"category,omitempty"`
	IsPassengerService    bool                   `protobuf:"varint,13,opt,name=is_passenger_service,json=isPassengerService,proto3" json:"is_passenger_service,omitempty"`
	IsActive              bool                   `protobuf:"varint,14,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsCharter             bool                   `protobuf:"varint,16,opt,name=is_charter,json=isCharter,proto3" json:"is_charter,omitempty"`
	IsCancelled           bool                   `protobuf:"varint,17,opt,name=is_cancelled,json=isCancelled,proto3" json:"is_cancelled,omitempty"`
	CancellationReason    *DisruptionReason      `protobuf:"bytes,18,opt,name=cancellation_reason,json=cancellationReason,proto3,oneof" json:"cancellation_reason,omitempty"`
	DivertedViaLocationId *string                `protobuf:"bytes,19,opt,name=diverted_via_location_id,json=divertedViaLocationId,proto3,oneof" json:"diverted_via_location_id,omitempty"`
	DiversionReason       *DisruptionReason      `protobuf:"bytes,20,opt,name=diversion_reason,json=diversionReason,proto3,oneof" json:"diversion_reason,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DescribeResponse_Schedule) Reset() {
	*x = DescribeResponse_Schedule{}
	mi := &file_describeResponse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse_Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse_Schedule) ProtoMessage() {}

func (x *DescribeResponse_Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_describeResponse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse_Schedule.ProtoReflect.Descriptor instead.
func (*DescribeResponse_Schedule) Descriptor() ([]byte, []int) {
	return file_describeResponse_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DescribeResponse_Schedule) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DescribeResponse_Schedule) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *DescribeResponse_Schedule) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DescribeResponse_Schedule) GetHeadcode() string {
	if x != nil {
		return x.Headcode
	}
	return ""
}

func (x *DescribeResponse_Schedule) GetRetailServiceId() string {
	if x != nil && x.RetailServiceId != nil {
		return *x.RetailServiceId
	}
	return ""
}

func (x *DescribeResponse_Schedule) GetTocId() string {
	if x != nil {
		return x.TocId
	}
	return ""
}

func (x *DescribeResponse_Schedule) GetService() ServiceType {
	if x != nil {
		return x.Service
	}
	return ServiceType_SERVICE_TYPE_SERVICE_UNKNOWN
}

func (x *DescribeResponse_Schedule) GetCategory() CategoryType {
	if x != nil {
		return x.Category
	}
	return CategoryType_CATEGORY_TYPE_CATEGORY_UNKNOWN
}

func (x *DescribeResponse_Schedule) GetIsPassengerService() bool {
	if x != nil {
		return x.IsPassengerService
	}
	return false
}

func (x *DescribeResponse_Schedule) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *DescribeResponse_Schedule) GetIsCharter() bool {
	if x != nil {
		return x.IsCharter
	}
	return false
}

func (x *DescribeResponse_Schedule) GetIsCancelled() bool {
	if x != nil {
		return x.IsCancelled
	}
	return false
}

func (x *DescribeResponse_Schedule) GetCancellationReason() *DisruptionReason {
	if x != nil {
		return x.CancellationReason
	}
	return nil
}

func (x *DescribeResponse_Schedule) GetDivertedViaLocationId() string {
	if x != nil && x.DivertedViaLocationId != nil {
		return *x.DivertedViaLocationId
	}
	return ""
}

func (x *DescribeResponse_Schedule) GetDiversionReason() *DisruptionReason {
	if x != nil {
		return x.DiversionReason
	}
	return nil
}

type DescribeResponse_Formation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse_Formation) Reset() {
	*x = DescribeResponse_Formation{}
	mi := &file_describeResponse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse_Formation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse_Formation) ProtoMessage() {}

func (x *DescribeResponse_Formation) ProtoReflect() protoreflect.Message {
	mi := &file_describeResponse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse_Formation.ProtoReflect.Descriptor instead.
func (*DescribeResponse_Formation) Descriptor() ([]byte, []int) {
	return file_describeResponse_proto_rawDescGZIP(), []int{1, 1}
}

type DescribeResponse_RouteLocation struct {
	state                 protoimpl.MessageState                              `protogen:"open.v1"`
	NextEdges             []*DescribeResponse_RouteLocation_RouteLocationEdge `protobuf:"bytes,1,rep,name=next_edges,json=nextEdges,proto3" json:"next_edges,omitempty"`
	PreviousEdges         []*DescribeResponse_RouteLocation_RouteLocationEdge `protobuf:"bytes,2,rep,name=previous_edges,json=previousEdges,proto3" json:"previous_edges,omitempty"`
	ScheduleLocation      *DescribeResponse_RouteLocation_ScheduleLocation    `protobuf:"bytes,5,opt,name=schedule_location,json=scheduleLocation,proto3" json:"schedule_location,omitempty"`
	CurrentPlatform       *string                                             `protobuf:"bytes,12,opt,name=current_platform,json=currentPlatform,proto3,oneof" json:"current_platform,omitempty"`
	GenerousArrivalTime   *string                                             `protobuf:"bytes,13,opt,name=generous_arrival_time,json=generousArrivalTime,proto3,oneof" json:"generous_arrival_time,omitempty"`
	GenerousPassingTime   *string                                             `protobuf:"bytes,14,opt,name=generous_passing_time,json=generousPassingTime,proto3,oneof" json:"generous_passing_time,omitempty"`
	GenerousDepartureTime *string                                             `protobuf:"bytes,15,opt,name=generous_departure_time,json=generousDepartureTime,proto3,oneof" json:"generous_departure_time,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DescribeResponse_RouteLocation) Reset() {
	*x = DescribeResponse_RouteLocation{}
	mi := &file_describeResponse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse_RouteLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse_RouteLocation) ProtoMessage() {}

func (x *DescribeResponse_RouteLocation) ProtoReflect() protoreflect.Message {
	mi := &file_describeResponse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse_RouteLocation.ProtoReflect.Descriptor instead.
func (*DescribeResponse_RouteLocation) Descriptor() ([]byte, []int) {
	return file_describeResponse_proto_rawDescGZIP(), []int{1, 2}
}

func (x *DescribeResponse_RouteLocation) GetNextEdges() []*DescribeResponse_RouteLocation_RouteLocationEdge {
	if x != nil {
		return x.NextEdges
	}
	return nil
}

func (x *DescribeResponse_RouteLocation) GetPreviousEdges() []*DescribeResponse_RouteLocation_RouteLocationEdge {
	if x != nil {
		return x.PreviousEdges
	}
	return nil
}

func (x *DescribeResponse_RouteLocation) GetScheduleLocation() *DescribeResponse_RouteLocation_ScheduleLocation {
	if x != nil {
		return x.ScheduleLocation
	}
	return nil
}

func (x *DescribeResponse_RouteLocation) GetCurrentPlatform() string {
	if x != nil && x.CurrentPlatform != nil {
		return *x.CurrentPlatform
	}
	return ""
}

func (x *DescribeResponse_RouteLocation) GetGenerousArrivalTime() string {
	if x != nil && x.GenerousArrivalTime != nil {
		return *x.GenerousArrivalTime
	}
	return ""
}

func (x *DescribeResponse_RouteLocation) GetGenerousPassingTime() string {
	if x != nil && x.GenerousPassingTime != nil {
		return *x.GenerousPassingTime
	}
	return ""
}

func (x *DescribeResponse_RouteLocation) GetGenerousDepartureTime() string {
	if x != nil && x.GenerousDepartureTime != nil {
		return *x.GenerousDepartureTime
	}
	return ""
}

type DescribeResponse_RouteLocation_RouteLocationEdge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Edge:
	//
	//	*DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge_
	//	*DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_
	Edge          isDescribeResponse_RouteLocation_RouteLocationEdge_Edge `protobuf_oneof:"edge"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge) Reset() {
	*x = DescribeResponse_RouteLocation_RouteLocationEdge{}
	mi := &file_describeResponse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse_RouteLocation_RouteLocationEdge) ProtoMessage() {}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge) ProtoReflect() protoreflect.Message {
	mi := &file_describeResponse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse_RouteLocation_RouteLocationEdge.ProtoReflect.Descriptor instead.
func (*DescribeResponse_RouteLocation_RouteLocationEdge) Descriptor() ([]byte, []int) {
	return file_describeResponse_proto_rawDescGZIP(), []int{1, 2, 0}
}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge) GetEdge() isDescribeResponse_RouteLocation_RouteLocationEdge_Edge {
	if x != nil {
		return x.Edge
	}
	return nil
}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge) GetScheduleEdge() *DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge {
	if x != nil {
		if x, ok := x.Edge.(*DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge_); ok {
			return x.ScheduleEdge
		}
	}
	return nil
}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge) GetAssociationEdge() *DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge {
	if x != nil {
		if x, ok := x.Edge.(*DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_); ok {
			return x.AssociationEdge
		}
	}
	return nil
}

type isDescribeResponse_RouteLocation_RouteLocationEdge_Edge interface {
	isDescribeResponse_RouteLocation_RouteLocationEdge_Edge()
}

type DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge_ struct {
	ScheduleEdge *DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge `protobuf:"bytes,1,opt,name=schedule_edge,json=scheduleEdge,proto3,oneof"`
}

type DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_ struct {
	AssociationEdge *DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge `protobuf:"bytes,2,opt,name=association_edge,json=associationEdge,proto3,oneof"`
}

func (*DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge_) isDescribeResponse_RouteLocation_RouteLocationEdge_Edge() {
}

func (*DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_) isDescribeResponse_RouteLocation_RouteLocationEdge_Edge() {
}

// 'Working' times are used internally by staff
// 'Public' times are used for display to passengers
// Working and Public timetables may differ, typically to allow services to experience very minor (30 to 60s) delays without appearing late to the public.
// There is no scheduled_public_passing_time because locations through which a service passes without stopping do not need to display any times to the public.
type DescribeResponse_RouteLocation_ScheduleLocation struct {
	state                      protoimpl.MessageState                                       `protogen:"open.v1"`
	Uuid                       string                                                       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ScheduleUuid               string                                                       `protobuf:"bytes,2,opt,name=schedule_uuid,json=scheduleUuid,proto3" json:"schedule_uuid,omitempty"`
	ScheduleOrder              uint32                                                       `protobuf:"varint,3,opt,name=schedule_order,json=scheduleOrder,proto3" json:"schedule_order,omitempty"`
	LocationId                 string                                                       `protobuf:"bytes,4,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Activities                 []ActivityType                                               `protobuf:"varint,5,rep,packed,name=activities,proto3,enum=ActivityType" json:"activities,omitempty"`
	PlannedActivities          []ActivityType                                               `protobuf:"varint,6,rep,packed,name=planned_activities,json=plannedActivities,proto3,enum=ActivityType" json:"planned_activities,omitempty"`
	FormationId                *string                                                      `protobuf:"bytes,7,opt,name=formation_id,json=formationId,proto3,oneof" json:"formation_id,omitempty"`
	IsAffectedByDiversion      bool                                                         `protobuf:"varint,8,opt,name=is_affected_by_diversion,json=isAffectedByDiversion,proto3" json:"is_affected_by_diversion,omitempty"`
	Type                       DescribeResponse_RouteLocation_ScheduleLocation_LocationType `protobuf:"varint,9,opt,name=type,proto3,enum=DescribeResponse_RouteLocation_ScheduleLocation_LocationType" json:"type,omitempty"`
	WorkingArrivalTime         *string                                                      `protobuf:"bytes,10,opt,name=working_arrival_time,json=workingArrivalTime,proto3,oneof" json:"working_arrival_time,omitempty"`
	WorkingPassingTime         *string                                                      `protobuf:"bytes,11,opt,name=working_passing_time,json=workingPassingTime,proto3,oneof" json:"working_passing_time,omitempty"`
	WorkingDepartureTime       *string                                                      `protobuf:"bytes,12,opt,name=working_departure_time,json=workingDepartureTime,proto3,oneof" json:"working_departure_time,omitempty"`
	PublicArrivalTime          *string                                                      `protobuf:"bytes,13,opt,name=public_arrival_time,json=publicArrivalTime,proto3,oneof" json:"public_arrival_time,omitempty"`
	PublicDepartureTime        *string                                                      `protobuf:"bytes,14,opt,name=public_departure_time,json=publicDepartureTime,proto3,oneof" json:"public_departure_time,omitempty"`
	RoutingDelay               uint32                                                       `protobuf:"varint,15,opt,name=routing_delay,json=routingDelay,proto3" json:"routing_delay,omitempty"` // in minutes
	FalseDestinationLocationId *string                                                      `protobuf:"bytes,16,opt,name=false_destination_location_id,json=falseDestinationLocationId,proto3,oneof" json:"false_destination_location_id,omitempty"`
	IsCancelled                bool                                                         `protobuf:"varint,17,opt,name=is_cancelled,json=isCancelled,proto3" json:"is_cancelled,omitempty"`
	LocationCancellationReason *DisruptionReason                                            `protobuf:"bytes,18,opt,name=location_cancellation_reason,json=locationCancellationReason,proto3,oneof" json:"location_cancellation_reason,omitempty"`
	TimetabledPlatform         *string                                                      `protobuf:"bytes,19,opt,name=timetabled_platform,json=timetabledPlatform,proto3,oneof" json:"timetabled_platform,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) Reset() {
	*x = DescribeResponse_RouteLocation_ScheduleLocation{}
	mi := &file_describeResponse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse_RouteLocation_ScheduleLocation) ProtoMessage() {}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) ProtoReflect() protoreflect.Message {
	mi := &file_describeResponse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse_RouteLocation_ScheduleLocation.ProtoReflect.Descriptor instead.
func (*DescribeResponse_RouteLocation_ScheduleLocation) Descriptor() ([]byte, []int) {
	return file_describeResponse_proto_rawDescGZIP(), []int{1, 2, 1}
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetScheduleUuid() string {
	if x != nil {
		return x.ScheduleUuid
	}
	return ""
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetScheduleOrder() uint32 {
	if x != nil {
		return x.ScheduleOrder
	}
	return 0
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetActivities() []ActivityType {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetPlannedActivities() []ActivityType {
	if x != nil {
		return x.PlannedActivities
	}
	return nil
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetFormationId() string {
	if x != nil && x.FormationId != nil {
		return *x.FormationId
	}
	return ""
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetIsAffectedByDiversion() bool {
	if x != nil {
		return x.IsAffectedByDiversion
	}
	return false
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetType() DescribeResponse_RouteLocation_ScheduleLocation_LocationType {
	if x != nil {
		return x.Type
	}
	return DescribeResponse_RouteLocation_ScheduleLocation_LOCATION_TYPE_LOCATION_UNKNOWN
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetWorkingArrivalTime() string {
	if x != nil && x.WorkingArrivalTime != nil {
		return *x.WorkingArrivalTime
	}
	return ""
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetWorkingPassingTime() string {
	if x != nil && x.WorkingPassingTime != nil {
		return *x.WorkingPassingTime
	}
	return ""
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetWorkingDepartureTime() string {
	if x != nil && x.WorkingDepartureTime != nil {
		return *x.WorkingDepartureTime
	}
	return ""
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetPublicArrivalTime() string {
	if x != nil && x.PublicArrivalTime != nil {
		return *x.PublicArrivalTime
	}
	return ""
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetPublicDepartureTime() string {
	if x != nil && x.PublicDepartureTime != nil {
		return *x.PublicDepartureTime
	}
	return ""
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetRoutingDelay() uint32 {
	if x != nil {
		return x.RoutingDelay
	}
	return 0
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetFalseDestinationLocationId() string {
	if x != nil && x.FalseDestinationLocationId != nil {
		return *x.FalseDestinationLocationId
	}
	return ""
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetIsCancelled() bool {
	if x != nil {
		return x.IsCancelled
	}
	return false
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetLocationCancellationReason() *DisruptionReason {
	if x != nil {
		return x.LocationCancellationReason
	}
	return nil
}

func (x *DescribeResponse_RouteLocation_ScheduleLocation) GetTimetabledPlatform() string {
	if x != nil && x.TimetabledPlatform != nil {
		return *x.TimetabledPlatform
	}
	return ""
}

type DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ScheduleLocationUuid string                 `protobuf:"bytes,1,opt,name=schedule_location_uuid,json=scheduleLocationUuid,proto3" json:"schedule_location_uuid,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge) Reset() {
	*x = DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge{}
	mi := &file_describeResponse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge) ProtoMessage() {}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge) ProtoReflect() protoreflect.Message {
	mi := &file_describeResponse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge.ProtoReflect.Descriptor instead.
func (*DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge) Descriptor() ([]byte, []int) {
	return file_describeResponse_proto_rawDescGZIP(), []int{1, 2, 0, 0}
}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge) GetScheduleLocationUuid() string {
	if x != nil {
		return x.ScheduleLocationUuid
	}
	return ""
}

type DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge struct {
	state                protoimpl.MessageState                                                               `protogen:"open.v1"`
	ScheduleLocationUuid string                                                                               `protobuf:"bytes,1,opt,name=schedule_location_uuid,json=scheduleLocationUuid,proto3" json:"schedule_location_uuid,omitempty"`
	AssociationCategory  DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory `protobuf:"varint,2,opt,name=association_category,json=associationCategory,proto3,enum=DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory" json:"association_category,omitempty"`
	IsCancelled          bool                                                                                 `protobuf:"varint,3,opt,name=is_cancelled,json=isCancelled,proto3" json:"is_cancelled,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge) Reset() {
	*x = DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge{}
	mi := &file_describeResponse_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge) ProtoMessage() {}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge) ProtoReflect() protoreflect.Message {
	mi := &file_describeResponse_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge.ProtoReflect.Descriptor instead.
func (*DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge) Descriptor() ([]byte, []int) {
	return file_describeResponse_proto_rawDescGZIP(), []int{1, 2, 0, 1}
}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge) GetScheduleLocationUuid() string {
	if x != nil {
		return x.ScheduleLocationUuid
	}
	return ""
}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge) GetAssociationCategory() DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory {
	if x != nil {
		return x.AssociationCategory
	}
	return DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_ASSOCIATION_CATEGORY_UNKNOWN
}

func (x *DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge) GetIsCancelled() bool {
	if x != nil {
		return x.IsCancelled
	}
	return false
}

var File_describeResponse_proto protoreflect.FileDescriptor

const file_describeResponse_proto_rawDesc = "" +
	"\n" +
	"\x16describeResponse.proto\x1a\x0frailtypes.proto\"\xb0\x01\n" +
	"\x10DisruptionReason\x12\x1b\n" +
	"\treason_id\x18\x01 \x01(\rR\breasonId\x121\n" +
	"\x12reason_location_id\x18\x02 \x01(\tH\x00R\x10reasonLocationId\x88\x01\x01\x125\n" +
	"\x17reason_is_near_location\x18\x03 \x01(\bR\x14reasonIsNearLocationB\x15\n" +
	"\x13_reason_location_id\"\x91\x1f\n" +
	"\x10DescribeResponse\x128\n" +
	"\tschedules\x18\x01 \x03(\v2\x1a.DescribeResponse.ScheduleR\tschedules\x12;\n" +
	"\n" +
	"formations\x18\x02 \x03(\v2\x1b.DescribeResponse.FormationR\n" +
	"formations\x125\n" +
	"\x05route\x18\x03 \x03(\v2\x1f.DescribeResponse.RouteLocationR\x05route\x12G\n" +
	" requested_schedule_location_uuid\x18\x04 \x01(\tR\x1drequestedScheduleLocationUuid\x1a\xd5\x05\n" +
	"\bSchedule\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vschedule_id\x18\x04 \x01(\tR\n" +
	"scheduleId\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\tR\x03uid\x12\x1a\n" +
	"\bheadcode\x18\b \x01(\tR\bheadcode\x12/\n" +
	"\x11retail_service_id\x18\t \x01(\tH\x00R\x0fretailServiceId\x88\x01\x01\x12\x15\n" +
	"\x06toc_id\x18\n" +
	" \x01(\tR\x05tocId\x12&\n" +
	"\aservice\x18\v \x01(\x0e2\f.ServiceTypeR\aservice\x12)\n" +
	"\bcategory\x18\f \x01(\x0e2\r.CategoryTypeR\bcategory\x120\n" +
	"\x14is_passenger_service\x18\r \x01(\bR\x12isPassengerService\x12\x1b\n" +
	"\tis_active\x18\x0e \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"is_charter\x18\x10 \x01(\bR\tisCharter\x12!\n" +
	"\fis_cancelled\x18\x11 \x01(\bR\visCancelled\x12G\n" +
	"\x13cancellation_reason\x18\x12 \x01(\v2\x11.DisruptionReasonH\x01R\x12cancellationReason\x88\x01\x01\x12<\n" +
	"\x18diverted_via_location_id\x18\x13 \x01(\tH\x02R\x15divertedViaLocationId\x88\x01\x01\x12A\n" +
	"\x10diversion_reason\x18\x14 \x01(\v2\x11.DisruptionReasonH\x03R\x0fdiversionReason\x88\x01\x01B\x14\n" +
	"\x12_retail_service_idB\x16\n" +
	"\x14_cancellation_reasonB\x1b\n" +
	"\x19_diverted_via_location_idB\x13\n" +
	"\x11_diversion_reasonJ\x04\b\x02\x10\x04J\x04\b\x06\x10\bJ\x04\b\x0f\x10\x10\x1a\v\n" +
	"\tFormation\x1a\xa0\x17\n" +
	"\rRouteLocation\x12P\n" +
	"\n" +
	"next_edges\x18\x01 \x03(\v21.DescribeResponse.RouteLocation.RouteLocationEdgeR\tnextEdges\x12X\n" +
	"\x0eprevious_edges\x18\x02 \x03(\v21.DescribeResponse.RouteLocation.RouteLocationEdgeR\rpreviousEdges\x12]\n" +
	"\x11schedule_location\x18\x05 \x01(\v20.DescribeResponse.RouteLocation.ScheduleLocationR\x10scheduleLocation\x12.\n" +
	"\x10current_platform\x18\f \x01(\tH\x00R\x0fcurrentPlatform\x88\x01\x01\x127\n" +
	"\x15generous_arrival_time\x18\r \x01(\tH\x01R\x13generousArrivalTime\x88\x01\x01\x127\n" +
	"\x15generous_passing_time\x18\x0e \x01(\tH\x02R\x13generousPassingTime\x88\x01\x01\x12;\n" +
	"\x17generous_departure_time\x18\x0f \x01(\tH\x03R\x15generousDepartureTime\x88\x01\x01\x1a\xe8\x05\n" +
	"\x11RouteLocationEdge\x12e\n" +
	"\rschedule_edge\x18\x01 \x01(\v2>.DescribeResponse.RouteLocation.RouteLocationEdge.ScheduleEdgeH\x00R\fscheduleEdge\x12n\n" +
	"\x10association_edge\x18\x02 \x01(\v2A.DescribeResponse.RouteLocation.RouteLocationEdge.AssociationEdgeH\x00R\x0fassociationEdge\x1aD\n" +
	"\fScheduleEdge\x124\n" +
	"\x16schedule_location_uuid\x18\x01 \x01(\tR\x14scheduleLocationUuid\x1a\xad\x03\n" +
	"\x0fAssociationEdge\x124\n" +
	"\x16schedule_location_uuid\x18\x01 \x01(\tR\x14scheduleLocationUuid\x12\x88\x01\n" +
	"\x14association_category\x18\x02 \x01(\x0e2U.DescribeResponse.RouteLocation.RouteLocationEdge.AssociationEdge.AssociationCategoryR\x13associationCategory\x12!\n" +
	"\fis_cancelled\x18\x03 \x01(\bR\visCancelled\"\xb5\x01\n" +
	"\x13AssociationCategory\x12 \n" +
	"\x1cASSOCIATION_CATEGORY_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19ASSOCIATION_CATEGORY_JOIN\x10\x01\x12\x1f\n" +
	"\x1bASSOCIATION_CATEGORY_DIVIDE\x10\x02\x12\x1d\n" +
	"\x19ASSOCIATION_CATEGORY_LINK\x10\x03\x12\x1d\n" +
	"\x19ASSOCIATION_CATEGORY_NEXT\x10\x04B\x06\n" +
	"\x04edge\x1a\xc8\f\n" +
	"\x10ScheduleLocation\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12#\n" +
	"\rschedule_uuid\x18\x02 \x01(\tR\fscheduleUuid\x12%\n" +
	"\x0eschedule_order\x18\x03 \x01(\rR\rscheduleOrder\x12\x1f\n" +
	"\vlocation_id\x18\x04 \x01(\tR\n" +
	"locationId\x12-\n" +
	"\n" +
	"activities\x18\x05 \x03(\x0e2\r.ActivityTypeR\n" +
	"activities\x12<\n" +
	"\x12planned_activities\x18\x06 \x03(\x0e2\r.ActivityTypeR\x11plannedActivities\x12&\n" +
	"\fformation_id\x18\a \x01(\tH\x00R\vformationId\x88\x01\x01\x127\n" +
	"\x18is_affected_by_diversion\x18\b \x01(\bR\x15isAffectedByDiversion\x12Q\n" +
	"\x04type\x18\t \x01(\x0e2=.DescribeResponse.RouteLocation.ScheduleLocation.LocationTypeR\x04type\x125\n" +
	"\x14working_arrival_time\x18\n" +
	" \x01(\tH\x01R\x12workingArrivalTime\x88\x01\x01\x125\n" +
	"\x14working_passing_time\x18\v \x01(\tH\x02R\x12workingPassingTime\x88\x01\x01\x129\n" +
	"\x16working_departure_time\x18\f \x01(\tH\x03R\x14workingDepartureTime\x88\x01\x01\x123\n" +
	"\x13public_arrival_time\x18\r \x01(\tH\x04R\x11publicArrivalTime\x88\x01\x01\x127\n" +
	"\x15public_departure_time\x18\x0e \x01(\tH\x05R\x13publicDepartureTime\x88\x01\x01\x12#\n" +
	"\rrouting_delay\x18\x0f \x01(\rR\froutingDelay\x12F\n" +
	"\x1dfalse_destination_location_id\x18\x10 \x01(\tH\x06R\x1afalseDestinationLocationId\x88\x01\x01\x12!\n" +
	"\fis_cancelled\x18\x11 \x01(\bR\visCancelled\x12X\n" +
	"\x1clocation_cancellation_reason\x18\x12 \x01(\v2\x11.DisruptionReasonH\aR\x1alocationCancellationReason\x88\x01\x01\x124\n" +
	"\x13timetabled_platform\x18\x13 \x01(\tH\bR\x12timetabledPlatform\x88\x01\x01\"\xef\x02\n" +
	"\fLocationType\x12\"\n" +
	"\x1eLOCATION_TYPE_LOCATION_UNKNOWN\x10\x00\x12!\n" +
	"\x1dLOCATION_TYPE_LOCATION_ORIGIN\x10\x01\x12-\n" +
	")LOCATION_TYPE_LOCATION_OPERATIONAL_ORIGIN\x10\x02\x12'\n" +
	"#LOCATION_TYPE_LOCATION_INTERMEDIATE\x10\x03\x123\n" +
	"/LOCATION_TYPE_LOCATION_OPERATIONAL_INTERMEDIATE\x10\x04\x12/\n" +
	"+LOCATION_TYPE_LOCATION_INTERMEDIATE_PASSING\x10\x05\x12&\n" +
	"\"LOCATION_TYPE_LOCATION_DESTINATION\x10\x06\x122\n" +
	".LOCATION_TYPE_LOCATION_OPERATIONAL_DESTINATION\x10\aB\x0f\n" +
	"\r_formation_idB\x17\n" +
	"\x15_working_arrival_timeB\x17\n" +
	"\x15_working_passing_timeB\x19\n" +
	"\x17_working_departure_timeB\x16\n" +
	"\x14_public_arrival_timeB\x18\n" +
	"\x16_public_departure_timeB \n" +
	"\x1e_false_destination_location_idB\x1f\n" +
	"\x1d_location_cancellation_reasonB\x16\n" +
	"\x14_timetabled_platformB\x13\n" +
	"\x11_current_platformB\x18\n" +
	"\x16_generous_arrival_timeB\x18\n" +
	"\x16_generous_passing_timeB\x1a\n" +
	"\x18_generous_departure_timeJ\x04\b\x03\x10\x05J\x04\b\x06\x10\f\"\xa9\x1e\n" +
	"\bForecast\x120\n" +
	"\x14is_reverse_formation\x18\x01 \x01(\bR\x12isReverseFormation\x12H\n" +
	"\x14schedule_late_reason\x18\x02 \x01(\v2\x11.DisruptionReasonH\x00R\x12scheduleLateReason\x88\x01\x01\x12F\n" +
	"\x1destimated_public_arrival_time\x18\x03 \x01(\tH\x01R\x1aestimatedPublicArrivalTime\x88\x01\x01\x12H\n" +
	"\x1eestimated_working_arrival_time\x18\x04 \x01(\tH\x02R\x1bestimatedWorkingArrivalTime\x88\x01\x01\x12H\n" +
	"\x1eestimated_minimum_arrival_time\x18\x05 \x01(\tH\x03R\x1bestimatedMinimumArrivalTime\x88\x01\x01\x121\n" +
	"\x12arrival_is_delayed\x18\x06 \x01(\bH\x04R\x10arrivalIsDelayed\x88\x01\x01\x12R\n" +
	"$arrival_is_delayed_by_unknown_amount\x18\a \x01(\bH\x05R\x1farrivalIsDelayedByUnknownAmount\x88\x01\x01\x129\n" +
	"\x16estimated_passing_time\x18\b \x01(\tH\x06R\x14estimatedPassingTime\x88\x01\x01\x12H\n" +
	"\x1eestimated_minimum_passing_time\x18\t \x01(\tH\aR\x1bestimatedMinimumPassingTime\x88\x01\x01\x121\n" +
	"\x12passing_is_delayed\x18\n" +
	" \x01(\bH\bR\x10passingIsDelayed\x88\x01\x01\x12R\n" +
	"$passing_is_delayed_by_unknown_amount\x18\v \x01(\bH\tR\x1fpassingIsDelayedByUnknownAmount\x88\x01\x01\x12J\n" +
	"\x1festimated_public_departure_time\x18\f \x01(\tH\n" +
	"R\x1cestimatedPublicDepartureTime\x88\x01\x01\x12L\n" +
	" estimated_working_departure_time\x18\r \x01(\tH\vR\x1destimatedWorkingDepartureTime\x88\x01\x01\x12L\n" +
	" estimated_minimum_departure_time\x18\x0e \x01(\tH\fR\x1destimatedMinimumDepartureTime\x88\x01\x01\x125\n" +
	"\x14departure_is_delayed\x18\x0f \x01(\bH\rR\x12departureIsDelayed\x88\x01\x01\x12V\n" +
	"&departure_is_delayed_by_unknown_amount\x18\x10 \x01(\bH\x0eR!departureIsDelayedByUnknownAmount\x88\x01\x01\x123\n" +
	"\x13actual_arrival_time\x18\x11 \x01(\tH\x0fR\x11actualArrivalTime\x88\x01\x01\x12>\n" +
	"\x19actual_arrival_data_class\x18\x12 \x01(\tH\x10R\x16actualArrivalDataClass\x88\x01\x01\x12@\n" +
	"\x1aactual_arrival_data_source\x18\x13 \x01(\tH\x11R\x17actualArrivalDataSource\x88\x01\x01\x12M\n" +
	"!actual_arrival_data_source_system\x18\x14 \x01(\tH\x12R\x1dactualArrivalDataSourceSystem\x88\x01\x01\x123\n" +
	"\x13actual_passing_time\x18\x15 \x01(\tH\x13R\x11actualPassingTime\x88\x01\x01\x12>\n" +
	"\x19actual_passing_data_class\x18\x16 \x01(\tH\x14R\x16actualPassingDataClass\x88\x01\x01\x12@\n" +
	"\x1aactual_passing_data_source\x18\x17 \x01(\tH\x15R\x17actualPassingDataSource\x88\x01\x01\x12M\n" +
	"!actual_passing_data_source_system\x18\x18 \x01(\tH\x16R\x1dactualPassingDataSourceSystem\x88\x01\x01\x127\n" +
	"\x15actual_departure_time\x18\x19 \x01(\tH\x17R\x13actualDepartureTime\x88\x01\x01\x12B\n" +
	"\x1bactual_departure_data_class\x18\x1a \x01(\tH\x18R\x18actualDepartureDataClass\x88\x01\x01\x12D\n" +
	"\x1cactual_departure_data_source\x18\x1b \x01(\tH\x19R\x19actualDepartureDataSource\x88\x01\x01\x12Q\n" +
	"#actual_departure_data_source_system\x18\x1c \x01(\tH\x1aR\x1factualDepartureDataSourceSystem\x88\x01\x01\x12H\n" +
	"\x14location_late_reason\x18\x1d \x01(\v2\x11.DisruptionReasonH\x1bR\x12locationLateReason\x88\x01\x01\x12=\n" +
	"\x18location_disruption_risk\x18\x1e \x01(\tH\x1cR\x16locationDisruptionRisk\x88\x01\x01\x12]\n" +
	"\x1flocation_disruption_risk_reason\x18\x1f \x01(\v2\x11.DisruptionReasonH\x1dR\x1clocationDisruptionRiskReason\x88\x01\x01\x12$\n" +
	"\vaffected_by\x18  \x01(\tH\x1eR\n" +
	"affectedBy\x88\x01\x01\x129\n" +
	"\x16platform_is_suppressed\x18! \x01(\bH\x1fR\x14platformIsSuppressed\x88\x01\x01\x12E\n" +
	"\x1dplatform_is_suppressed_by_cis\x18\" \x01(\bH R\x19platformIsSuppressedByCis\x88\x01\x01\x12S\n" +
	"\x14platform_data_source\x18# \x01(\x0e2\x1c.Forecast.PlatformDataSourceH!R\x12platformDataSource\x88\x01\x01\x127\n" +
	"\x15platform_is_confirmed\x18$ \x01(\bH\"R\x13platformIsConfirmed\x88\x01\x01\x122\n" +
	"\x15service_is_suppressed\x18% \x01(\bR\x13serviceIsSuppressed\x12?\n" +
	"\x1cservice_detatches_from_front\x18& \x01(\bR\x19serviceDetatchesFromFront\"\xc1\x01\n" +
	"\x12PlatformDataSource\x12)\n" +
	"%PLATFORM_DATA_SOURCE_PLATFORM_UNKNOWN\x10\x00\x12)\n" +
	"%PLATFORM_DATA_SOURCE_PLATFORM_PLANNED\x10\x01\x12+\n" +
	"'PLATFORM_DATA_SOURCE_PLATFORM_AUTOMATIC\x10\x02\x12(\n" +
	"$PLATFORM_DATA_SOURCE_PLATFORM_MANUAL\x10\x03B\x17\n" +
	"\x15_schedule_late_reasonB \n" +
	"\x1e_estimated_public_arrival_timeB!\n" +
	"\x1f_estimated_working_arrival_timeB!\n" +
	"\x1f_estimated_minimum_arrival_timeB\x15\n" +
	"\x13_arrival_is_delayedB'\n" +
	"%_arrival_is_delayed_by_unknown_amountB\x19\n" +
	"\x17_estimated_passing_timeB!\n" +
	"\x1f_estimated_minimum_passing_timeB\x15\n" +
	"\x13_passing_is_delayedB'\n" +
	"%_passing_is_delayed_by_unknown_amountB\"\n" +
	" _estimated_public_departure_timeB#\n" +
	"!_estimated_working_departure_timeB#\n" +
	"!_estimated_minimum_departure_timeB\x17\n" +
	"\x15_departure_is_delayedB)\n" +
	"'_departure_is_delayed_by_unknown_amountB\x16\n" +
	"\x14_actual_arrival_timeB\x1c\n" +
	"\x1a_actual_arrival_data_classB\x1d\n" +
	"\x1b_actual_arrival_data_sourceB$\n" +
	"\"_actual_arrival_data_source_systemB\x16\n" +
	"\x14_actual_passing_timeB\x1c\n" +
	"\x1a_actual_passing_data_classB\x1d\n" +
	"\x1b_actual_passing_data_sourceB$\n" +
	"\"_actual_passing_data_source_systemB\x18\n" +
	"\x16_actual_departure_timeB\x1e\n" +
	"\x1c_actual_departure_data_classB\x1f\n" +
	"\x1d_actual_departure_data_sourceB&\n" +
	"$_actual_departure_data_source_systemB\x17\n" +
	"\x15_location_late_reasonB\x1b\n" +
	"\x19_location_disruption_riskB\"\n" +
	" _location_disruption_risk_reasonB\x0e\n" +
	"\f_affected_byB\x19\n" +
	"\x17_platform_is_suppressedB \n" +
	"\x1e_platform_is_suppressed_by_cisB\x17\n" +
	"\x15_platform_data_sourceB\x18\n" +
	"\x16_platform_is_confirmedB*Z(github.com/headblockhead/railreader-grpcb\x06proto3"

var (
	file_describeResponse_proto_rawDescOnce sync.Once
	file_describeResponse_proto_rawDescData []byte
)

func file_describeResponse_proto_rawDescGZIP() []byte {
	file_describeResponse_proto_rawDescOnce.Do(func() {
		file_describeResponse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_describeResponse_proto_rawDesc), len(file_describeResponse_proto_rawDesc)))
	})
	return file_describeResponse_proto_rawDescData
}

var file_describeResponse_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_describeResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_describeResponse_proto_goTypes = []any{
	(DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_AssociationCategory)(0), // 0: DescribeResponse.RouteLocation.RouteLocationEdge.AssociationEdge.AssociationCategory
	(DescribeResponse_RouteLocation_ScheduleLocation_LocationType)(0),                         // 1: DescribeResponse.RouteLocation.ScheduleLocation.LocationType
	(Forecast_PlatformDataSource)(0),                                                          // 2: Forecast.PlatformDataSource
	(*DisruptionReason)(nil),                                                                  // 3: DisruptionReason
	(*DescribeResponse)(nil),                                                                  // 4: DescribeResponse
	(*Forecast)(nil),                                                                          // 5: Forecast
	(*DescribeResponse_Schedule)(nil),                                                         // 6: DescribeResponse.Schedule
	(*DescribeResponse_Formation)(nil),                                                        // 7: DescribeResponse.Formation
	(*DescribeResponse_RouteLocation)(nil),                                                    // 8: DescribeResponse.RouteLocation
	(*DescribeResponse_RouteLocation_RouteLocationEdge)(nil),                                  // 9: DescribeResponse.RouteLocation.RouteLocationEdge
	(*DescribeResponse_RouteLocation_ScheduleLocation)(nil),                                   // 10: DescribeResponse.RouteLocation.ScheduleLocation
	(*DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge)(nil),                     // 11: DescribeResponse.RouteLocation.RouteLocationEdge.ScheduleEdge
	(*DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge)(nil),                  // 12: DescribeResponse.RouteLocation.RouteLocationEdge.AssociationEdge
	(ServiceType)(0),  // 13: ServiceType
	(CategoryType)(0), // 14: CategoryType
	(ActivityType)(0), // 15: ActivityType
}
var file_describeResponse_proto_depIdxs = []int32{
	6,  // 0: DescribeResponse.schedules:type_name -> DescribeResponse.Schedule
	7,  // 1: DescribeResponse.formations:type_name -> DescribeResponse.Formation
	8,  // 2: DescribeResponse.route:type_name -> DescribeResponse.RouteLocation
	3,  // 3: Forecast.schedule_late_reason:type_name -> DisruptionReason
	3,  // 4: Forecast.location_late_reason:type_name -> DisruptionReason
	3,  // 5: Forecast.location_disruption_risk_reason:type_name -> DisruptionReason
	2,  // 6: Forecast.platform_data_source:type_name -> Forecast.PlatformDataSource
	13, // 7: DescribeResponse.Schedule.service:type_name -> ServiceType
	14, // 8: DescribeResponse.Schedule.category:type_name -> CategoryType
	3,  // 9: DescribeResponse.Schedule.cancellation_reason:type_name -> DisruptionReason
	3,  // 10: DescribeResponse.Schedule.diversion_reason:type_name -> DisruptionReason
	9,  // 11: DescribeResponse.RouteLocation.next_edges:type_name -> DescribeResponse.RouteLocation.RouteLocationEdge
	9,  // 12: DescribeResponse.RouteLocation.previous_edges:type_name -> DescribeResponse.RouteLocation.RouteLocationEdge
	10, // 13: DescribeResponse.RouteLocation.schedule_location:type_name -> DescribeResponse.RouteLocation.ScheduleLocation
	11, // 14: DescribeResponse.RouteLocation.RouteLocationEdge.schedule_edge:type_name -> DescribeResponse.RouteLocation.RouteLocationEdge.ScheduleEdge
	12, // 15: DescribeResponse.RouteLocation.RouteLocationEdge.association_edge:type_name -> DescribeResponse.RouteLocation.RouteLocationEdge.AssociationEdge
	15, // 16: DescribeResponse.RouteLocation.ScheduleLocation.activities:type_name -> ActivityType
	15, // 17: DescribeResponse.RouteLocation.ScheduleLocation.planned_activities:type_name -> ActivityType
	1,  // 18: DescribeResponse.RouteLocation.ScheduleLocation.type:type_name -> DescribeResponse.RouteLocation.ScheduleLocation.LocationType
	3,  // 19: DescribeResponse.RouteLocation.ScheduleLocation.location_cancellation_reason:type_name -> DisruptionReason
	0,  // 20: DescribeResponse.RouteLocation.RouteLocationEdge.AssociationEdge.association_category:type_name -> DescribeResponse.RouteLocation.RouteLocationEdge.AssociationEdge.AssociationCategory
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_describeResponse_proto_init() }
func file_describeResponse_proto_init() {
	if File_describeResponse_proto != nil {
		return
	}
	file_railtypes_proto_init()
	file_describeResponse_proto_msgTypes[0].OneofWrappers = []any{}
	file_describeResponse_proto_msgTypes[2].OneofWrappers = []any{}
	file_describeResponse_proto_msgTypes[3].OneofWrappers = []any{}
	file_describeResponse_proto_msgTypes[5].OneofWrappers = []any{}
	file_describeResponse_proto_msgTypes[6].OneofWrappers = []any{
		(*DescribeResponse_RouteLocation_RouteLocationEdge_ScheduleEdge_)(nil),
		(*DescribeResponse_RouteLocation_RouteLocationEdge_AssociationEdge_)(nil),
	}
	file_describeResponse_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_describeResponse_proto_rawDesc), len(file_describeResponse_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_describeResponse_proto_goTypes,
		DependencyIndexes: file_describeResponse_proto_depIdxs,
		EnumInfos:         file_describeResponse_proto_enumTypes,
		MessageInfos:      file_describeResponse_proto_msgTypes,
	}.Build()
	File_describeResponse_proto = out.File
	file_describeResponse_proto_goTypes = nil
	file_describeResponse_proto_depIdxs = nil
}
