// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: describeResponse.proto

package railreader_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DescribeResponse is sent n times, where n represents the number of DescribeRequests received.
type DescribeResponse struct {
	state                                  protoimpl.MessageState `protogen:"open.v1"`
	Request                                *DescribeRequest       `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`                                                                                                                   // The request being answered.
	Schedules                              []*Schedule            `protobuf:"bytes,2,rep,name=schedules,proto3" json:"schedules,omitempty"`                                                                                                               // All schedules that form the service being described. A service may have multiple schedules if a schedule joins, divides, or links with other schedules.
	Formations                             []*Formation           `protobuf:"bytes,3,rep,name=formations,proto3" json:"formations,omitempty"`                                                                                                             // All formation data (if any) that is given about the service being described. A service may have multiple formations if it loses or gains coaches during its route, or if multiple schedules that form the service have different formations.
	Route                                  []*RouteLocation       `protobuf:"bytes,4,rep,name=route,proto3" json:"route,omitempty"`                                                                                                                       // A graph of all route entries that form the service being described.
	OriginScheduleLocationComputedIds      [][]byte               `protobuf:"bytes,5,rep,name=origin_schedule_location_computed_ids,json=originScheduleLocationComputedIds,proto3" json:"origin_schedule_location_computed_ids,omitempty"`                // The schedule_location.computed_ids of the RouteLocations that the service has as origins. Multiple origins may be provided when two schedules have joined previously in the service's route.
	DestinationScheduleLocationComputedIds [][]byte               `protobuf:"bytes,6,rep,name=destination_schedule_location_computed_ids,json=destinationScheduleLocationComputedIds,proto3" json:"destination_schedule_location_computed_ids,omitempty"` // The schedule_location.computed_ids of the RouteLocations that the service has as destinations. Multiple destinations may be provided when a schedule will divide later in the service's route.
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_describeResponse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_describeResponse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_describeResponse_proto_rawDescGZIP(), []int{0}
}

func (x *DescribeResponse) GetRequest() *DescribeRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *DescribeResponse) GetSchedules() []*Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *DescribeResponse) GetFormations() []*Formation {
	if x != nil {
		return x.Formations
	}
	return nil
}

func (x *DescribeResponse) GetRoute() []*RouteLocation {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *DescribeResponse) GetOriginScheduleLocationComputedIds() [][]byte {
	if x != nil {
		return x.OriginScheduleLocationComputedIds
	}
	return nil
}

func (x *DescribeResponse) GetDestinationScheduleLocationComputedIds() [][]byte {
	if x != nil {
		return x.DestinationScheduleLocationComputedIds
	}
	return nil
}

var File_describeResponse_proto protoreflect.FileDescriptor

const file_describeResponse_proto_rawDesc = "" +
	"\n" +
	"\x16describeResponse.proto\x1a\x15describeRequest.proto\x1a\fdarwin.proto\x1a\x13routeLocation.proto\"\xe7\x02\n" +
	"\x10DescribeResponse\x12*\n" +
	"\arequest\x18\x01 \x01(\v2\x10.DescribeRequestR\arequest\x12'\n" +
	"\tschedules\x18\x02 \x03(\v2\t.ScheduleR\tschedules\x12*\n" +
	"\n" +
	"formations\x18\x03 \x03(\v2\n" +
	".FormationR\n" +
	"formations\x12$\n" +
	"\x05route\x18\x04 \x03(\v2\x0e.RouteLocationR\x05route\x12P\n" +
	"%origin_schedule_location_computed_ids\x18\x05 \x03(\fR!originScheduleLocationComputedIds\x12Z\n" +
	"*destination_schedule_location_computed_ids\x18\x06 \x03(\fR&destinationScheduleLocationComputedIdsB*Z(github.com/headblockhead/railreader-grpcb\x06proto3"

var (
	file_describeResponse_proto_rawDescOnce sync.Once
	file_describeResponse_proto_rawDescData []byte
)

func file_describeResponse_proto_rawDescGZIP() []byte {
	file_describeResponse_proto_rawDescOnce.Do(func() {
		file_describeResponse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_describeResponse_proto_rawDesc), len(file_describeResponse_proto_rawDesc)))
	})
	return file_describeResponse_proto_rawDescData
}

var file_describeResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_describeResponse_proto_goTypes = []any{
	(*DescribeResponse)(nil), // 0: DescribeResponse
	(*DescribeRequest)(nil),  // 1: DescribeRequest
	(*Schedule)(nil),         // 2: Schedule
	(*Formation)(nil),        // 3: Formation
	(*RouteLocation)(nil),    // 4: RouteLocation
}
var file_describeResponse_proto_depIdxs = []int32{
	1, // 0: DescribeResponse.request:type_name -> DescribeRequest
	2, // 1: DescribeResponse.schedules:type_name -> Schedule
	3, // 2: DescribeResponse.formations:type_name -> Formation
	4, // 3: DescribeResponse.route:type_name -> RouteLocation
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_describeResponse_proto_init() }
func file_describeResponse_proto_init() {
	if File_describeResponse_proto != nil {
		return
	}
	file_describeRequest_proto_init()
	file_darwin_proto_init()
	file_routeLocation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_describeResponse_proto_rawDesc), len(file_describeResponse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_describeResponse_proto_goTypes,
		DependencyIndexes: file_describeResponse_proto_depIdxs,
		MessageInfos:      file_describeResponse_proto_msgTypes,
	}.Build()
	File_describeResponse_proto = out.File
	file_describeResponse_proto_goTypes = nil
	file_describeResponse_proto_depIdxs = nil
}
