// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: overviewResponse.proto

package railreader_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OverviewResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Request                   *OverviewRequest       `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	CurrentSchedule           *Schedule              `protobuf:"bytes,2,opt,name=current_schedule,json=currentSchedule,proto3" json:"current_schedule,omitempty"`
	CurrentFormation          *Formation             `protobuf:"bytes,3,opt,name=current_formation,json=currentFormation,proto3,oneof" json:"current_formation,omitempty"`
	CurrentRouteLocation      *RouteLocation         `protobuf:"bytes,4,opt,name=current_route_location,json=currentRouteLocation,proto3" json:"current_route_location,omitempty"`
	OriginRouteLocations      []*RouteLocation       `protobuf:"bytes,5,rep,name=origin_route_locations,json=originRouteLocations,proto3" json:"origin_route_locations,omitempty"`
	DestinationRouteLocations []*RouteLocation       `protobuf:"bytes,6,rep,name=destination_route_locations,json=destinationRouteLocations,proto3" json:"destination_route_locations,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *OverviewResponse) Reset() {
	*x = OverviewResponse{}
	mi := &file_overviewResponse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverviewResponse) ProtoMessage() {}

func (x *OverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overviewResponse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverviewResponse.ProtoReflect.Descriptor instead.
func (*OverviewResponse) Descriptor() ([]byte, []int) {
	return file_overviewResponse_proto_rawDescGZIP(), []int{0}
}

func (x *OverviewResponse) GetRequest() *OverviewRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *OverviewResponse) GetCurrentSchedule() *Schedule {
	if x != nil {
		return x.CurrentSchedule
	}
	return nil
}

func (x *OverviewResponse) GetCurrentFormation() *Formation {
	if x != nil {
		return x.CurrentFormation
	}
	return nil
}

func (x *OverviewResponse) GetCurrentRouteLocation() *RouteLocation {
	if x != nil {
		return x.CurrentRouteLocation
	}
	return nil
}

func (x *OverviewResponse) GetOriginRouteLocations() []*RouteLocation {
	if x != nil {
		return x.OriginRouteLocations
	}
	return nil
}

func (x *OverviewResponse) GetDestinationRouteLocations() []*RouteLocation {
	if x != nil {
		return x.DestinationRouteLocations
	}
	return nil
}

var File_overviewResponse_proto protoreflect.FileDescriptor

const file_overviewResponse_proto_rawDesc = "" +
	"\n" +
	"\x16overviewResponse.proto\x1a\x15overviewRequest.proto\x1a\fdarwin.proto\x1a\x13routeLocation.proto\"\xa4\x03\n" +
	"\x10OverviewResponse\x12*\n" +
	"\arequest\x18\x01 \x01(\v2\x10.OverviewRequestR\arequest\x124\n" +
	"\x10current_schedule\x18\x02 \x01(\v2\t.ScheduleR\x0fcurrentSchedule\x12<\n" +
	"\x11current_formation\x18\x03 \x01(\v2\n" +
	".FormationH\x00R\x10currentFormation\x88\x01\x01\x12D\n" +
	"\x16current_route_location\x18\x04 \x01(\v2\x0e.RouteLocationR\x14currentRouteLocation\x12D\n" +
	"\x16origin_route_locations\x18\x05 \x03(\v2\x0e.RouteLocationR\x14originRouteLocations\x12N\n" +
	"\x1bdestination_route_locations\x18\x06 \x03(\v2\x0e.RouteLocationR\x19destinationRouteLocationsB\x14\n" +
	"\x12_current_formationB*Z(github.com/headblockhead/railreader-grpcb\x06proto3"

var (
	file_overviewResponse_proto_rawDescOnce sync.Once
	file_overviewResponse_proto_rawDescData []byte
)

func file_overviewResponse_proto_rawDescGZIP() []byte {
	file_overviewResponse_proto_rawDescOnce.Do(func() {
		file_overviewResponse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_overviewResponse_proto_rawDesc), len(file_overviewResponse_proto_rawDesc)))
	})
	return file_overviewResponse_proto_rawDescData
}

var file_overviewResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_overviewResponse_proto_goTypes = []any{
	(*OverviewResponse)(nil), // 0: OverviewResponse
	(*OverviewRequest)(nil),  // 1: OverviewRequest
	(*Schedule)(nil),         // 2: Schedule
	(*Formation)(nil),        // 3: Formation
	(*RouteLocation)(nil),    // 4: RouteLocation
}
var file_overviewResponse_proto_depIdxs = []int32{
	1, // 0: OverviewResponse.request:type_name -> OverviewRequest
	2, // 1: OverviewResponse.current_schedule:type_name -> Schedule
	3, // 2: OverviewResponse.current_formation:type_name -> Formation
	4, // 3: OverviewResponse.current_route_location:type_name -> RouteLocation
	4, // 4: OverviewResponse.origin_route_locations:type_name -> RouteLocation
	4, // 5: OverviewResponse.destination_route_locations:type_name -> RouteLocation
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_overviewResponse_proto_init() }
func file_overviewResponse_proto_init() {
	if File_overviewResponse_proto != nil {
		return
	}
	file_overviewRequest_proto_init()
	file_darwin_proto_init()
	file_routeLocation_proto_init()
	file_overviewResponse_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_overviewResponse_proto_rawDesc), len(file_overviewResponse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_overviewResponse_proto_goTypes,
		DependencyIndexes: file_overviewResponse_proto_depIdxs,
		MessageInfos:      file_overviewResponse_proto_msgTypes,
	}.Build()
	File_overviewResponse_proto = out.File
	file_overviewResponse_proto_goTypes = nil
	file_overviewResponse_proto_depIdxs = nil
}
