// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: railreader.proto

package railreader_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_railreader_proto protoreflect.FileDescriptor

const file_railreader_proto_rawDesc = "" +
	"\n" +
	"\x10railreader.proto\x1a\x1egetLatestLocationUpdates.proto\x1a\x1flistSchedulesAtLocationID.proto\x1a,describeScheduleByScheduleLocationUUID.proto\x1a\x18serviceDescription.proto2\xba\x02\n" +
	"\n" +
	"RailReader\x12[\n" +
	"\x18GetLatestLocationUpdates\x12\x1d.LatestLocationUpdatesRequest\x1a\x1e.LatestLocationUpdatesResponse\"\x00\x12Y\n" +
	"\x19ListSchedulesAtLocationID\x12!.ListSchedulesAtLocationIDRequest\x1a\x15.ScheduleLocationUUID\"\x000\x01\x12t\n" +
	"'DescribeSchedulesByScheduleLocationUUID\x12..DescribeScheduleByScheduleLocationUUIDRequest\x1a\x13.ServiceDescription\"\x00(\x010\x01B*Z(github.com/headblockhead/railreader-grpcb\x06proto3"

var file_railreader_proto_goTypes = []any{
	(*LatestLocationUpdatesRequest)(nil),                  // 0: LatestLocationUpdatesRequest
	(*ListSchedulesAtLocationIDRequest)(nil),              // 1: ListSchedulesAtLocationIDRequest
	(*DescribeScheduleByScheduleLocationUUIDRequest)(nil), // 2: DescribeScheduleByScheduleLocationUUIDRequest
	(*LatestLocationUpdatesResponse)(nil),                 // 3: LatestLocationUpdatesResponse
	(*ScheduleLocationUUID)(nil),                          // 4: ScheduleLocationUUID
	(*ServiceDescription)(nil),                            // 5: ServiceDescription
}
var file_railreader_proto_depIdxs = []int32{
	0, // 0: RailReader.GetLatestLocationUpdates:input_type -> LatestLocationUpdatesRequest
	1, // 1: RailReader.ListSchedulesAtLocationID:input_type -> ListSchedulesAtLocationIDRequest
	2, // 2: RailReader.DescribeSchedulesByScheduleLocationUUID:input_type -> DescribeScheduleByScheduleLocationUUIDRequest
	3, // 3: RailReader.GetLatestLocationUpdates:output_type -> LatestLocationUpdatesResponse
	4, // 4: RailReader.ListSchedulesAtLocationID:output_type -> ScheduleLocationUUID
	5, // 5: RailReader.DescribeSchedulesByScheduleLocationUUID:output_type -> ServiceDescription
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_railreader_proto_init() }
func file_railreader_proto_init() {
	if File_railreader_proto != nil {
		return
	}
	file_getLatestLocationUpdates_proto_init()
	file_listSchedulesAtLocationID_proto_init()
	file_describeScheduleByScheduleLocationUUID_proto_init()
	file_serviceDescription_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_railreader_proto_rawDesc), len(file_railreader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_railreader_proto_goTypes,
		DependencyIndexes: file_railreader_proto_depIdxs,
	}.Build()
	File_railreader_proto = out.File
	file_railreader_proto_goTypes = nil
	file_railreader_proto_depIdxs = nil
}
