// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: railreader.proto

package railreader_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RailReader_UpdateLocations_FullMethodName = "/RailReader/UpdateLocations"
	RailReader_Search_FullMethodName          = "/RailReader/Search"
	RailReader_Overview_FullMethodName        = "/RailReader/Overview"
	RailReader_Describe_FullMethodName        = "/RailReader/Describe"
)

// RailReaderClient is the client API for RailReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RailReaderClient interface {
	UpdateLocations(ctx context.Context, in *UpdateLocationsRequest, opts ...grpc.CallOption) (*UpdateLocationsResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	Overview(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OverviewRequest, OverviewResponse], error)
	Describe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DescribeRequest, DescribeResponse], error)
}

type railReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewRailReaderClient(cc grpc.ClientConnInterface) RailReaderClient {
	return &railReaderClient{cc}
}

func (c *railReaderClient) UpdateLocations(ctx context.Context, in *UpdateLocationsRequest, opts ...grpc.CallOption) (*UpdateLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLocationsResponse)
	err := c.cc.Invoke(ctx, RailReader_UpdateLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *railReaderClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, RailReader_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *railReaderClient) Overview(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OverviewRequest, OverviewResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RailReader_ServiceDesc.Streams[0], RailReader_Overview_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OverviewRequest, OverviewResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RailReader_OverviewClient = grpc.BidiStreamingClient[OverviewRequest, OverviewResponse]

func (c *railReaderClient) Describe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DescribeRequest, DescribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RailReader_ServiceDesc.Streams[1], RailReader_Describe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DescribeRequest, DescribeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RailReader_DescribeClient = grpc.BidiStreamingClient[DescribeRequest, DescribeResponse]

// RailReaderServer is the server API for RailReader service.
// All implementations must embed UnimplementedRailReaderServer
// for forward compatibility.
type RailReaderServer interface {
	UpdateLocations(context.Context, *UpdateLocationsRequest) (*UpdateLocationsResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	Overview(grpc.BidiStreamingServer[OverviewRequest, OverviewResponse]) error
	Describe(grpc.BidiStreamingServer[DescribeRequest, DescribeResponse]) error
	mustEmbedUnimplementedRailReaderServer()
}

// UnimplementedRailReaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRailReaderServer struct{}

func (UnimplementedRailReaderServer) UpdateLocations(context.Context, *UpdateLocationsRequest) (*UpdateLocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLocations not implemented")
}
func (UnimplementedRailReaderServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedRailReaderServer) Overview(grpc.BidiStreamingServer[OverviewRequest, OverviewResponse]) error {
	return status.Error(codes.Unimplemented, "method Overview not implemented")
}
func (UnimplementedRailReaderServer) Describe(grpc.BidiStreamingServer[DescribeRequest, DescribeResponse]) error {
	return status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedRailReaderServer) mustEmbedUnimplementedRailReaderServer() {}
func (UnimplementedRailReaderServer) testEmbeddedByValue()                    {}

// UnsafeRailReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RailReaderServer will
// result in compilation errors.
type UnsafeRailReaderServer interface {
	mustEmbedUnimplementedRailReaderServer()
}

func RegisterRailReaderServer(s grpc.ServiceRegistrar, srv RailReaderServer) {
	// If the following call panics, it indicates UnimplementedRailReaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RailReader_ServiceDesc, srv)
}

func _RailReader_UpdateLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RailReaderServer).UpdateLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RailReader_UpdateLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RailReaderServer).UpdateLocations(ctx, req.(*UpdateLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RailReader_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RailReaderServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RailReader_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RailReaderServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RailReader_Overview_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RailReaderServer).Overview(&grpc.GenericServerStream[OverviewRequest, OverviewResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RailReader_OverviewServer = grpc.BidiStreamingServer[OverviewRequest, OverviewResponse]

func _RailReader_Describe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RailReaderServer).Describe(&grpc.GenericServerStream[DescribeRequest, DescribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RailReader_DescribeServer = grpc.BidiStreamingServer[DescribeRequest, DescribeResponse]

// RailReader_ServiceDesc is the grpc.ServiceDesc for RailReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RailReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RailReader",
	HandlerType: (*RailReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateLocations",
			Handler:    _RailReader_UpdateLocations_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _RailReader_Search_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Overview",
			Handler:       _RailReader_Overview_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Describe",
			Handler:       _RailReader_Describe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "railreader.proto",
}
