// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: railtypes.proto

package railreader_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceType int32

const (
	ServiceType_SERVICE_TYPE_SERVICE_UNKNOWN                  ServiceType = 0
	ServiceType_SERVICE_TYPE_SERVICE_TRAIN                    ServiceType = 1
	ServiceType_SERVICE_TYPE_SERVICE_SHORT_TERM_PLANNED_TRAIN ServiceType = 2
	ServiceType_SERVICE_TYPE_SERVICE_BUS                      ServiceType = 3
	ServiceType_SERVICE_TYPE_SERVICE_SHORT_TERM_PLANNED_BUS   ServiceType = 4
	ServiceType_SERVICE_TYPE_SERVICE_SHIP                     ServiceType = 5
	ServiceType_SERVICE_TYPE_SERVICE_SHORT_TERM_PLANNED_SHIP  ServiceType = 6 // Trip and Freight types ommitted as they are not tracked by Darwin
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "SERVICE_TYPE_SERVICE_UNKNOWN",
		1: "SERVICE_TYPE_SERVICE_TRAIN",
		2: "SERVICE_TYPE_SERVICE_SHORT_TERM_PLANNED_TRAIN",
		3: "SERVICE_TYPE_SERVICE_BUS",
		4: "SERVICE_TYPE_SERVICE_SHORT_TERM_PLANNED_BUS",
		5: "SERVICE_TYPE_SERVICE_SHIP",
		6: "SERVICE_TYPE_SERVICE_SHORT_TERM_PLANNED_SHIP",
	}
	ServiceType_value = map[string]int32{
		"SERVICE_TYPE_SERVICE_UNKNOWN":                  0,
		"SERVICE_TYPE_SERVICE_TRAIN":                    1,
		"SERVICE_TYPE_SERVICE_SHORT_TERM_PLANNED_TRAIN": 2,
		"SERVICE_TYPE_SERVICE_BUS":                      3,
		"SERVICE_TYPE_SERVICE_SHORT_TERM_PLANNED_BUS":   4,
		"SERVICE_TYPE_SERVICE_SHIP":                     5,
		"SERVICE_TYPE_SERVICE_SHORT_TERM_PLANNED_SHIP":  6,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_railtypes_proto_enumTypes[0].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_railtypes_proto_enumTypes[0]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_railtypes_proto_rawDescGZIP(), []int{0}
}

type CategoryType int32

const (
	CategoryType_CATEGORY_TYPE_CATEGORY_UNKNOWN                                   CategoryType = 0
	CategoryType_CATEGORY_TYPE_CATEGORY_UNDERGROUND_OR_METRO                      CategoryType = 1
	CategoryType_CATEGORY_TYPE_CATEGORY_UNADVERTISED_PASSENGER                    CategoryType = 2
	CategoryType_CATEGORY_TYPE_CATEGORY_PASSENGER                                 CategoryType = 3
	CategoryType_CATEGORY_TYPE_CATEGORY_STAFF                                     CategoryType = 4
	CategoryType_CATEGORY_TYPE_CATEGORY_MIXED                                     CategoryType = 5
	CategoryType_CATEGORY_TYPE_CATEGORY_CHANNEL_TUNNEL                            CategoryType = 6
	CategoryType_CATEGORY_TYPE_CATEGORY_SLEEPER                                   CategoryType = 7
	CategoryType_CATEGORY_TYPE_CATEGORY_INTERNATIONAL                             CategoryType = 8
	CategoryType_CATEGORY_TYPE_CATEGORY_MOTORAIL                                  CategoryType = 9
	CategoryType_CATEGORY_TYPE_CATEGORY_UNADVERTISED_EXPRESS                      CategoryType = 10
	CategoryType_CATEGORY_TYPE_CATEGORY_EXPRESS                                   CategoryType = 11
	CategoryType_CATEGORY_TYPE_CATEGORY_SLEEPER_DOMESTIC                          CategoryType = 12
	CategoryType_CATEGORY_TYPE_CATEGORY_BUS_REPLACEMENT                           CategoryType = 13
	CategoryType_CATEGORY_TYPE_CATEGORY_BUS_SERVICE                               CategoryType = 14
	CategoryType_CATEGORY_TYPE_CATEGORY_SHIP                                      CategoryType = 15
	CategoryType_CATEGORY_TYPE_CATEGORY_EMPTY_COACHING_STOCK                      CategoryType = 16
	CategoryType_CATEGORY_TYPE_CATEGORY_EMPTY_COACHING_STOCK_UNDERGROUND_OR_METRO CategoryType = 17
	CategoryType_CATEGORY_TYPE_CATEGORY_EMPTY_COACHING_STOCK_OR_STAFF             CategoryType = 18
)

// Enum value maps for CategoryType.
var (
	CategoryType_name = map[int32]string{
		0:  "CATEGORY_TYPE_CATEGORY_UNKNOWN",
		1:  "CATEGORY_TYPE_CATEGORY_UNDERGROUND_OR_METRO",
		2:  "CATEGORY_TYPE_CATEGORY_UNADVERTISED_PASSENGER",
		3:  "CATEGORY_TYPE_CATEGORY_PASSENGER",
		4:  "CATEGORY_TYPE_CATEGORY_STAFF",
		5:  "CATEGORY_TYPE_CATEGORY_MIXED",
		6:  "CATEGORY_TYPE_CATEGORY_CHANNEL_TUNNEL",
		7:  "CATEGORY_TYPE_CATEGORY_SLEEPER",
		8:  "CATEGORY_TYPE_CATEGORY_INTERNATIONAL",
		9:  "CATEGORY_TYPE_CATEGORY_MOTORAIL",
		10: "CATEGORY_TYPE_CATEGORY_UNADVERTISED_EXPRESS",
		11: "CATEGORY_TYPE_CATEGORY_EXPRESS",
		12: "CATEGORY_TYPE_CATEGORY_SLEEPER_DOMESTIC",
		13: "CATEGORY_TYPE_CATEGORY_BUS_REPLACEMENT",
		14: "CATEGORY_TYPE_CATEGORY_BUS_SERVICE",
		15: "CATEGORY_TYPE_CATEGORY_SHIP",
		16: "CATEGORY_TYPE_CATEGORY_EMPTY_COACHING_STOCK",
		17: "CATEGORY_TYPE_CATEGORY_EMPTY_COACHING_STOCK_UNDERGROUND_OR_METRO",
		18: "CATEGORY_TYPE_CATEGORY_EMPTY_COACHING_STOCK_OR_STAFF",
	}
	CategoryType_value = map[string]int32{
		"CATEGORY_TYPE_CATEGORY_UNKNOWN":                                   0,
		"CATEGORY_TYPE_CATEGORY_UNDERGROUND_OR_METRO":                      1,
		"CATEGORY_TYPE_CATEGORY_UNADVERTISED_PASSENGER":                    2,
		"CATEGORY_TYPE_CATEGORY_PASSENGER":                                 3,
		"CATEGORY_TYPE_CATEGORY_STAFF":                                     4,
		"CATEGORY_TYPE_CATEGORY_MIXED":                                     5,
		"CATEGORY_TYPE_CATEGORY_CHANNEL_TUNNEL":                            6,
		"CATEGORY_TYPE_CATEGORY_SLEEPER":                                   7,
		"CATEGORY_TYPE_CATEGORY_INTERNATIONAL":                             8,
		"CATEGORY_TYPE_CATEGORY_MOTORAIL":                                  9,
		"CATEGORY_TYPE_CATEGORY_UNADVERTISED_EXPRESS":                      10,
		"CATEGORY_TYPE_CATEGORY_EXPRESS":                                   11,
		"CATEGORY_TYPE_CATEGORY_SLEEPER_DOMESTIC":                          12,
		"CATEGORY_TYPE_CATEGORY_BUS_REPLACEMENT":                           13,
		"CATEGORY_TYPE_CATEGORY_BUS_SERVICE":                               14,
		"CATEGORY_TYPE_CATEGORY_SHIP":                                      15,
		"CATEGORY_TYPE_CATEGORY_EMPTY_COACHING_STOCK":                      16,
		"CATEGORY_TYPE_CATEGORY_EMPTY_COACHING_STOCK_UNDERGROUND_OR_METRO": 17,
		"CATEGORY_TYPE_CATEGORY_EMPTY_COACHING_STOCK_OR_STAFF":             18,
	}
)

func (x CategoryType) Enum() *CategoryType {
	p := new(CategoryType)
	*p = x
	return p
}

func (x CategoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CategoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_railtypes_proto_enumTypes[1].Descriptor()
}

func (CategoryType) Type() protoreflect.EnumType {
	return &file_railtypes_proto_enumTypes[1]
}

func (x CategoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CategoryType.Descriptor instead.
func (CategoryType) EnumDescriptor() ([]byte, []int) {
	return file_railtypes_proto_rawDescGZIP(), []int{1}
}

type ActivityType int32

const (
	ActivityType_ACTIVITY_TYPE_ACTIVITY_UNKNOWN                                                     ActivityType = 0
	ActivityType_ACTIVITY_TYPE_ACTIVITY_TRAIN_BEGINS                                                ActivityType = 1
	ActivityType_ACTIVITY_TYPE_ACTIVITY_TRAIN_FINISHES                                              ActivityType = 2
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_TO_TAKE_UP_AND_SET_DOWN_PASSENGERS                    ActivityType = 3
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_TO_TAKE_UP_PASSENGERS                                 ActivityType = 4
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_TO_SET_DOWN_PASSENGERS                                ActivityType = 5
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_OR_SHUNTS_FOR_OTHER_TRAINS_TO_PASS                    ActivityType = 6
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_OR_DETACH_ASSISTING_LOCOMOTIVE              ActivityType = 7
	ActivityType_ACTIVITY_TYPE_ACTIVITY_SHOWS_AS_X_ON_ARRIVAL                                       ActivityType = 8
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_BANKING_LOCOMOTIVE                                ActivityType = 9
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_TO_CHANGE_TRAIN_CREW                                  ActivityType = 10
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_TO_DETATCH_VEHICLES                                   ActivityType = 11
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_EXAMINATION                                       ActivityType = 12
	ActivityType_ACTIVITY_TYPE_ACTIVITY_NATIONAL_RAIL_TIMETABLE_DATA_TO_ADD                         ActivityType = 13
	ActivityType_ACTIVITY_TYPE_ACTIVITY_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE       ActivityType = 14
	ActivityType_ACTIVITY_TYPE_ACTIVITY_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE_TWICE ActivityType = 15
	ActivityType_ACTIVITY_TYPE_ACTIVITY_PASSENGER_COUNT_POINT                                       ActivityType = 16
	ActivityType_ACTIVITY_TYPE_ACTIVITY_TICKET_COLLECTION_AND_EXAMINATION_POINT                     ActivityType = 17
	ActivityType_ACTIVITY_TYPE_ACTIVITY_TICKET_EXAMINATION_POINT                                    ActivityType = 18
	ActivityType_ACTIVITY_TYPE_ACTIVITY_TICKET_EXAMINATION_POINT_FIRST_CLASS_ONLY                   ActivityType = 19
	ActivityType_ACTIVITY_TYPE_ACTIVITY_TICKET_EXAMINATION_POINT_SELECTIVE                          ActivityType = 20
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_TO_CHANGE_LOCOMOTIVES                                 ActivityType = 21
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOP_NOT_ADVERTISED                                         ActivityType = 22
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_OTHER_OPERATING_REASONS                           ActivityType = 23
	ActivityType_ACTIVITY_TYPE_ACTIVITY_TRAIN_LOCOMOTIVE_ON_REAR                                    ActivityType = 24
	ActivityType_ACTIVITY_TYPE_ACTIVITY_PROPELLING_BETWEEN_POINTS_SHOWN                             ActivityType = 25
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_WHEN_REQUIRED                                         ActivityType = 26
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_REVERSING_MOVEMENT_OR_DRIVER_END_CHANGE           ActivityType = 27
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_LOCOMOTIVE_TO_RUN_ROUND                           ActivityType = 28
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_RAILWAY_PERSONELL_ONLY                            ActivityType = 29
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_AND_DETACH_VEHICLES                         ActivityType = 30
	ActivityType_ACTIVITY_TYPE_ACTIVITY_DETAIL_CONSIST_FOR_TOPS_DIRECT                              ActivityType = 31
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_OR_PASSES_FOR_TABLET_STAFF_OR_TOKEN                   ActivityType = 32
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_VEHICLES                                    ActivityType = 33
	ActivityType_ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_WATERING_OF_COACHES                               ActivityType = 34
	ActivityType_ACTIVITY_TYPE_ACTIVITY_PASSES_ANOTHER_TRAIN_AT_CROSSING_POINT_ON_SINGLE_LINE       ActivityType = 35
)

// Enum value maps for ActivityType.
var (
	ActivityType_name = map[int32]string{
		0:  "ACTIVITY_TYPE_ACTIVITY_UNKNOWN",
		1:  "ACTIVITY_TYPE_ACTIVITY_TRAIN_BEGINS",
		2:  "ACTIVITY_TYPE_ACTIVITY_TRAIN_FINISHES",
		3:  "ACTIVITY_TYPE_ACTIVITY_STOPS_TO_TAKE_UP_AND_SET_DOWN_PASSENGERS",
		4:  "ACTIVITY_TYPE_ACTIVITY_STOPS_TO_TAKE_UP_PASSENGERS",
		5:  "ACTIVITY_TYPE_ACTIVITY_STOPS_TO_SET_DOWN_PASSENGERS",
		6:  "ACTIVITY_TYPE_ACTIVITY_STOPS_OR_SHUNTS_FOR_OTHER_TRAINS_TO_PASS",
		7:  "ACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_OR_DETACH_ASSISTING_LOCOMOTIVE",
		8:  "ACTIVITY_TYPE_ACTIVITY_SHOWS_AS_X_ON_ARRIVAL",
		9:  "ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_BANKING_LOCOMOTIVE",
		10: "ACTIVITY_TYPE_ACTIVITY_STOPS_TO_CHANGE_TRAIN_CREW",
		11: "ACTIVITY_TYPE_ACTIVITY_STOPS_TO_DETATCH_VEHICLES",
		12: "ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_EXAMINATION",
		13: "ACTIVITY_TYPE_ACTIVITY_NATIONAL_RAIL_TIMETABLE_DATA_TO_ADD",
		14: "ACTIVITY_TYPE_ACTIVITY_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE",
		15: "ACTIVITY_TYPE_ACTIVITY_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE_TWICE",
		16: "ACTIVITY_TYPE_ACTIVITY_PASSENGER_COUNT_POINT",
		17: "ACTIVITY_TYPE_ACTIVITY_TICKET_COLLECTION_AND_EXAMINATION_POINT",
		18: "ACTIVITY_TYPE_ACTIVITY_TICKET_EXAMINATION_POINT",
		19: "ACTIVITY_TYPE_ACTIVITY_TICKET_EXAMINATION_POINT_FIRST_CLASS_ONLY",
		20: "ACTIVITY_TYPE_ACTIVITY_TICKET_EXAMINATION_POINT_SELECTIVE",
		21: "ACTIVITY_TYPE_ACTIVITY_STOPS_TO_CHANGE_LOCOMOTIVES",
		22: "ACTIVITY_TYPE_ACTIVITY_STOP_NOT_ADVERTISED",
		23: "ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_OTHER_OPERATING_REASONS",
		24: "ACTIVITY_TYPE_ACTIVITY_TRAIN_LOCOMOTIVE_ON_REAR",
		25: "ACTIVITY_TYPE_ACTIVITY_PROPELLING_BETWEEN_POINTS_SHOWN",
		26: "ACTIVITY_TYPE_ACTIVITY_STOPS_WHEN_REQUIRED",
		27: "ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_REVERSING_MOVEMENT_OR_DRIVER_END_CHANGE",
		28: "ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_LOCOMOTIVE_TO_RUN_ROUND",
		29: "ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_RAILWAY_PERSONELL_ONLY",
		30: "ACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_AND_DETACH_VEHICLES",
		31: "ACTIVITY_TYPE_ACTIVITY_DETAIL_CONSIST_FOR_TOPS_DIRECT",
		32: "ACTIVITY_TYPE_ACTIVITY_STOPS_OR_PASSES_FOR_TABLET_STAFF_OR_TOKEN",
		33: "ACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_VEHICLES",
		34: "ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_WATERING_OF_COACHES",
		35: "ACTIVITY_TYPE_ACTIVITY_PASSES_ANOTHER_TRAIN_AT_CROSSING_POINT_ON_SINGLE_LINE",
	}
	ActivityType_value = map[string]int32{
		"ACTIVITY_TYPE_ACTIVITY_UNKNOWN":                                                     0,
		"ACTIVITY_TYPE_ACTIVITY_TRAIN_BEGINS":                                                1,
		"ACTIVITY_TYPE_ACTIVITY_TRAIN_FINISHES":                                              2,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_TO_TAKE_UP_AND_SET_DOWN_PASSENGERS":                    3,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_TO_TAKE_UP_PASSENGERS":                                 4,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_TO_SET_DOWN_PASSENGERS":                                5,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_OR_SHUNTS_FOR_OTHER_TRAINS_TO_PASS":                    6,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_OR_DETACH_ASSISTING_LOCOMOTIVE":              7,
		"ACTIVITY_TYPE_ACTIVITY_SHOWS_AS_X_ON_ARRIVAL":                                       8,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_BANKING_LOCOMOTIVE":                                9,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_TO_CHANGE_TRAIN_CREW":                                  10,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_TO_DETATCH_VEHICLES":                                   11,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_EXAMINATION":                                       12,
		"ACTIVITY_TYPE_ACTIVITY_NATIONAL_RAIL_TIMETABLE_DATA_TO_ADD":                         13,
		"ACTIVITY_TYPE_ACTIVITY_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE":       14,
		"ACTIVITY_TYPE_ACTIVITY_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE_TWICE": 15,
		"ACTIVITY_TYPE_ACTIVITY_PASSENGER_COUNT_POINT":                                       16,
		"ACTIVITY_TYPE_ACTIVITY_TICKET_COLLECTION_AND_EXAMINATION_POINT":                     17,
		"ACTIVITY_TYPE_ACTIVITY_TICKET_EXAMINATION_POINT":                                    18,
		"ACTIVITY_TYPE_ACTIVITY_TICKET_EXAMINATION_POINT_FIRST_CLASS_ONLY":                   19,
		"ACTIVITY_TYPE_ACTIVITY_TICKET_EXAMINATION_POINT_SELECTIVE":                          20,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_TO_CHANGE_LOCOMOTIVES":                                 21,
		"ACTIVITY_TYPE_ACTIVITY_STOP_NOT_ADVERTISED":                                         22,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_OTHER_OPERATING_REASONS":                           23,
		"ACTIVITY_TYPE_ACTIVITY_TRAIN_LOCOMOTIVE_ON_REAR":                                    24,
		"ACTIVITY_TYPE_ACTIVITY_PROPELLING_BETWEEN_POINTS_SHOWN":                             25,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_WHEN_REQUIRED":                                         26,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_REVERSING_MOVEMENT_OR_DRIVER_END_CHANGE":           27,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_LOCOMOTIVE_TO_RUN_ROUND":                           28,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_RAILWAY_PERSONELL_ONLY":                            29,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_AND_DETACH_VEHICLES":                         30,
		"ACTIVITY_TYPE_ACTIVITY_DETAIL_CONSIST_FOR_TOPS_DIRECT":                              31,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_OR_PASSES_FOR_TABLET_STAFF_OR_TOKEN":                   32,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_VEHICLES":                                    33,
		"ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_WATERING_OF_COACHES":                               34,
		"ACTIVITY_TYPE_ACTIVITY_PASSES_ANOTHER_TRAIN_AT_CROSSING_POINT_ON_SINGLE_LINE":       35,
	}
)

func (x ActivityType) Enum() *ActivityType {
	p := new(ActivityType)
	*p = x
	return p
}

func (x ActivityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityType) Descriptor() protoreflect.EnumDescriptor {
	return file_railtypes_proto_enumTypes[2].Descriptor()
}

func (ActivityType) Type() protoreflect.EnumType {
	return &file_railtypes_proto_enumTypes[2]
}

func (x ActivityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityType.Descriptor instead.
func (ActivityType) EnumDescriptor() ([]byte, []int) {
	return file_railtypes_proto_rawDescGZIP(), []int{2}
}

var File_railtypes_proto protoreflect.FileDescriptor

const file_railtypes_proto_rawDesc = "" +
	"\n" +
	"\x0frailtypes.proto*\xa2\x02\n" +
	"\vServiceType\x12 \n" +
	"\x1cSERVICE_TYPE_SERVICE_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aSERVICE_TYPE_SERVICE_TRAIN\x10\x01\x121\n" +
	"-SERVICE_TYPE_SERVICE_SHORT_TERM_PLANNED_TRAIN\x10\x02\x12\x1c\n" +
	"\x18SERVICE_TYPE_SERVICE_BUS\x10\x03\x12/\n" +
	"+SERVICE_TYPE_SERVICE_SHORT_TERM_PLANNED_BUS\x10\x04\x12\x1d\n" +
	"\x19SERVICE_TYPE_SERVICE_SHIP\x10\x05\x120\n" +
	",SERVICE_TYPE_SERVICE_SHORT_TERM_PLANNED_SHIP\x10\x06*\xc6\x06\n" +
	"\fCategoryType\x12\"\n" +
	"\x1eCATEGORY_TYPE_CATEGORY_UNKNOWN\x10\x00\x12/\n" +
	"+CATEGORY_TYPE_CATEGORY_UNDERGROUND_OR_METRO\x10\x01\x121\n" +
	"-CATEGORY_TYPE_CATEGORY_UNADVERTISED_PASSENGER\x10\x02\x12$\n" +
	" CATEGORY_TYPE_CATEGORY_PASSENGER\x10\x03\x12 \n" +
	"\x1cCATEGORY_TYPE_CATEGORY_STAFF\x10\x04\x12 \n" +
	"\x1cCATEGORY_TYPE_CATEGORY_MIXED\x10\x05\x12)\n" +
	"%CATEGORY_TYPE_CATEGORY_CHANNEL_TUNNEL\x10\x06\x12\"\n" +
	"\x1eCATEGORY_TYPE_CATEGORY_SLEEPER\x10\a\x12(\n" +
	"$CATEGORY_TYPE_CATEGORY_INTERNATIONAL\x10\b\x12#\n" +
	"\x1fCATEGORY_TYPE_CATEGORY_MOTORAIL\x10\t\x12/\n" +
	"+CATEGORY_TYPE_CATEGORY_UNADVERTISED_EXPRESS\x10\n" +
	"\x12\"\n" +
	"\x1eCATEGORY_TYPE_CATEGORY_EXPRESS\x10\v\x12+\n" +
	"'CATEGORY_TYPE_CATEGORY_SLEEPER_DOMESTIC\x10\f\x12*\n" +
	"&CATEGORY_TYPE_CATEGORY_BUS_REPLACEMENT\x10\r\x12&\n" +
	"\"CATEGORY_TYPE_CATEGORY_BUS_SERVICE\x10\x0e\x12\x1f\n" +
	"\x1bCATEGORY_TYPE_CATEGORY_SHIP\x10\x0f\x12/\n" +
	"+CATEGORY_TYPE_CATEGORY_EMPTY_COACHING_STOCK\x10\x10\x12D\n" +
	"@CATEGORY_TYPE_CATEGORY_EMPTY_COACHING_STOCK_UNDERGROUND_OR_METRO\x10\x11\x128\n" +
	"4CATEGORY_TYPE_CATEGORY_EMPTY_COACHING_STOCK_OR_STAFF\x10\x12*\x82\x11\n" +
	"\fActivityType\x12\"\n" +
	"\x1eACTIVITY_TYPE_ACTIVITY_UNKNOWN\x10\x00\x12'\n" +
	"#ACTIVITY_TYPE_ACTIVITY_TRAIN_BEGINS\x10\x01\x12)\n" +
	"%ACTIVITY_TYPE_ACTIVITY_TRAIN_FINISHES\x10\x02\x12C\n" +
	"?ACTIVITY_TYPE_ACTIVITY_STOPS_TO_TAKE_UP_AND_SET_DOWN_PASSENGERS\x10\x03\x126\n" +
	"2ACTIVITY_TYPE_ACTIVITY_STOPS_TO_TAKE_UP_PASSENGERS\x10\x04\x127\n" +
	"3ACTIVITY_TYPE_ACTIVITY_STOPS_TO_SET_DOWN_PASSENGERS\x10\x05\x12C\n" +
	"?ACTIVITY_TYPE_ACTIVITY_STOPS_OR_SHUNTS_FOR_OTHER_TRAINS_TO_PASS\x10\x06\x12I\n" +
	"EACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_OR_DETACH_ASSISTING_LOCOMOTIVE\x10\a\x120\n" +
	",ACTIVITY_TYPE_ACTIVITY_SHOWS_AS_X_ON_ARRIVAL\x10\b\x127\n" +
	"3ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_BANKING_LOCOMOTIVE\x10\t\x125\n" +
	"1ACTIVITY_TYPE_ACTIVITY_STOPS_TO_CHANGE_TRAIN_CREW\x10\n" +
	"\x124\n" +
	"0ACTIVITY_TYPE_ACTIVITY_STOPS_TO_DETATCH_VEHICLES\x10\v\x120\n" +
	",ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_EXAMINATION\x10\f\x12>\n" +
	":ACTIVITY_TYPE_ACTIVITY_NATIONAL_RAIL_TIMETABLE_DATA_TO_ADD\x10\r\x12P\n" +
	"LACTIVITY_TYPE_ACTIVITY_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE\x10\x0e\x12V\n" +
	"RACTIVITY_TYPE_ACTIVITY_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE_TWICE\x10\x0f\x120\n" +
	",ACTIVITY_TYPE_ACTIVITY_PASSENGER_COUNT_POINT\x10\x10\x12B\n" +
	">ACTIVITY_TYPE_ACTIVITY_TICKET_COLLECTION_AND_EXAMINATION_POINT\x10\x11\x123\n" +
	"/ACTIVITY_TYPE_ACTIVITY_TICKET_EXAMINATION_POINT\x10\x12\x12D\n" +
	"@ACTIVITY_TYPE_ACTIVITY_TICKET_EXAMINATION_POINT_FIRST_CLASS_ONLY\x10\x13\x12=\n" +
	"9ACTIVITY_TYPE_ACTIVITY_TICKET_EXAMINATION_POINT_SELECTIVE\x10\x14\x126\n" +
	"2ACTIVITY_TYPE_ACTIVITY_STOPS_TO_CHANGE_LOCOMOTIVES\x10\x15\x12.\n" +
	"*ACTIVITY_TYPE_ACTIVITY_STOP_NOT_ADVERTISED\x10\x16\x12<\n" +
	"8ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_OTHER_OPERATING_REASONS\x10\x17\x123\n" +
	"/ACTIVITY_TYPE_ACTIVITY_TRAIN_LOCOMOTIVE_ON_REAR\x10\x18\x12:\n" +
	"6ACTIVITY_TYPE_ACTIVITY_PROPELLING_BETWEEN_POINTS_SHOWN\x10\x19\x12.\n" +
	"*ACTIVITY_TYPE_ACTIVITY_STOPS_WHEN_REQUIRED\x10\x1a\x12L\n" +
	"HACTIVITY_TYPE_ACTIVITY_STOPS_FOR_REVERSING_MOVEMENT_OR_DRIVER_END_CHANGE\x10\x1b\x12<\n" +
	"8ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_LOCOMOTIVE_TO_RUN_ROUND\x10\x1c\x12;\n" +
	"7ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_RAILWAY_PERSONELL_ONLY\x10\x1d\x12>\n" +
	":ACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_AND_DETACH_VEHICLES\x10\x1e\x129\n" +
	"5ACTIVITY_TYPE_ACTIVITY_DETAIL_CONSIST_FOR_TOPS_DIRECT\x10\x1f\x12D\n" +
	"@ACTIVITY_TYPE_ACTIVITY_STOPS_OR_PASSES_FOR_TABLET_STAFF_OR_TOKEN\x10 \x123\n" +
	"/ACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_VEHICLES\x10!\x128\n" +
	"4ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_WATERING_OF_COACHES\x10\"\x12P\n" +
	"LACTIVITY_TYPE_ACTIVITY_PASSES_ANOTHER_TRAIN_AT_CROSSING_POINT_ON_SINGLE_LINE\x10#B*Z(github.com/headblockhead/railreader-grpcb\x06proto3"

var (
	file_railtypes_proto_rawDescOnce sync.Once
	file_railtypes_proto_rawDescData []byte
)

func file_railtypes_proto_rawDescGZIP() []byte {
	file_railtypes_proto_rawDescOnce.Do(func() {
		file_railtypes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_railtypes_proto_rawDesc), len(file_railtypes_proto_rawDesc)))
	})
	return file_railtypes_proto_rawDescData
}

var file_railtypes_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_railtypes_proto_goTypes = []any{
	(ServiceType)(0),  // 0: ServiceType
	(CategoryType)(0), // 1: CategoryType
	(ActivityType)(0), // 2: ActivityType
}
var file_railtypes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_railtypes_proto_init() }
func file_railtypes_proto_init() {
	if File_railtypes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_railtypes_proto_rawDesc), len(file_railtypes_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_railtypes_proto_goTypes,
		DependencyIndexes: file_railtypes_proto_depIdxs,
		EnumInfos:         file_railtypes_proto_enumTypes,
	}.Build()
	File_railtypes_proto = out.File
	file_railtypes_proto_goTypes = nil
	file_railtypes_proto_depIdxs = nil
}
