// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: railreader.proto

package railreader_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RailReader_GetLatestLocationUpdates_FullMethodName               = "/RailReader/GetLatestLocationUpdates"
	RailReader_Search_FullMethodName                                 = "/RailReader/Search"
	RailReader_DescribeServicesByScheduleLocationUUID_FullMethodName = "/RailReader/DescribeServicesByScheduleLocationUUID"
)

// RailReaderClient is the client API for RailReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RailReaderClient interface {
	GetLatestLocationUpdates(ctx context.Context, in *LatestLocationUpdatesRequest, opts ...grpc.CallOption) (*LatestLocationUpdatesResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	DescribeServicesByScheduleLocationUUID(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DescribeServiceByScheduleLocationUUIDRequest, ServiceDescription], error)
}

type railReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewRailReaderClient(cc grpc.ClientConnInterface) RailReaderClient {
	return &railReaderClient{cc}
}

func (c *railReaderClient) GetLatestLocationUpdates(ctx context.Context, in *LatestLocationUpdatesRequest, opts ...grpc.CallOption) (*LatestLocationUpdatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LatestLocationUpdatesResponse)
	err := c.cc.Invoke(ctx, RailReader_GetLatestLocationUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *railReaderClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, RailReader_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *railReaderClient) DescribeServicesByScheduleLocationUUID(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DescribeServiceByScheduleLocationUUIDRequest, ServiceDescription], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RailReader_ServiceDesc.Streams[0], RailReader_DescribeServicesByScheduleLocationUUID_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DescribeServiceByScheduleLocationUUIDRequest, ServiceDescription]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RailReader_DescribeServicesByScheduleLocationUUIDClient = grpc.BidiStreamingClient[DescribeServiceByScheduleLocationUUIDRequest, ServiceDescription]

// RailReaderServer is the server API for RailReader service.
// All implementations must embed UnimplementedRailReaderServer
// for forward compatibility.
type RailReaderServer interface {
	GetLatestLocationUpdates(context.Context, *LatestLocationUpdatesRequest) (*LatestLocationUpdatesResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	DescribeServicesByScheduleLocationUUID(grpc.BidiStreamingServer[DescribeServiceByScheduleLocationUUIDRequest, ServiceDescription]) error
	mustEmbedUnimplementedRailReaderServer()
}

// UnimplementedRailReaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRailReaderServer struct{}

func (UnimplementedRailReaderServer) GetLatestLocationUpdates(context.Context, *LatestLocationUpdatesRequest) (*LatestLocationUpdatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestLocationUpdates not implemented")
}
func (UnimplementedRailReaderServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedRailReaderServer) DescribeServicesByScheduleLocationUUID(grpc.BidiStreamingServer[DescribeServiceByScheduleLocationUUIDRequest, ServiceDescription]) error {
	return status.Error(codes.Unimplemented, "method DescribeServicesByScheduleLocationUUID not implemented")
}
func (UnimplementedRailReaderServer) mustEmbedUnimplementedRailReaderServer() {}
func (UnimplementedRailReaderServer) testEmbeddedByValue()                    {}

// UnsafeRailReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RailReaderServer will
// result in compilation errors.
type UnsafeRailReaderServer interface {
	mustEmbedUnimplementedRailReaderServer()
}

func RegisterRailReaderServer(s grpc.ServiceRegistrar, srv RailReaderServer) {
	// If the following call panics, it indicates UnimplementedRailReaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RailReader_ServiceDesc, srv)
}

func _RailReader_GetLatestLocationUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatestLocationUpdatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RailReaderServer).GetLatestLocationUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RailReader_GetLatestLocationUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RailReaderServer).GetLatestLocationUpdates(ctx, req.(*LatestLocationUpdatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RailReader_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RailReaderServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RailReader_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RailReaderServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RailReader_DescribeServicesByScheduleLocationUUID_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RailReaderServer).DescribeServicesByScheduleLocationUUID(&grpc.GenericServerStream[DescribeServiceByScheduleLocationUUIDRequest, ServiceDescription]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RailReader_DescribeServicesByScheduleLocationUUIDServer = grpc.BidiStreamingServer[DescribeServiceByScheduleLocationUUIDRequest, ServiceDescription]

// RailReader_ServiceDesc is the grpc.ServiceDesc for RailReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RailReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RailReader",
	HandlerType: (*RailReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestLocationUpdates",
			Handler:    _RailReader_GetLatestLocationUpdates_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _RailReader_Search_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DescribeServicesByScheduleLocationUUID",
			Handler:       _RailReader_DescribeServicesByScheduleLocationUUID_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "railreader.proto",
}
