// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: railreader.proto

package railreader_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_railreader_proto protoreflect.FileDescriptor

const file_railreader_proto_rawDesc = "" +
	"\n" +
	"\x10railreader.proto\x1a\x15updateLocations.proto\x1a\fsearch.proto2\x83\x01\n" +
	"\n" +
	"RailReader\x12F\n" +
	"\x0fUpdateLocations\x12\x17.UpdateLocationsRequest\x1a\x18.UpdateLocationsResponse\"\x00\x12-\n" +
	"\x06Search\x12\x0e.SearchRequest\x1a\x0f.SearchResponse\"\x000\x01B*Z(github.com/headblockhead/railreader-grpcb\x06proto3"

var file_railreader_proto_goTypes = []any{
	(*UpdateLocationsRequest)(nil),  // 0: UpdateLocationsRequest
	(*SearchRequest)(nil),           // 1: SearchRequest
	(*UpdateLocationsResponse)(nil), // 2: UpdateLocationsResponse
	(*SearchResponse)(nil),          // 3: SearchResponse
}
var file_railreader_proto_depIdxs = []int32{
	0, // 0: RailReader.UpdateLocations:input_type -> UpdateLocationsRequest
	1, // 1: RailReader.Search:input_type -> SearchRequest
	2, // 2: RailReader.UpdateLocations:output_type -> UpdateLocationsResponse
	3, // 3: RailReader.Search:output_type -> SearchResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_railreader_proto_init() }
func file_railreader_proto_init() {
	if File_railreader_proto != nil {
		return
	}
	file_updateLocations_proto_init()
	file_search_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_railreader_proto_rawDesc), len(file_railreader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_railreader_proto_goTypes,
		DependencyIndexes: file_railreader_proto_depIdxs,
	}.Build()
	File_railreader_proto = out.File
	file_railreader_proto_goTypes = nil
	file_railreader_proto_depIdxs = nil
}
