// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: routeLocation.proto

package railreader_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteLocation struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	NextEdges             []*RouteLocation_Edge  `protobuf:"bytes,1,rep,name=next_edges,json=nextEdges,proto3" json:"next_edges,omitempty"`
	PreviousEdges         []*RouteLocation_Edge  `protobuf:"bytes,2,rep,name=previous_edges,json=previousEdges,proto3" json:"previous_edges,omitempty"`
	ViaText               *string                `protobuf:"bytes,3,opt,name=via_text,json=viaText,proto3,oneof" json:"via_text,omitempty"`
	ForecastLocation      *ForecastLocation      `protobuf:"bytes,4,opt,name=forecast_location,json=forecastLocation,proto3,oneof" json:"forecast_location,omitempty"`
	FormationLoading      *FormationLoading      `protobuf:"bytes,5,opt,name=formation_loading,json=formationLoading,proto3,oneof" json:"formation_loading,omitempty"`
	ScheduleLocation      *ScheduleLocation      `protobuf:"bytes,6,opt,name=schedule_location,json=scheduleLocation,proto3" json:"schedule_location,omitempty"`
	ServiceLoading        *ServiceLoading        `protobuf:"bytes,7,opt,name=service_loading,json=serviceLoading,proto3,oneof" json:"service_loading,omitempty"`
	GenerousArrivalTime   *string                `protobuf:"bytes,13,opt,name=generous_arrival_time,json=generousArrivalTime,proto3,oneof" json:"generous_arrival_time,omitempty"`
	GenerousPassingTime   *string                `protobuf:"bytes,14,opt,name=generous_passing_time,json=generousPassingTime,proto3,oneof" json:"generous_passing_time,omitempty"`
	GenerousDepartureTime *string                `protobuf:"bytes,15,opt,name=generous_departure_time,json=generousDepartureTime,proto3,oneof" json:"generous_departure_time,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RouteLocation) Reset() {
	*x = RouteLocation{}
	mi := &file_routeLocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteLocation) ProtoMessage() {}

func (x *RouteLocation) ProtoReflect() protoreflect.Message {
	mi := &file_routeLocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteLocation.ProtoReflect.Descriptor instead.
func (*RouteLocation) Descriptor() ([]byte, []int) {
	return file_routeLocation_proto_rawDescGZIP(), []int{0}
}

func (x *RouteLocation) GetNextEdges() []*RouteLocation_Edge {
	if x != nil {
		return x.NextEdges
	}
	return nil
}

func (x *RouteLocation) GetPreviousEdges() []*RouteLocation_Edge {
	if x != nil {
		return x.PreviousEdges
	}
	return nil
}

func (x *RouteLocation) GetViaText() string {
	if x != nil && x.ViaText != nil {
		return *x.ViaText
	}
	return ""
}

func (x *RouteLocation) GetForecastLocation() *ForecastLocation {
	if x != nil {
		return x.ForecastLocation
	}
	return nil
}

func (x *RouteLocation) GetFormationLoading() *FormationLoading {
	if x != nil {
		return x.FormationLoading
	}
	return nil
}

func (x *RouteLocation) GetScheduleLocation() *ScheduleLocation {
	if x != nil {
		return x.ScheduleLocation
	}
	return nil
}

func (x *RouteLocation) GetServiceLoading() *ServiceLoading {
	if x != nil {
		return x.ServiceLoading
	}
	return nil
}

func (x *RouteLocation) GetGenerousArrivalTime() string {
	if x != nil && x.GenerousArrivalTime != nil {
		return *x.GenerousArrivalTime
	}
	return ""
}

func (x *RouteLocation) GetGenerousPassingTime() string {
	if x != nil && x.GenerousPassingTime != nil {
		return *x.GenerousPassingTime
	}
	return ""
}

func (x *RouteLocation) GetGenerousDepartureTime() string {
	if x != nil && x.GenerousDepartureTime != nil {
		return *x.GenerousDepartureTime
	}
	return ""
}

type RouteLocation_Edge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Edge:
	//
	//	*RouteLocation_Edge_Schedule_
	//	*RouteLocation_Edge_Association_
	Edge          isRouteLocation_Edge_Edge `protobuf_oneof:"edge"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteLocation_Edge) Reset() {
	*x = RouteLocation_Edge{}
	mi := &file_routeLocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteLocation_Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteLocation_Edge) ProtoMessage() {}

func (x *RouteLocation_Edge) ProtoReflect() protoreflect.Message {
	mi := &file_routeLocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteLocation_Edge.ProtoReflect.Descriptor instead.
func (*RouteLocation_Edge) Descriptor() ([]byte, []int) {
	return file_routeLocation_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RouteLocation_Edge) GetEdge() isRouteLocation_Edge_Edge {
	if x != nil {
		return x.Edge
	}
	return nil
}

func (x *RouteLocation_Edge) GetSchedule() *RouteLocation_Edge_Schedule {
	if x != nil {
		if x, ok := x.Edge.(*RouteLocation_Edge_Schedule_); ok {
			return x.Schedule
		}
	}
	return nil
}

func (x *RouteLocation_Edge) GetAssociation() *RouteLocation_Edge_Association {
	if x != nil {
		if x, ok := x.Edge.(*RouteLocation_Edge_Association_); ok {
			return x.Association
		}
	}
	return nil
}

type isRouteLocation_Edge_Edge interface {
	isRouteLocation_Edge_Edge()
}

type RouteLocation_Edge_Schedule_ struct {
	Schedule *RouteLocation_Edge_Schedule `protobuf:"bytes,1,opt,name=schedule,proto3,oneof"`
}

type RouteLocation_Edge_Association_ struct {
	Association *RouteLocation_Edge_Association `protobuf:"bytes,2,opt,name=association,proto3,oneof"`
}

func (*RouteLocation_Edge_Schedule_) isRouteLocation_Edge_Edge() {}

func (*RouteLocation_Edge_Association_) isRouteLocation_Edge_Edge() {}

type RouteLocation_Edge_Schedule struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ScheduleLocationComputedId []byte                 `protobuf:"bytes,1,opt,name=schedule_location_computed_id,json=scheduleLocationComputedId,proto3" json:"schedule_location_computed_id,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RouteLocation_Edge_Schedule) Reset() {
	*x = RouteLocation_Edge_Schedule{}
	mi := &file_routeLocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteLocation_Edge_Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteLocation_Edge_Schedule) ProtoMessage() {}

func (x *RouteLocation_Edge_Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_routeLocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteLocation_Edge_Schedule.ProtoReflect.Descriptor instead.
func (*RouteLocation_Edge_Schedule) Descriptor() ([]byte, []int) {
	return file_routeLocation_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *RouteLocation_Edge_Schedule) GetScheduleLocationComputedId() []byte {
	if x != nil {
		return x.ScheduleLocationComputedId
	}
	return nil
}

type RouteLocation_Edge_Association struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ScheduleLocationComputedId []byte                 `protobuf:"bytes,1,opt,name=schedule_location_computed_id,json=scheduleLocationComputedId,proto3" json:"schedule_location_computed_id,omitempty"`
	AssociationCategory        AssociationCategory    `protobuf:"varint,2,opt,name=association_category,json=associationCategory,proto3,enum=AssociationCategory" json:"association_category,omitempty"`
	IsCancelled                bool                   `protobuf:"varint,3,opt,name=is_cancelled,json=isCancelled,proto3" json:"is_cancelled,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RouteLocation_Edge_Association) Reset() {
	*x = RouteLocation_Edge_Association{}
	mi := &file_routeLocation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteLocation_Edge_Association) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteLocation_Edge_Association) ProtoMessage() {}

func (x *RouteLocation_Edge_Association) ProtoReflect() protoreflect.Message {
	mi := &file_routeLocation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteLocation_Edge_Association.ProtoReflect.Descriptor instead.
func (*RouteLocation_Edge_Association) Descriptor() ([]byte, []int) {
	return file_routeLocation_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *RouteLocation_Edge_Association) GetScheduleLocationComputedId() []byte {
	if x != nil {
		return x.ScheduleLocationComputedId
	}
	return nil
}

func (x *RouteLocation_Edge_Association) GetAssociationCategory() AssociationCategory {
	if x != nil {
		return x.AssociationCategory
	}
	return AssociationCategory_ASSOCIATION_CATEGORY_UNKNOWN
}

func (x *RouteLocation_Edge_Association) GetIsCancelled() bool {
	if x != nil {
		return x.IsCancelled
	}
	return false
}

var File_routeLocation_proto protoreflect.FileDescriptor

const file_routeLocation_proto_rawDesc = "" +
	"\n" +
	"\x13routeLocation.proto\x1a\x0frailtypes.proto\x1a\fdarwin.proto\"\x9a\t\n" +
	"\rRouteLocation\x122\n" +
	"\n" +
	"next_edges\x18\x01 \x03(\v2\x13.RouteLocation.EdgeR\tnextEdges\x12:\n" +
	"\x0eprevious_edges\x18\x02 \x03(\v2\x13.RouteLocation.EdgeR\rpreviousEdges\x12\x1e\n" +
	"\bvia_text\x18\x03 \x01(\tH\x00R\aviaText\x88\x01\x01\x12C\n" +
	"\x11forecast_location\x18\x04 \x01(\v2\x11.ForecastLocationH\x01R\x10forecastLocation\x88\x01\x01\x12C\n" +
	"\x11formation_loading\x18\x05 \x01(\v2\x11.FormationLoadingH\x02R\x10formationLoading\x88\x01\x01\x12>\n" +
	"\x11schedule_location\x18\x06 \x01(\v2\x11.ScheduleLocationR\x10scheduleLocation\x12=\n" +
	"\x0fservice_loading\x18\a \x01(\v2\x0f.ServiceLoadingH\x03R\x0eserviceLoading\x88\x01\x01\x127\n" +
	"\x15generous_arrival_time\x18\r \x01(\tH\x04R\x13generousArrivalTime\x88\x01\x01\x127\n" +
	"\x15generous_passing_time\x18\x0e \x01(\tH\x05R\x13generousPassingTime\x88\x01\x01\x12;\n" +
	"\x17generous_departure_time\x18\x0f \x01(\tH\x06R\x15generousDepartureTime\x88\x01\x01\x1a\x9d\x03\n" +
	"\x04Edge\x12:\n" +
	"\bschedule\x18\x01 \x01(\v2\x1c.RouteLocation.Edge.ScheduleH\x00R\bschedule\x12C\n" +
	"\vassociation\x18\x02 \x01(\v2\x1f.RouteLocation.Edge.AssociationH\x00R\vassociation\x1aM\n" +
	"\bSchedule\x12A\n" +
	"\x1dschedule_location_computed_id\x18\x01 \x01(\fR\x1ascheduleLocationComputedId\x1a\xbc\x01\n" +
	"\vAssociation\x12A\n" +
	"\x1dschedule_location_computed_id\x18\x01 \x01(\fR\x1ascheduleLocationComputedId\x12G\n" +
	"\x14association_category\x18\x02 \x01(\x0e2\x14.AssociationCategoryR\x13associationCategory\x12!\n" +
	"\fis_cancelled\x18\x03 \x01(\bR\visCancelledB\x06\n" +
	"\x04edgeB\v\n" +
	"\t_via_textB\x14\n" +
	"\x12_forecast_locationB\x14\n" +
	"\x12_formation_loadingB\x12\n" +
	"\x10_service_loadingB\x18\n" +
	"\x16_generous_arrival_timeB\x18\n" +
	"\x16_generous_passing_timeB\x1a\n" +
	"\x18_generous_departure_timeJ\x04\b\b\x10\rB*Z(github.com/headblockhead/railreader-grpcb\x06proto3"

var (
	file_routeLocation_proto_rawDescOnce sync.Once
	file_routeLocation_proto_rawDescData []byte
)

func file_routeLocation_proto_rawDescGZIP() []byte {
	file_routeLocation_proto_rawDescOnce.Do(func() {
		file_routeLocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeLocation_proto_rawDesc), len(file_routeLocation_proto_rawDesc)))
	})
	return file_routeLocation_proto_rawDescData
}

var file_routeLocation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_routeLocation_proto_goTypes = []any{
	(*RouteLocation)(nil),                  // 0: RouteLocation
	(*RouteLocation_Edge)(nil),             // 1: RouteLocation.Edge
	(*RouteLocation_Edge_Schedule)(nil),    // 2: RouteLocation.Edge.Schedule
	(*RouteLocation_Edge_Association)(nil), // 3: RouteLocation.Edge.Association
	(*ForecastLocation)(nil),               // 4: ForecastLocation
	(*FormationLoading)(nil),               // 5: FormationLoading
	(*ScheduleLocation)(nil),               // 6: ScheduleLocation
	(*ServiceLoading)(nil),                 // 7: ServiceLoading
	(AssociationCategory)(0),               // 8: AssociationCategory
}
var file_routeLocation_proto_depIdxs = []int32{
	1, // 0: RouteLocation.next_edges:type_name -> RouteLocation.Edge
	1, // 1: RouteLocation.previous_edges:type_name -> RouteLocation.Edge
	4, // 2: RouteLocation.forecast_location:type_name -> ForecastLocation
	5, // 3: RouteLocation.formation_loading:type_name -> FormationLoading
	6, // 4: RouteLocation.schedule_location:type_name -> ScheduleLocation
	7, // 5: RouteLocation.service_loading:type_name -> ServiceLoading
	2, // 6: RouteLocation.Edge.schedule:type_name -> RouteLocation.Edge.Schedule
	3, // 7: RouteLocation.Edge.association:type_name -> RouteLocation.Edge.Association
	8, // 8: RouteLocation.Edge.Association.association_category:type_name -> AssociationCategory
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_routeLocation_proto_init() }
func file_routeLocation_proto_init() {
	if File_routeLocation_proto != nil {
		return
	}
	file_railtypes_proto_init()
	file_darwin_proto_init()
	file_routeLocation_proto_msgTypes[0].OneofWrappers = []any{}
	file_routeLocation_proto_msgTypes[1].OneofWrappers = []any{
		(*RouteLocation_Edge_Schedule_)(nil),
		(*RouteLocation_Edge_Association_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeLocation_proto_rawDesc), len(file_routeLocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_routeLocation_proto_goTypes,
		DependencyIndexes: file_routeLocation_proto_depIdxs,
		MessageInfos:      file_routeLocation_proto_msgTypes,
	}.Build()
	File_routeLocation_proto = out.File
	file_routeLocation_proto_goTypes = nil
	file_routeLocation_proto_depIdxs = nil
}
