// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: schedulesAtLocation.proto

package railreader_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchedulesAtLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    string                 `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"` // TIPLOC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulesAtLocationRequest) Reset() {
	*x = SchedulesAtLocationRequest{}
	mi := &file_schedulesAtLocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulesAtLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulesAtLocationRequest) ProtoMessage() {}

func (x *SchedulesAtLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedulesAtLocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulesAtLocationRequest.ProtoReflect.Descriptor instead.
func (*SchedulesAtLocationRequest) Descriptor() ([]byte, []int) {
	return file_schedulesAtLocation_proto_rawDescGZIP(), []int{0}
}

func (x *SchedulesAtLocationRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

// This contains some minimal information about a schedule at the location requested.
// Designed to use very little bandwidth.
// More (useful) data can be requested using the IDs provided.
type SchedulesAtLocationResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ScheduleUuid         string                 `protobuf:"bytes,1,opt,name=schedule_uuid,json=scheduleUuid,proto3" json:"schedule_uuid,omitempty"`
	ScheduleId           string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	ScheduleLocationUuid string                 `protobuf:"bytes,3,opt,name=schedule_location_uuid,json=scheduleLocationUuid,proto3" json:"schedule_location_uuid,omitempty"`
	ScheduledStartDate   string                 `protobuf:"bytes,4,opt,name=scheduled_start_date,json=scheduledStartDate,proto3" json:"scheduled_start_date,omitempty"` // in YYYY-MM-DD format
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SchedulesAtLocationResponse) Reset() {
	*x = SchedulesAtLocationResponse{}
	mi := &file_schedulesAtLocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulesAtLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulesAtLocationResponse) ProtoMessage() {}

func (x *SchedulesAtLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schedulesAtLocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulesAtLocationResponse.ProtoReflect.Descriptor instead.
func (*SchedulesAtLocationResponse) Descriptor() ([]byte, []int) {
	return file_schedulesAtLocation_proto_rawDescGZIP(), []int{1}
}

func (x *SchedulesAtLocationResponse) GetScheduleUuid() string {
	if x != nil {
		return x.ScheduleUuid
	}
	return ""
}

func (x *SchedulesAtLocationResponse) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *SchedulesAtLocationResponse) GetScheduleLocationUuid() string {
	if x != nil {
		return x.ScheduleLocationUuid
	}
	return ""
}

func (x *SchedulesAtLocationResponse) GetScheduledStartDate() string {
	if x != nil {
		return x.ScheduledStartDate
	}
	return ""
}

var File_schedulesAtLocation_proto protoreflect.FileDescriptor

const file_schedulesAtLocation_proto_rawDesc = "" +
	"\n" +
	"\x19schedulesAtLocation.proto\"=\n" +
	"\x1aSchedulesAtLocationRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\"\xcb\x01\n" +
	"\x1bSchedulesAtLocationResponse\x12#\n" +
	"\rschedule_uuid\x18\x01 \x01(\tR\fscheduleUuid\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x124\n" +
	"\x16schedule_location_uuid\x18\x03 \x01(\tR\x14scheduleLocationUuid\x120\n" +
	"\x14scheduled_start_date\x18\x04 \x01(\tR\x12scheduledStartDateB*Z(github.com/headblockhead/railreader-grpcb\x06proto3"

var (
	file_schedulesAtLocation_proto_rawDescOnce sync.Once
	file_schedulesAtLocation_proto_rawDescData []byte
)

func file_schedulesAtLocation_proto_rawDescGZIP() []byte {
	file_schedulesAtLocation_proto_rawDescOnce.Do(func() {
		file_schedulesAtLocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schedulesAtLocation_proto_rawDesc), len(file_schedulesAtLocation_proto_rawDesc)))
	})
	return file_schedulesAtLocation_proto_rawDescData
}

var file_schedulesAtLocation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schedulesAtLocation_proto_goTypes = []any{
	(*SchedulesAtLocationRequest)(nil),  // 0: SchedulesAtLocationRequest
	(*SchedulesAtLocationResponse)(nil), // 1: SchedulesAtLocationResponse
}
var file_schedulesAtLocation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schedulesAtLocation_proto_init() }
func file_schedulesAtLocation_proto_init() {
	if File_schedulesAtLocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schedulesAtLocation_proto_rawDesc), len(file_schedulesAtLocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schedulesAtLocation_proto_goTypes,
		DependencyIndexes: file_schedulesAtLocation_proto_depIdxs,
		MessageInfos:      file_schedulesAtLocation_proto_msgTypes,
	}.Build()
	File_schedulesAtLocation_proto = out.File
	file_schedulesAtLocation_proto_goTypes = nil
	file_schedulesAtLocation_proto_depIdxs = nil
}
