// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: searchResponse.proto

package railreader_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchResponse struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ScheduleLocationComputedIds []string               `protobuf:"bytes,1,rep,name=schedule_location_computed_ids,json=scheduleLocationComputedIds,proto3" json:"schedule_location_computed_ids,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_searchResponse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_searchResponse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_searchResponse_proto_rawDescGZIP(), []int{0}
}

func (x *SearchResponse) GetScheduleLocationComputedIds() []string {
	if x != nil {
		return x.ScheduleLocationComputedIds
	}
	return nil
}

var File_searchResponse_proto protoreflect.FileDescriptor

const file_searchResponse_proto_rawDesc = "" +
	"\n" +
	"\x14searchResponse.proto\"U\n" +
	"\x0eSearchResponse\x12C\n" +
	"\x1eschedule_location_computed_ids\x18\x01 \x03(\tR\x1bscheduleLocationComputedIdsB*Z(github.com/headblockhead/railreader-grpcb\x06proto3"

var (
	file_searchResponse_proto_rawDescOnce sync.Once
	file_searchResponse_proto_rawDescData []byte
)

func file_searchResponse_proto_rawDescGZIP() []byte {
	file_searchResponse_proto_rawDescOnce.Do(func() {
		file_searchResponse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_searchResponse_proto_rawDesc), len(file_searchResponse_proto_rawDesc)))
	})
	return file_searchResponse_proto_rawDescData
}

var file_searchResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_searchResponse_proto_goTypes = []any{
	(*SearchResponse)(nil), // 0: SearchResponse
}
var file_searchResponse_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_searchResponse_proto_init() }
func file_searchResponse_proto_init() {
	if File_searchResponse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_searchResponse_proto_rawDesc), len(file_searchResponse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_searchResponse_proto_goTypes,
		DependencyIndexes: file_searchResponse_proto_depIdxs,
		MessageInfos:      file_searchResponse_proto_msgTypes,
	}.Build()
	File_searchResponse_proto = out.File
	file_searchResponse_proto_goTypes = nil
	file_searchResponse_proto_depIdxs = nil
}
