// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: search.proto

package railreader_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchType int32

const (
	SearchType_SEARCH_TYPE_RETURN_NONE                                SearchType = 0
	SearchType_SEARCH_TYPE_RETURN_DEPARTURES                          SearchType = 1
	SearchType_SEARCH_TYPE_RETURN_PASSING                             SearchType = 2
	SearchType_SEARCH_TYPE_RETURN_PASSING_AND_DEPARTURES              SearchType = 3
	SearchType_SEARCH_TYPE_RETURN_ARRIVALS                            SearchType = 4
	SearchType_SEARCH_TYPE_RETURN_ARRIVALS_AND_DEPARTURES             SearchType = 5
	SearchType_SEARCH_TYPE_RETURN_ARRIVALS_AND_PASSING                SearchType = 6
	SearchType_SEARCH_TYPE_RETURN_ARRIVALS_AND_PASSING_AND_DEPARTURES SearchType = 7
)

// Enum value maps for SearchType.
var (
	SearchType_name = map[int32]string{
		0: "SEARCH_TYPE_RETURN_NONE",
		1: "SEARCH_TYPE_RETURN_DEPARTURES",
		2: "SEARCH_TYPE_RETURN_PASSING",
		3: "SEARCH_TYPE_RETURN_PASSING_AND_DEPARTURES",
		4: "SEARCH_TYPE_RETURN_ARRIVALS",
		5: "SEARCH_TYPE_RETURN_ARRIVALS_AND_DEPARTURES",
		6: "SEARCH_TYPE_RETURN_ARRIVALS_AND_PASSING",
		7: "SEARCH_TYPE_RETURN_ARRIVALS_AND_PASSING_AND_DEPARTURES",
	}
	SearchType_value = map[string]int32{
		"SEARCH_TYPE_RETURN_NONE":                                0,
		"SEARCH_TYPE_RETURN_DEPARTURES":                          1,
		"SEARCH_TYPE_RETURN_PASSING":                             2,
		"SEARCH_TYPE_RETURN_PASSING_AND_DEPARTURES":              3,
		"SEARCH_TYPE_RETURN_ARRIVALS":                            4,
		"SEARCH_TYPE_RETURN_ARRIVALS_AND_DEPARTURES":             5,
		"SEARCH_TYPE_RETURN_ARRIVALS_AND_PASSING":                6,
		"SEARCH_TYPE_RETURN_ARRIVALS_AND_PASSING_AND_DEPARTURES": 7,
	}
)

func (x SearchType) Enum() *SearchType {
	p := new(SearchType)
	*p = x
	return p
}

func (x SearchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchType) Descriptor() protoreflect.EnumDescriptor {
	return file_search_proto_enumTypes[0].Descriptor()
}

func (SearchType) Type() protoreflect.EnumType {
	return &file_search_proto_enumTypes[0]
}

func (x SearchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchType.Descriptor instead.
func (SearchType) EnumDescriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

type ServiceType int32

const (
	ServiceType_SERVICE_TYPE_UNKNOWN                  ServiceType = 0
	ServiceType_SERVICE_TYPE_TRAIN                    ServiceType = 1
	ServiceType_SERVICE_TYPE_SHORT_TERM_PLANNED_TRAIN ServiceType = 2
	ServiceType_SERVICE_TYPE_BUS                      ServiceType = 3
	ServiceType_SERVICE_TYPE_SHORT_TERM_PLANNED_BUS   ServiceType = 4
	ServiceType_SERVICE_TYPE_SHIP                     ServiceType = 5
	ServiceType_SERVICE_TYPE_SHORT_TERM_PLANNED_SHIP  ServiceType = 6 // Trip and Freight types ommitted as they are not tracked by Darwin
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "SERVICE_TYPE_UNKNOWN",
		1: "SERVICE_TYPE_TRAIN",
		2: "SERVICE_TYPE_SHORT_TERM_PLANNED_TRAIN",
		3: "SERVICE_TYPE_BUS",
		4: "SERVICE_TYPE_SHORT_TERM_PLANNED_BUS",
		5: "SERVICE_TYPE_SHIP",
		6: "SERVICE_TYPE_SHORT_TERM_PLANNED_SHIP",
	}
	ServiceType_value = map[string]int32{
		"SERVICE_TYPE_UNKNOWN":                  0,
		"SERVICE_TYPE_TRAIN":                    1,
		"SERVICE_TYPE_SHORT_TERM_PLANNED_TRAIN": 2,
		"SERVICE_TYPE_BUS":                      3,
		"SERVICE_TYPE_SHORT_TERM_PLANNED_BUS":   4,
		"SERVICE_TYPE_SHIP":                     5,
		"SERVICE_TYPE_SHORT_TERM_PLANNED_SHIP":  6,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_search_proto_enumTypes[1].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_search_proto_enumTypes[1]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{1}
}

type CategoryType int32

const (
	CategoryType_CATEGORY_TYPE_UNKNOWN                                   CategoryType = 0
	CategoryType_CATEGORY_TYPE_UNDERGROUND_OR_METRO                      CategoryType = 1
	CategoryType_CATEGORY_TYPE_UNADVERTISED_PASSENGER                    CategoryType = 2
	CategoryType_CATEGORY_TYPE_PASSENGER                                 CategoryType = 3
	CategoryType_CATEGORY_TYPE_STAFF                                     CategoryType = 4
	CategoryType_CATEGORY_TYPE_MIXED                                     CategoryType = 5
	CategoryType_CATEGORY_TYPE_CHANNEL_TUNNEL                            CategoryType = 6
	CategoryType_CATEGORY_TYPE_SLEEPER                                   CategoryType = 7
	CategoryType_CATEGORY_TYPE_INTERNATIONAL                             CategoryType = 8
	CategoryType_CATEGORY_TYPE_MOTORAIL                                  CategoryType = 9
	CategoryType_CATEGORY_TYPE_UNADVERTISED_EXPRESS                      CategoryType = 10
	CategoryType_CATEGORY_TYPE_EXPRESS                                   CategoryType = 11
	CategoryType_CATEGORY_TYPE_SLEEPER_DOMESTIC                          CategoryType = 12
	CategoryType_CATEGORY_TYPE_BUS_REPLACEMENT                           CategoryType = 13
	CategoryType_CATEGORY_TYPE_BUS_SERVICE                               CategoryType = 14
	CategoryType_CATEGORY_TYPE_SHIP                                      CategoryType = 15
	CategoryType_CATEGORY_TYPE_EMPTY_COACHING_STOCK                      CategoryType = 16
	CategoryType_CATEGORY_TYPE_EMPTY_COACHING_STOCK_UNDERGROUND_OR_METRO CategoryType = 17
	CategoryType_CATEGORY_TYPE_EMPTY_COACHING_STOCK_OR_STAFF             CategoryType = 18
)

// Enum value maps for CategoryType.
var (
	CategoryType_name = map[int32]string{
		0:  "CATEGORY_TYPE_UNKNOWN",
		1:  "CATEGORY_TYPE_UNDERGROUND_OR_METRO",
		2:  "CATEGORY_TYPE_UNADVERTISED_PASSENGER",
		3:  "CATEGORY_TYPE_PASSENGER",
		4:  "CATEGORY_TYPE_STAFF",
		5:  "CATEGORY_TYPE_MIXED",
		6:  "CATEGORY_TYPE_CHANNEL_TUNNEL",
		7:  "CATEGORY_TYPE_SLEEPER",
		8:  "CATEGORY_TYPE_INTERNATIONAL",
		9:  "CATEGORY_TYPE_MOTORAIL",
		10: "CATEGORY_TYPE_UNADVERTISED_EXPRESS",
		11: "CATEGORY_TYPE_EXPRESS",
		12: "CATEGORY_TYPE_SLEEPER_DOMESTIC",
		13: "CATEGORY_TYPE_BUS_REPLACEMENT",
		14: "CATEGORY_TYPE_BUS_SERVICE",
		15: "CATEGORY_TYPE_SHIP",
		16: "CATEGORY_TYPE_EMPTY_COACHING_STOCK",
		17: "CATEGORY_TYPE_EMPTY_COACHING_STOCK_UNDERGROUND_OR_METRO",
		18: "CATEGORY_TYPE_EMPTY_COACHING_STOCK_OR_STAFF",
	}
	CategoryType_value = map[string]int32{
		"CATEGORY_TYPE_UNKNOWN":                                   0,
		"CATEGORY_TYPE_UNDERGROUND_OR_METRO":                      1,
		"CATEGORY_TYPE_UNADVERTISED_PASSENGER":                    2,
		"CATEGORY_TYPE_PASSENGER":                                 3,
		"CATEGORY_TYPE_STAFF":                                     4,
		"CATEGORY_TYPE_MIXED":                                     5,
		"CATEGORY_TYPE_CHANNEL_TUNNEL":                            6,
		"CATEGORY_TYPE_SLEEPER":                                   7,
		"CATEGORY_TYPE_INTERNATIONAL":                             8,
		"CATEGORY_TYPE_MOTORAIL":                                  9,
		"CATEGORY_TYPE_UNADVERTISED_EXPRESS":                      10,
		"CATEGORY_TYPE_EXPRESS":                                   11,
		"CATEGORY_TYPE_SLEEPER_DOMESTIC":                          12,
		"CATEGORY_TYPE_BUS_REPLACEMENT":                           13,
		"CATEGORY_TYPE_BUS_SERVICE":                               14,
		"CATEGORY_TYPE_SHIP":                                      15,
		"CATEGORY_TYPE_EMPTY_COACHING_STOCK":                      16,
		"CATEGORY_TYPE_EMPTY_COACHING_STOCK_UNDERGROUND_OR_METRO": 17,
		"CATEGORY_TYPE_EMPTY_COACHING_STOCK_OR_STAFF":             18,
	}
)

func (x CategoryType) Enum() *CategoryType {
	p := new(CategoryType)
	*p = x
	return p
}

func (x CategoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CategoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_search_proto_enumTypes[2].Descriptor()
}

func (CategoryType) Type() protoreflect.EnumType {
	return &file_search_proto_enumTypes[2]
}

func (x CategoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CategoryType.Descriptor instead.
func (CategoryType) EnumDescriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{2}
}

type ActivityType int32

const (
	ActivityType_ACTIVITY_TYPE_UNKNOWN                                                     ActivityType = 0
	ActivityType_ACTIVITY_TYPE_TRAIN_BEGINS                                                ActivityType = 1
	ActivityType_ACTIVITY_TYPE_TRAIN_FINISHES                                              ActivityType = 2
	ActivityType_ACTIVITY_TYPE_STOPS_TO_TAKE_UP_AND_SET_DOWN_PASSENGERS                    ActivityType = 3
	ActivityType_ACTIVITY_TYPE_STOPS_TO_TAKE_UP_PASSENGERS                                 ActivityType = 4
	ActivityType_ACTIVITY_TYPE_STOPS_TO_SET_DOWN_PASSENGERS                                ActivityType = 5
	ActivityType_ACTIVITY_TYPE_STOPS_OR_SHUNTS_FOR_OTHER_TRAINS_TO_PASS                    ActivityType = 6
	ActivityType_ACTIVITY_TYPE_STOPS_TO_ATTACH_OR_DETACH_ASSISTING_LOCOMOTIVE              ActivityType = 7
	ActivityType_ACTIVITY_TYPE_SHOWS_AS_X_ON_ARRIVAL                                       ActivityType = 8
	ActivityType_ACTIVITY_TYPE_STOPS_FOR_BANKING_LOCOMOTIVE                                ActivityType = 9
	ActivityType_ACTIVITY_TYPE_STOPS_TO_CHANGE_TRAIN_CREW                                  ActivityType = 10
	ActivityType_ACTIVITY_TYPE_STOPS_TO_DETATCH_VEHICLES                                   ActivityType = 11
	ActivityType_ACTIVITY_TYPE_STOPS_FOR_EXAMINATION                                       ActivityType = 12
	ActivityType_ACTIVITY_TYPE_NATIONAL_RAIL_TIMETABLE_DATA_TO_ADD                         ActivityType = 13
	ActivityType_ACTIVITY_TYPE_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE       ActivityType = 14
	ActivityType_ACTIVITY_TYPE_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE_TWICE ActivityType = 15
	ActivityType_ACTIVITY_TYPE_PASSENGER_COUNT_POINT                                       ActivityType = 16
	ActivityType_ACTIVITY_TYPE_TICKET_COLLECTION_AND_EXAMINATION_POINT                     ActivityType = 17
	ActivityType_ACTIVITY_TYPE_TICKET_EXAMINATION_POINT                                    ActivityType = 18
	ActivityType_ACTIVITY_TYPE_TICKET_EXAMINATION_POINT_FIRST_CLASS_ONLY                   ActivityType = 19
	ActivityType_ACTIVITY_TYPE_TICKET_EXAMINATION_POINT_SELECTIVE                          ActivityType = 20
	ActivityType_ACTIVITY_TYPE_STOPS_TO_CHANGE_LOCOMOTIVES                                 ActivityType = 21
	ActivityType_ACTIVITY_TYPE_STOP_NOT_ADVERTISED                                         ActivityType = 22
	ActivityType_ACTIVITY_TYPE_STOPS_FOR_OTHER_OPERATING_REASONS                           ActivityType = 23
	ActivityType_ACTIVITY_TYPE_TRAIN_LOCOMOTIVE_ON_REAR                                    ActivityType = 24
	ActivityType_ACTIVITY_TYPE_PROPELLING_BETWEEN_POINTS_SHOWN                             ActivityType = 25
	ActivityType_ACTIVITY_TYPE_STOPS_WHEN_REQUIRED                                         ActivityType = 26
	ActivityType_ACTIVITY_TYPE_STOPS_FOR_REVERSING_MOVEMENT_OR_DRIVER_END_CHANGE           ActivityType = 27
	ActivityType_ACTIVITY_TYPE_STOPS_FOR_LOCOMOTIVE_TO_RUN_ROUND                           ActivityType = 28
	ActivityType_ACTIVITY_TYPE_STOPS_FOR_RAILWAY_PERSONELL_ONLY                            ActivityType = 29
	ActivityType_ACTIVITY_TYPE_STOPS_TO_ATTACH_AND_DETACH_VEHICLES                         ActivityType = 30
	ActivityType_ACTIVITY_TYPE_DETAIL_CONSIST_FOR_TOPS_DIRECT                              ActivityType = 31
	ActivityType_ACTIVITY_TYPE_STOPS_OR_PASSES_FOR_TABLET_STAFF_OR_TOKEN                   ActivityType = 32
	ActivityType_ACTIVITY_TYPE_STOPS_TO_ATTACH_VEHICLES                                    ActivityType = 33
	ActivityType_ACTIVITY_TYPE_STOPS_FOR_WATERING_OF_COACHES                               ActivityType = 34
	ActivityType_ACTIVITY_TYPE_PASSES_ANOTHER_TRAIN_AT_CROSSING_POINT_ON_SINGLE_LINE       ActivityType = 35
)

// Enum value maps for ActivityType.
var (
	ActivityType_name = map[int32]string{
		0:  "ACTIVITY_TYPE_UNKNOWN",
		1:  "ACTIVITY_TYPE_TRAIN_BEGINS",
		2:  "ACTIVITY_TYPE_TRAIN_FINISHES",
		3:  "ACTIVITY_TYPE_STOPS_TO_TAKE_UP_AND_SET_DOWN_PASSENGERS",
		4:  "ACTIVITY_TYPE_STOPS_TO_TAKE_UP_PASSENGERS",
		5:  "ACTIVITY_TYPE_STOPS_TO_SET_DOWN_PASSENGERS",
		6:  "ACTIVITY_TYPE_STOPS_OR_SHUNTS_FOR_OTHER_TRAINS_TO_PASS",
		7:  "ACTIVITY_TYPE_STOPS_TO_ATTACH_OR_DETACH_ASSISTING_LOCOMOTIVE",
		8:  "ACTIVITY_TYPE_SHOWS_AS_X_ON_ARRIVAL",
		9:  "ACTIVITY_TYPE_STOPS_FOR_BANKING_LOCOMOTIVE",
		10: "ACTIVITY_TYPE_STOPS_TO_CHANGE_TRAIN_CREW",
		11: "ACTIVITY_TYPE_STOPS_TO_DETATCH_VEHICLES",
		12: "ACTIVITY_TYPE_STOPS_FOR_EXAMINATION",
		13: "ACTIVITY_TYPE_NATIONAL_RAIL_TIMETABLE_DATA_TO_ADD",
		14: "ACTIVITY_TYPE_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE",
		15: "ACTIVITY_TYPE_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE_TWICE",
		16: "ACTIVITY_TYPE_PASSENGER_COUNT_POINT",
		17: "ACTIVITY_TYPE_TICKET_COLLECTION_AND_EXAMINATION_POINT",
		18: "ACTIVITY_TYPE_TICKET_EXAMINATION_POINT",
		19: "ACTIVITY_TYPE_TICKET_EXAMINATION_POINT_FIRST_CLASS_ONLY",
		20: "ACTIVITY_TYPE_TICKET_EXAMINATION_POINT_SELECTIVE",
		21: "ACTIVITY_TYPE_STOPS_TO_CHANGE_LOCOMOTIVES",
		22: "ACTIVITY_TYPE_STOP_NOT_ADVERTISED",
		23: "ACTIVITY_TYPE_STOPS_FOR_OTHER_OPERATING_REASONS",
		24: "ACTIVITY_TYPE_TRAIN_LOCOMOTIVE_ON_REAR",
		25: "ACTIVITY_TYPE_PROPELLING_BETWEEN_POINTS_SHOWN",
		26: "ACTIVITY_TYPE_STOPS_WHEN_REQUIRED",
		27: "ACTIVITY_TYPE_STOPS_FOR_REVERSING_MOVEMENT_OR_DRIVER_END_CHANGE",
		28: "ACTIVITY_TYPE_STOPS_FOR_LOCOMOTIVE_TO_RUN_ROUND",
		29: "ACTIVITY_TYPE_STOPS_FOR_RAILWAY_PERSONELL_ONLY",
		30: "ACTIVITY_TYPE_STOPS_TO_ATTACH_AND_DETACH_VEHICLES",
		31: "ACTIVITY_TYPE_DETAIL_CONSIST_FOR_TOPS_DIRECT",
		32: "ACTIVITY_TYPE_STOPS_OR_PASSES_FOR_TABLET_STAFF_OR_TOKEN",
		33: "ACTIVITY_TYPE_STOPS_TO_ATTACH_VEHICLES",
		34: "ACTIVITY_TYPE_STOPS_FOR_WATERING_OF_COACHES",
		35: "ACTIVITY_TYPE_PASSES_ANOTHER_TRAIN_AT_CROSSING_POINT_ON_SINGLE_LINE",
	}
	ActivityType_value = map[string]int32{
		"ACTIVITY_TYPE_UNKNOWN":                                                     0,
		"ACTIVITY_TYPE_TRAIN_BEGINS":                                                1,
		"ACTIVITY_TYPE_TRAIN_FINISHES":                                              2,
		"ACTIVITY_TYPE_STOPS_TO_TAKE_UP_AND_SET_DOWN_PASSENGERS":                    3,
		"ACTIVITY_TYPE_STOPS_TO_TAKE_UP_PASSENGERS":                                 4,
		"ACTIVITY_TYPE_STOPS_TO_SET_DOWN_PASSENGERS":                                5,
		"ACTIVITY_TYPE_STOPS_OR_SHUNTS_FOR_OTHER_TRAINS_TO_PASS":                    6,
		"ACTIVITY_TYPE_STOPS_TO_ATTACH_OR_DETACH_ASSISTING_LOCOMOTIVE":              7,
		"ACTIVITY_TYPE_SHOWS_AS_X_ON_ARRIVAL":                                       8,
		"ACTIVITY_TYPE_STOPS_FOR_BANKING_LOCOMOTIVE":                                9,
		"ACTIVITY_TYPE_STOPS_TO_CHANGE_TRAIN_CREW":                                  10,
		"ACTIVITY_TYPE_STOPS_TO_DETATCH_VEHICLES":                                   11,
		"ACTIVITY_TYPE_STOPS_FOR_EXAMINATION":                                       12,
		"ACTIVITY_TYPE_NATIONAL_RAIL_TIMETABLE_DATA_TO_ADD":                         13,
		"ACTIVITY_TYPE_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE":       14,
		"ACTIVITY_TYPE_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE_TWICE": 15,
		"ACTIVITY_TYPE_PASSENGER_COUNT_POINT":                                       16,
		"ACTIVITY_TYPE_TICKET_COLLECTION_AND_EXAMINATION_POINT":                     17,
		"ACTIVITY_TYPE_TICKET_EXAMINATION_POINT":                                    18,
		"ACTIVITY_TYPE_TICKET_EXAMINATION_POINT_FIRST_CLASS_ONLY":                   19,
		"ACTIVITY_TYPE_TICKET_EXAMINATION_POINT_SELECTIVE":                          20,
		"ACTIVITY_TYPE_STOPS_TO_CHANGE_LOCOMOTIVES":                                 21,
		"ACTIVITY_TYPE_STOP_NOT_ADVERTISED":                                         22,
		"ACTIVITY_TYPE_STOPS_FOR_OTHER_OPERATING_REASONS":                           23,
		"ACTIVITY_TYPE_TRAIN_LOCOMOTIVE_ON_REAR":                                    24,
		"ACTIVITY_TYPE_PROPELLING_BETWEEN_POINTS_SHOWN":                             25,
		"ACTIVITY_TYPE_STOPS_WHEN_REQUIRED":                                         26,
		"ACTIVITY_TYPE_STOPS_FOR_REVERSING_MOVEMENT_OR_DRIVER_END_CHANGE":           27,
		"ACTIVITY_TYPE_STOPS_FOR_LOCOMOTIVE_TO_RUN_ROUND":                           28,
		"ACTIVITY_TYPE_STOPS_FOR_RAILWAY_PERSONELL_ONLY":                            29,
		"ACTIVITY_TYPE_STOPS_TO_ATTACH_AND_DETACH_VEHICLES":                         30,
		"ACTIVITY_TYPE_DETAIL_CONSIST_FOR_TOPS_DIRECT":                              31,
		"ACTIVITY_TYPE_STOPS_OR_PASSES_FOR_TABLET_STAFF_OR_TOKEN":                   32,
		"ACTIVITY_TYPE_STOPS_TO_ATTACH_VEHICLES":                                    33,
		"ACTIVITY_TYPE_STOPS_FOR_WATERING_OF_COACHES":                               34,
		"ACTIVITY_TYPE_PASSES_ANOTHER_TRAIN_AT_CROSSING_POINT_ON_SINGLE_LINE":       35,
	}
)

func (x ActivityType) Enum() *ActivityType {
	p := new(ActivityType)
	*p = x
	return p
}

func (x ActivityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityType) Descriptor() protoreflect.EnumDescriptor {
	return file_search_proto_enumTypes[3].Descriptor()
}

func (ActivityType) Type() protoreflect.EnumType {
	return &file_search_proto_enumTypes[3]
}

func (x ActivityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityType.Descriptor instead.
func (ActivityType) EnumDescriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{3}
}

type LocationType int32

const (
	LocationType_LOCATION_TYPE_UNKNOWN                  LocationType = 0
	LocationType_LOCATION_TYPE_ORIGIN                   LocationType = 1
	LocationType_LOCATION_TYPE_OPERATIONAL_ORIGIN       LocationType = 2
	LocationType_LOCATION_TYPE_INTERMEDIATE             LocationType = 3
	LocationType_LOCATION_TYPE_OPERATIONAL_INTERMEDIATE LocationType = 4
	LocationType_LOCATION_TYPE_INTERMEDIATE_PASSING     LocationType = 5
	LocationType_LOCATION_TYPE_DESTINATION              LocationType = 6
	LocationType_LOCATION_TYPE_OPERATIONAL_DESTINATION  LocationType = 7
)

// Enum value maps for LocationType.
var (
	LocationType_name = map[int32]string{
		0: "LOCATION_TYPE_UNKNOWN",
		1: "LOCATION_TYPE_ORIGIN",
		2: "LOCATION_TYPE_OPERATIONAL_ORIGIN",
		3: "LOCATION_TYPE_INTERMEDIATE",
		4: "LOCATION_TYPE_OPERATIONAL_INTERMEDIATE",
		5: "LOCATION_TYPE_INTERMEDIATE_PASSING",
		6: "LOCATION_TYPE_DESTINATION",
		7: "LOCATION_TYPE_OPERATIONAL_DESTINATION",
	}
	LocationType_value = map[string]int32{
		"LOCATION_TYPE_UNKNOWN":                  0,
		"LOCATION_TYPE_ORIGIN":                   1,
		"LOCATION_TYPE_OPERATIONAL_ORIGIN":       2,
		"LOCATION_TYPE_INTERMEDIATE":             3,
		"LOCATION_TYPE_OPERATIONAL_INTERMEDIATE": 4,
		"LOCATION_TYPE_INTERMEDIATE_PASSING":     5,
		"LOCATION_TYPE_DESTINATION":              6,
		"LOCATION_TYPE_OPERATIONAL_DESTINATION":  7,
	}
)

func (x LocationType) Enum() *LocationType {
	p := new(LocationType)
	*p = x
	return p
}

func (x LocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_search_proto_enumTypes[4].Descriptor()
}

func (LocationType) Type() protoreflect.EnumType {
	return &file_search_proto_enumTypes[4]
}

func (x LocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocationType.Descriptor instead.
func (LocationType) EnumDescriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{4}
}

type PlatformDataSource int32

const (
	PlatformDataSource_PLATFORM_DATA_SOURCE_UNKNOWN   PlatformDataSource = 0
	PlatformDataSource_PLATFORM_DATA_SOURCE_PLANNED   PlatformDataSource = 1
	PlatformDataSource_PLATFORM_DATA_SOURCE_AUTOMATIC PlatformDataSource = 2
	PlatformDataSource_PLATFORM_DATA_SOURCE_MANUAL    PlatformDataSource = 3
)

// Enum value maps for PlatformDataSource.
var (
	PlatformDataSource_name = map[int32]string{
		0: "PLATFORM_DATA_SOURCE_UNKNOWN",
		1: "PLATFORM_DATA_SOURCE_PLANNED",
		2: "PLATFORM_DATA_SOURCE_AUTOMATIC",
		3: "PLATFORM_DATA_SOURCE_MANUAL",
	}
	PlatformDataSource_value = map[string]int32{
		"PLATFORM_DATA_SOURCE_UNKNOWN":   0,
		"PLATFORM_DATA_SOURCE_PLANNED":   1,
		"PLATFORM_DATA_SOURCE_AUTOMATIC": 2,
		"PLATFORM_DATA_SOURCE_MANUAL":    3,
	}
)

func (x PlatformDataSource) Enum() *PlatformDataSource {
	p := new(PlatformDataSource)
	*p = x
	return p
}

func (x PlatformDataSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlatformDataSource) Descriptor() protoreflect.EnumDescriptor {
	return file_search_proto_enumTypes[5].Descriptor()
}

func (PlatformDataSource) Type() protoreflect.EnumType {
	return &file_search_proto_enumTypes[5]
}

func (x PlatformDataSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlatformDataSource.Descriptor instead.
func (PlatformDataSource) EnumDescriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{5}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchType    SearchType             `protobuf:"varint,1,opt,name=search_type,json=searchType,proto3,enum=SearchType" json:"search_type,omitempty"`
	LocationId    *string                `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3,oneof" json:"location_id,omitempty"`
	CrsId         *string                `protobuf:"bytes,3,opt,name=crs_id,json=crsId,proto3,oneof" json:"crs_id,omitempty"`
	FromTime      string                 `protobuf:"bytes,4,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`
	ToTime        string                 `protobuf:"bytes,5,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetSearchType() SearchType {
	if x != nil {
		return x.SearchType
	}
	return SearchType_SEARCH_TYPE_RETURN_NONE
}

func (x *SearchRequest) GetLocationId() string {
	if x != nil && x.LocationId != nil {
		return *x.LocationId
	}
	return ""
}

func (x *SearchRequest) GetCrsId() string {
	if x != nil && x.CrsId != nil {
		return *x.CrsId
	}
	return ""
}

func (x *SearchRequest) GetFromTime() string {
	if x != nil {
		return x.FromTime
	}
	return ""
}

func (x *SearchRequest) GetToTime() string {
	if x != nil {
		return x.ToTime
	}
	return ""
}

type SearchResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Schedule         *Schedule              `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	ScheduleLocation *ScheduleLocation      `protobuf:"bytes,2,opt,name=schedule_location,json=scheduleLocation,proto3" json:"schedule_location,omitempty"`
	Forecast         *Forecast              `protobuf:"bytes,3,opt,name=forecast,proto3,oneof" json:"forecast,omitempty"`
	Platform         *string                `protobuf:"bytes,4,opt,name=platform,proto3,oneof" json:"platform,omitempty"` // can be sourced either from darwin.schedule_locations or darwin.forecast_locations
	Length           *uint32                `protobuf:"varint,5,opt,name=length,proto3,oneof" json:"length,omitempty"`    // number of coaches, can be sourced either from darwin.formation_coaches or darwin.forecast_locations
	IsCircularRoute  bool                   `protobuf:"varint,6,opt,name=is_circular_route,json=isCircularRoute,proto3" json:"is_circular_route,omitempty"`
	PreviousRoute    *ServiceRoute          `protobuf:"bytes,7,opt,name=previous_route,json=previousRoute,proto3" json:"previous_route,omitempty"`
	NextRoute        *ServiceRoute          `protobuf:"bytes,8,opt,name=next_route,json=nextRoute,proto3" json:"next_route,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetSchedule() *Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *SearchResponse) GetScheduleLocation() *ScheduleLocation {
	if x != nil {
		return x.ScheduleLocation
	}
	return nil
}

func (x *SearchResponse) GetForecast() *Forecast {
	if x != nil {
		return x.Forecast
	}
	return nil
}

func (x *SearchResponse) GetPlatform() string {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return ""
}

func (x *SearchResponse) GetLength() uint32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *SearchResponse) GetIsCircularRoute() bool {
	if x != nil {
		return x.IsCircularRoute
	}
	return false
}

func (x *SearchResponse) GetPreviousRoute() *ServiceRoute {
	if x != nil {
		return x.PreviousRoute
	}
	return nil
}

func (x *SearchResponse) GetNextRoute() *ServiceRoute {
	if x != nil {
		return x.NextRoute
	}
	return nil
}

type ServiceRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRoute) Reset() {
	*x = ServiceRoute{}
	mi := &file_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRoute) ProtoMessage() {}

func (x *ServiceRoute) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRoute.ProtoReflect.Descriptor instead.
func (*ServiceRoute) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{2}
}

type ServiceRouteLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRouteLocation) Reset() {
	*x = ServiceRouteLocation{}
	mi := &file_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRouteLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRouteLocation) ProtoMessage() {}

func (x *ServiceRouteLocation) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRouteLocation.ProtoReflect.Descriptor instead.
func (*ServiceRouteLocation) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{3}
}

type DisruptionReason struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReasonId         uint32                 `protobuf:"varint,1,opt,name=reason_id,json=reasonId,proto3" json:"reason_id,omitempty"`
	ReasonLocationId *string                `protobuf:"bytes,2,opt,name=reason_location_id,json=reasonLocationId,proto3,oneof" json:"reason_location_id,omitempty"`
	// When true, the provided reason_id is 'near to' the provided reason_location_id.
	// When false, the reason_id is 'at' the reason_location_id.
	ReasonIsNearLocation bool `protobuf:"varint,3,opt,name=reason_is_near_location,json=reasonIsNearLocation,proto3" json:"reason_is_near_location,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DisruptionReason) Reset() {
	*x = DisruptionReason{}
	mi := &file_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisruptionReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisruptionReason) ProtoMessage() {}

func (x *DisruptionReason) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisruptionReason.ProtoReflect.Descriptor instead.
func (*DisruptionReason) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{4}
}

func (x *DisruptionReason) GetReasonId() uint32 {
	if x != nil {
		return x.ReasonId
	}
	return 0
}

func (x *DisruptionReason) GetReasonLocationId() string {
	if x != nil && x.ReasonLocationId != nil {
		return *x.ReasonLocationId
	}
	return ""
}

func (x *DisruptionReason) GetReasonIsNearLocation() bool {
	if x != nil {
		return x.ReasonIsNearLocation
	}
	return false
}

type Schedule struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId                    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Uid                           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Headcode                      string                 `protobuf:"bytes,3,opt,name=headcode,proto3" json:"headcode,omitempty"`
	RetailServiceId               *string                `protobuf:"bytes,4,opt,name=retail_service_id,json=retailServiceId,proto3,oneof" json:"retail_service_id,omitempty"`
	TocId                         string                 `protobuf:"bytes,5,opt,name=toc_id,json=tocId,proto3" json:"toc_id,omitempty"`
	ServiceType                   ServiceType            `protobuf:"varint,6,opt,name=service_type,json=serviceType,proto3,enum=ServiceType" json:"service_type,omitempty"`
	CategoryType                  CategoryType           `protobuf:"varint,7,opt,name=category_type,json=categoryType,proto3,enum=CategoryType" json:"category_type,omitempty"`
	IsPassenger                   bool                   `protobuf:"varint,8,opt,name=is_passenger,json=isPassenger,proto3" json:"is_passenger,omitempty"`
	IsActive                      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsChartered                   bool                   `protobuf:"varint,10,opt,name=is_chartered,json=isChartered,proto3" json:"is_chartered,omitempty"`
	ScheduleIsCancelled           bool                   `protobuf:"varint,11,opt,name=schedule_is_cancelled,json=scheduleIsCancelled,proto3" json:"schedule_is_cancelled,omitempty"`
	ScheduleCancellationReason    *DisruptionReason      `protobuf:"bytes,12,opt,name=schedule_cancellation_reason,json=scheduleCancellationReason,proto3,oneof" json:"schedule_cancellation_reason,omitempty"`
	ScheduleDivertedViaLocationId *string                `protobuf:"bytes,13,opt,name=schedule_diverted_via_location_id,json=scheduleDivertedViaLocationId,proto3,oneof" json:"schedule_diverted_via_location_id,omitempty"`
	ScheduleDiversionReason       *DisruptionReason      `protobuf:"bytes,14,opt,name=schedule_diversion_reason,json=scheduleDiversionReason,proto3,oneof" json:"schedule_diversion_reason,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{5}
}

func (x *Schedule) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *Schedule) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Schedule) GetHeadcode() string {
	if x != nil {
		return x.Headcode
	}
	return ""
}

func (x *Schedule) GetRetailServiceId() string {
	if x != nil && x.RetailServiceId != nil {
		return *x.RetailServiceId
	}
	return ""
}

func (x *Schedule) GetTocId() string {
	if x != nil {
		return x.TocId
	}
	return ""
}

func (x *Schedule) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_UNKNOWN
}

func (x *Schedule) GetCategoryType() CategoryType {
	if x != nil {
		return x.CategoryType
	}
	return CategoryType_CATEGORY_TYPE_UNKNOWN
}

func (x *Schedule) GetIsPassenger() bool {
	if x != nil {
		return x.IsPassenger
	}
	return false
}

func (x *Schedule) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Schedule) GetIsChartered() bool {
	if x != nil {
		return x.IsChartered
	}
	return false
}

func (x *Schedule) GetScheduleIsCancelled() bool {
	if x != nil {
		return x.ScheduleIsCancelled
	}
	return false
}

func (x *Schedule) GetScheduleCancellationReason() *DisruptionReason {
	if x != nil {
		return x.ScheduleCancellationReason
	}
	return nil
}

func (x *Schedule) GetScheduleDivertedViaLocationId() string {
	if x != nil && x.ScheduleDivertedViaLocationId != nil {
		return *x.ScheduleDivertedViaLocationId
	}
	return ""
}

func (x *Schedule) GetScheduleDiversionReason() *DisruptionReason {
	if x != nil {
		return x.ScheduleDiversionReason
	}
	return nil
}

type ScheduleLocation struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Activities                    []ActivityType         `protobuf:"varint,1,rep,packed,name=activities,proto3,enum=ActivityType" json:"activities,omitempty"`
	PlannedActivities             []ActivityType         `protobuf:"varint,2,rep,packed,name=planned_activities,json=plannedActivities,proto3,enum=ActivityType" json:"planned_activities,omitempty"`
	LocationIsAffectedByDiversion bool                   `protobuf:"varint,3,opt,name=location_is_affected_by_diversion,json=locationIsAffectedByDiversion,proto3" json:"location_is_affected_by_diversion,omitempty"`
	LocationType                  LocationType           `protobuf:"varint,4,opt,name=location_type,json=locationType,proto3,enum=LocationType" json:"location_type,omitempty"`
	ScheduledWorkingArrivalTime   *string                `protobuf:"bytes,5,opt,name=scheduled_working_arrival_time,json=scheduledWorkingArrivalTime,proto3,oneof" json:"scheduled_working_arrival_time,omitempty"`
	ScheduledWorkingPassingTime   *string                `protobuf:"bytes,6,opt,name=scheduled_working_passing_time,json=scheduledWorkingPassingTime,proto3,oneof" json:"scheduled_working_passing_time,omitempty"`
	ScheduledWorkingDepartureTime *string                `protobuf:"bytes,7,opt,name=scheduled_working_departure_time,json=scheduledWorkingDepartureTime,proto3,oneof" json:"scheduled_working_departure_time,omitempty"`
	ScheduledPublicArrivalTime    *string                `protobuf:"bytes,8,opt,name=scheduled_public_arrival_time,json=scheduledPublicArrivalTime,proto3,oneof" json:"scheduled_public_arrival_time,omitempty"`
	ScheduledPublicDepartureTime  *string                `protobuf:"bytes,9,opt,name=scheduled_public_departure_time,json=scheduledPublicDepartureTime,proto3,oneof" json:"scheduled_public_departure_time,omitempty"`
	RoutingDelay                  uint32                 `protobuf:"varint,10,opt,name=routing_delay,json=routingDelay,proto3" json:"routing_delay,omitempty"` // in minutes
	LocationIsCancelled           bool                   `protobuf:"varint,11,opt,name=location_is_cancelled,json=locationIsCancelled,proto3" json:"location_is_cancelled,omitempty"`
	LocationCancellationReason    *DisruptionReason      `protobuf:"bytes,12,opt,name=location_cancellation_reason,json=locationCancellationReason,proto3,oneof" json:"location_cancellation_reason,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ScheduleLocation) Reset() {
	*x = ScheduleLocation{}
	mi := &file_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleLocation) ProtoMessage() {}

func (x *ScheduleLocation) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleLocation.ProtoReflect.Descriptor instead.
func (*ScheduleLocation) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{6}
}

func (x *ScheduleLocation) GetActivities() []ActivityType {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *ScheduleLocation) GetPlannedActivities() []ActivityType {
	if x != nil {
		return x.PlannedActivities
	}
	return nil
}

func (x *ScheduleLocation) GetLocationIsAffectedByDiversion() bool {
	if x != nil {
		return x.LocationIsAffectedByDiversion
	}
	return false
}

func (x *ScheduleLocation) GetLocationType() LocationType {
	if x != nil {
		return x.LocationType
	}
	return LocationType_LOCATION_TYPE_UNKNOWN
}

func (x *ScheduleLocation) GetScheduledWorkingArrivalTime() string {
	if x != nil && x.ScheduledWorkingArrivalTime != nil {
		return *x.ScheduledWorkingArrivalTime
	}
	return ""
}

func (x *ScheduleLocation) GetScheduledWorkingPassingTime() string {
	if x != nil && x.ScheduledWorkingPassingTime != nil {
		return *x.ScheduledWorkingPassingTime
	}
	return ""
}

func (x *ScheduleLocation) GetScheduledWorkingDepartureTime() string {
	if x != nil && x.ScheduledWorkingDepartureTime != nil {
		return *x.ScheduledWorkingDepartureTime
	}
	return ""
}

func (x *ScheduleLocation) GetScheduledPublicArrivalTime() string {
	if x != nil && x.ScheduledPublicArrivalTime != nil {
		return *x.ScheduledPublicArrivalTime
	}
	return ""
}

func (x *ScheduleLocation) GetScheduledPublicDepartureTime() string {
	if x != nil && x.ScheduledPublicDepartureTime != nil {
		return *x.ScheduledPublicDepartureTime
	}
	return ""
}

func (x *ScheduleLocation) GetRoutingDelay() uint32 {
	if x != nil {
		return x.RoutingDelay
	}
	return 0
}

func (x *ScheduleLocation) GetLocationIsCancelled() bool {
	if x != nil {
		return x.LocationIsCancelled
	}
	return false
}

func (x *ScheduleLocation) GetLocationCancellationReason() *DisruptionReason {
	if x != nil {
		return x.LocationCancellationReason
	}
	return nil
}

type Forecast struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	IsReverseFormation                bool                   `protobuf:"varint,1,opt,name=is_reverse_formation,json=isReverseFormation,proto3" json:"is_reverse_formation,omitempty"`
	ScheduleLateReason                *DisruptionReason      `protobuf:"bytes,2,opt,name=schedule_late_reason,json=scheduleLateReason,proto3,oneof" json:"schedule_late_reason,omitempty"`
	EstimatedPublicArrivalTime        *string                `protobuf:"bytes,3,opt,name=estimated_public_arrival_time,json=estimatedPublicArrivalTime,proto3,oneof" json:"estimated_public_arrival_time,omitempty"`
	EstimatedWorkingArrivalTime       *string                `protobuf:"bytes,4,opt,name=estimated_working_arrival_time,json=estimatedWorkingArrivalTime,proto3,oneof" json:"estimated_working_arrival_time,omitempty"`
	EstimatedMinimumArrivalTime       *string                `protobuf:"bytes,5,opt,name=estimated_minimum_arrival_time,json=estimatedMinimumArrivalTime,proto3,oneof" json:"estimated_minimum_arrival_time,omitempty"`
	ArrivalIsDelayed                  *bool                  `protobuf:"varint,6,opt,name=arrival_is_delayed,json=arrivalIsDelayed,proto3,oneof" json:"arrival_is_delayed,omitempty"`
	ArrivalIsDelayedByUnknownAmount   *bool                  `protobuf:"varint,7,opt,name=arrival_is_delayed_by_unknown_amount,json=arrivalIsDelayedByUnknownAmount,proto3,oneof" json:"arrival_is_delayed_by_unknown_amount,omitempty"`
	EstimatedPassingTime              *string                `protobuf:"bytes,8,opt,name=estimated_passing_time,json=estimatedPassingTime,proto3,oneof" json:"estimated_passing_time,omitempty"`
	EstimatedMinimumPassingTime       *string                `protobuf:"bytes,9,opt,name=estimated_minimum_passing_time,json=estimatedMinimumPassingTime,proto3,oneof" json:"estimated_minimum_passing_time,omitempty"`
	PassingIsDelayed                  *bool                  `protobuf:"varint,10,opt,name=passing_is_delayed,json=passingIsDelayed,proto3,oneof" json:"passing_is_delayed,omitempty"`
	PassingIsDelayedByUnknownAmount   *bool                  `protobuf:"varint,11,opt,name=passing_is_delayed_by_unknown_amount,json=passingIsDelayedByUnknownAmount,proto3,oneof" json:"passing_is_delayed_by_unknown_amount,omitempty"`
	EstimatedPublicDepartureTime      *string                `protobuf:"bytes,12,opt,name=estimated_public_departure_time,json=estimatedPublicDepartureTime,proto3,oneof" json:"estimated_public_departure_time,omitempty"`
	EstimatedWorkingDepartureTime     *string                `protobuf:"bytes,13,opt,name=estimated_working_departure_time,json=estimatedWorkingDepartureTime,proto3,oneof" json:"estimated_working_departure_time,omitempty"`
	EstimatedMinimumDepartureTime     *string                `protobuf:"bytes,14,opt,name=estimated_minimum_departure_time,json=estimatedMinimumDepartureTime,proto3,oneof" json:"estimated_minimum_departure_time,omitempty"`
	DepartureIsDelayed                *bool                  `protobuf:"varint,15,opt,name=departure_is_delayed,json=departureIsDelayed,proto3,oneof" json:"departure_is_delayed,omitempty"`
	DepartureIsDelayedByUnknownAmount *bool                  `protobuf:"varint,16,opt,name=departure_is_delayed_by_unknown_amount,json=departureIsDelayedByUnknownAmount,proto3,oneof" json:"departure_is_delayed_by_unknown_amount,omitempty"`
	ActualArrivalTime                 *string                `protobuf:"bytes,17,opt,name=actual_arrival_time,json=actualArrivalTime,proto3,oneof" json:"actual_arrival_time,omitempty"`
	ActualArrivalDataClass            *string                `protobuf:"bytes,18,opt,name=actual_arrival_data_class,json=actualArrivalDataClass,proto3,oneof" json:"actual_arrival_data_class,omitempty"`
	ActualArrivalDataSource           *string                `protobuf:"bytes,19,opt,name=actual_arrival_data_source,json=actualArrivalDataSource,proto3,oneof" json:"actual_arrival_data_source,omitempty"`
	ActualArrivalDataSourceSystem     *string                `protobuf:"bytes,20,opt,name=actual_arrival_data_source_system,json=actualArrivalDataSourceSystem,proto3,oneof" json:"actual_arrival_data_source_system,omitempty"`
	ActualPassingTime                 *string                `protobuf:"bytes,21,opt,name=actual_passing_time,json=actualPassingTime,proto3,oneof" json:"actual_passing_time,omitempty"`
	ActualPassingDataClass            *string                `protobuf:"bytes,22,opt,name=actual_passing_data_class,json=actualPassingDataClass,proto3,oneof" json:"actual_passing_data_class,omitempty"`
	ActualPassingDataSource           *string                `protobuf:"bytes,23,opt,name=actual_passing_data_source,json=actualPassingDataSource,proto3,oneof" json:"actual_passing_data_source,omitempty"`
	ActualPassingDataSourceSystem     *string                `protobuf:"bytes,24,opt,name=actual_passing_data_source_system,json=actualPassingDataSourceSystem,proto3,oneof" json:"actual_passing_data_source_system,omitempty"`
	ActualDepartureTime               *string                `protobuf:"bytes,25,opt,name=actual_departure_time,json=actualDepartureTime,proto3,oneof" json:"actual_departure_time,omitempty"`
	ActualDepartureDataClass          *string                `protobuf:"bytes,26,opt,name=actual_departure_data_class,json=actualDepartureDataClass,proto3,oneof" json:"actual_departure_data_class,omitempty"`
	ActualDepartureDataSource         *string                `protobuf:"bytes,27,opt,name=actual_departure_data_source,json=actualDepartureDataSource,proto3,oneof" json:"actual_departure_data_source,omitempty"`
	ActualDepartureDataSourceSystem   *string                `protobuf:"bytes,28,opt,name=actual_departure_data_source_system,json=actualDepartureDataSourceSystem,proto3,oneof" json:"actual_departure_data_source_system,omitempty"`
	LocationLateReason                *DisruptionReason      `protobuf:"bytes,29,opt,name=location_late_reason,json=locationLateReason,proto3,oneof" json:"location_late_reason,omitempty"`
	LocationDisruptionRisk            *string                `protobuf:"bytes,30,opt,name=location_disruption_risk,json=locationDisruptionRisk,proto3,oneof" json:"location_disruption_risk,omitempty"`
	LocationDisruptionRiskReason      *DisruptionReason      `protobuf:"bytes,31,opt,name=location_disruption_risk_reason,json=locationDisruptionRiskReason,proto3,oneof" json:"location_disruption_risk_reason,omitempty"`
	AffectedBy                        *string                `protobuf:"bytes,32,opt,name=affected_by,json=affectedBy,proto3,oneof" json:"affected_by,omitempty"`
	PlatformIsSuppressed              *bool                  `protobuf:"varint,33,opt,name=platform_is_suppressed,json=platformIsSuppressed,proto3,oneof" json:"platform_is_suppressed,omitempty"` // do not display platform information if true
	PlatformIsSuppressedByCis         *bool                  `protobuf:"varint,34,opt,name=platform_is_suppressed_by_cis,json=platformIsSuppressedByCis,proto3,oneof" json:"platform_is_suppressed_by_cis,omitempty"`
	PlatformDataSource                *PlatformDataSource    `protobuf:"varint,35,opt,name=platform_data_source,json=platformDataSource,proto3,enum=PlatformDataSource,oneof" json:"platform_data_source,omitempty"`
	PlatformIsConfirmed               *bool                  `protobuf:"varint,36,opt,name=platform_is_confirmed,json=platformIsConfirmed,proto3,oneof" json:"platform_is_confirmed,omitempty"`
	ServiceIsSuppressed               bool                   `protobuf:"varint,37,opt,name=service_is_suppressed,json=serviceIsSuppressed,proto3" json:"service_is_suppressed,omitempty"`
	ServiceDetatchesFromFront         bool                   `protobuf:"varint,38,opt,name=service_detatches_from_front,json=serviceDetatchesFromFront,proto3" json:"service_detatches_from_front,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *Forecast) Reset() {
	*x = Forecast{}
	mi := &file_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forecast) ProtoMessage() {}

func (x *Forecast) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forecast.ProtoReflect.Descriptor instead.
func (*Forecast) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{7}
}

func (x *Forecast) GetIsReverseFormation() bool {
	if x != nil {
		return x.IsReverseFormation
	}
	return false
}

func (x *Forecast) GetScheduleLateReason() *DisruptionReason {
	if x != nil {
		return x.ScheduleLateReason
	}
	return nil
}

func (x *Forecast) GetEstimatedPublicArrivalTime() string {
	if x != nil && x.EstimatedPublicArrivalTime != nil {
		return *x.EstimatedPublicArrivalTime
	}
	return ""
}

func (x *Forecast) GetEstimatedWorkingArrivalTime() string {
	if x != nil && x.EstimatedWorkingArrivalTime != nil {
		return *x.EstimatedWorkingArrivalTime
	}
	return ""
}

func (x *Forecast) GetEstimatedMinimumArrivalTime() string {
	if x != nil && x.EstimatedMinimumArrivalTime != nil {
		return *x.EstimatedMinimumArrivalTime
	}
	return ""
}

func (x *Forecast) GetArrivalIsDelayed() bool {
	if x != nil && x.ArrivalIsDelayed != nil {
		return *x.ArrivalIsDelayed
	}
	return false
}

func (x *Forecast) GetArrivalIsDelayedByUnknownAmount() bool {
	if x != nil && x.ArrivalIsDelayedByUnknownAmount != nil {
		return *x.ArrivalIsDelayedByUnknownAmount
	}
	return false
}

func (x *Forecast) GetEstimatedPassingTime() string {
	if x != nil && x.EstimatedPassingTime != nil {
		return *x.EstimatedPassingTime
	}
	return ""
}

func (x *Forecast) GetEstimatedMinimumPassingTime() string {
	if x != nil && x.EstimatedMinimumPassingTime != nil {
		return *x.EstimatedMinimumPassingTime
	}
	return ""
}

func (x *Forecast) GetPassingIsDelayed() bool {
	if x != nil && x.PassingIsDelayed != nil {
		return *x.PassingIsDelayed
	}
	return false
}

func (x *Forecast) GetPassingIsDelayedByUnknownAmount() bool {
	if x != nil && x.PassingIsDelayedByUnknownAmount != nil {
		return *x.PassingIsDelayedByUnknownAmount
	}
	return false
}

func (x *Forecast) GetEstimatedPublicDepartureTime() string {
	if x != nil && x.EstimatedPublicDepartureTime != nil {
		return *x.EstimatedPublicDepartureTime
	}
	return ""
}

func (x *Forecast) GetEstimatedWorkingDepartureTime() string {
	if x != nil && x.EstimatedWorkingDepartureTime != nil {
		return *x.EstimatedWorkingDepartureTime
	}
	return ""
}

func (x *Forecast) GetEstimatedMinimumDepartureTime() string {
	if x != nil && x.EstimatedMinimumDepartureTime != nil {
		return *x.EstimatedMinimumDepartureTime
	}
	return ""
}

func (x *Forecast) GetDepartureIsDelayed() bool {
	if x != nil && x.DepartureIsDelayed != nil {
		return *x.DepartureIsDelayed
	}
	return false
}

func (x *Forecast) GetDepartureIsDelayedByUnknownAmount() bool {
	if x != nil && x.DepartureIsDelayedByUnknownAmount != nil {
		return *x.DepartureIsDelayedByUnknownAmount
	}
	return false
}

func (x *Forecast) GetActualArrivalTime() string {
	if x != nil && x.ActualArrivalTime != nil {
		return *x.ActualArrivalTime
	}
	return ""
}

func (x *Forecast) GetActualArrivalDataClass() string {
	if x != nil && x.ActualArrivalDataClass != nil {
		return *x.ActualArrivalDataClass
	}
	return ""
}

func (x *Forecast) GetActualArrivalDataSource() string {
	if x != nil && x.ActualArrivalDataSource != nil {
		return *x.ActualArrivalDataSource
	}
	return ""
}

func (x *Forecast) GetActualArrivalDataSourceSystem() string {
	if x != nil && x.ActualArrivalDataSourceSystem != nil {
		return *x.ActualArrivalDataSourceSystem
	}
	return ""
}

func (x *Forecast) GetActualPassingTime() string {
	if x != nil && x.ActualPassingTime != nil {
		return *x.ActualPassingTime
	}
	return ""
}

func (x *Forecast) GetActualPassingDataClass() string {
	if x != nil && x.ActualPassingDataClass != nil {
		return *x.ActualPassingDataClass
	}
	return ""
}

func (x *Forecast) GetActualPassingDataSource() string {
	if x != nil && x.ActualPassingDataSource != nil {
		return *x.ActualPassingDataSource
	}
	return ""
}

func (x *Forecast) GetActualPassingDataSourceSystem() string {
	if x != nil && x.ActualPassingDataSourceSystem != nil {
		return *x.ActualPassingDataSourceSystem
	}
	return ""
}

func (x *Forecast) GetActualDepartureTime() string {
	if x != nil && x.ActualDepartureTime != nil {
		return *x.ActualDepartureTime
	}
	return ""
}

func (x *Forecast) GetActualDepartureDataClass() string {
	if x != nil && x.ActualDepartureDataClass != nil {
		return *x.ActualDepartureDataClass
	}
	return ""
}

func (x *Forecast) GetActualDepartureDataSource() string {
	if x != nil && x.ActualDepartureDataSource != nil {
		return *x.ActualDepartureDataSource
	}
	return ""
}

func (x *Forecast) GetActualDepartureDataSourceSystem() string {
	if x != nil && x.ActualDepartureDataSourceSystem != nil {
		return *x.ActualDepartureDataSourceSystem
	}
	return ""
}

func (x *Forecast) GetLocationLateReason() *DisruptionReason {
	if x != nil {
		return x.LocationLateReason
	}
	return nil
}

func (x *Forecast) GetLocationDisruptionRisk() string {
	if x != nil && x.LocationDisruptionRisk != nil {
		return *x.LocationDisruptionRisk
	}
	return ""
}

func (x *Forecast) GetLocationDisruptionRiskReason() *DisruptionReason {
	if x != nil {
		return x.LocationDisruptionRiskReason
	}
	return nil
}

func (x *Forecast) GetAffectedBy() string {
	if x != nil && x.AffectedBy != nil {
		return *x.AffectedBy
	}
	return ""
}

func (x *Forecast) GetPlatformIsSuppressed() bool {
	if x != nil && x.PlatformIsSuppressed != nil {
		return *x.PlatformIsSuppressed
	}
	return false
}

func (x *Forecast) GetPlatformIsSuppressedByCis() bool {
	if x != nil && x.PlatformIsSuppressedByCis != nil {
		return *x.PlatformIsSuppressedByCis
	}
	return false
}

func (x *Forecast) GetPlatformDataSource() PlatformDataSource {
	if x != nil && x.PlatformDataSource != nil {
		return *x.PlatformDataSource
	}
	return PlatformDataSource_PLATFORM_DATA_SOURCE_UNKNOWN
}

func (x *Forecast) GetPlatformIsConfirmed() bool {
	if x != nil && x.PlatformIsConfirmed != nil {
		return *x.PlatformIsConfirmed
	}
	return false
}

func (x *Forecast) GetServiceIsSuppressed() bool {
	if x != nil {
		return x.ServiceIsSuppressed
	}
	return false
}

func (x *Forecast) GetServiceDetatchesFromFront() bool {
	if x != nil {
		return x.ServiceDetatchesFromFront
	}
	return false
}

var File_search_proto protoreflect.FileDescriptor

const file_search_proto_rawDesc = "" +
	"\n" +
	"\fsearch.proto\"\xd0\x01\n" +
	"\rSearchRequest\x12,\n" +
	"\vsearch_type\x18\x01 \x01(\x0e2\v.SearchTypeR\n" +
	"searchType\x12$\n" +
	"\vlocation_id\x18\x02 \x01(\tH\x00R\n" +
	"locationId\x88\x01\x01\x12\x1a\n" +
	"\x06crs_id\x18\x03 \x01(\tH\x01R\x05crsId\x88\x01\x01\x12\x1b\n" +
	"\tfrom_time\x18\x04 \x01(\tR\bfromTime\x12\x17\n" +
	"\ato_time\x18\x05 \x01(\tR\x06toTimeB\x0e\n" +
	"\f_location_idB\t\n" +
	"\a_crs_id\"\x96\x03\n" +
	"\x0eSearchResponse\x12%\n" +
	"\bschedule\x18\x01 \x01(\v2\t.ScheduleR\bschedule\x12>\n" +
	"\x11schedule_location\x18\x02 \x01(\v2\x11.ScheduleLocationR\x10scheduleLocation\x12*\n" +
	"\bforecast\x18\x03 \x01(\v2\t.ForecastH\x00R\bforecast\x88\x01\x01\x12\x1f\n" +
	"\bplatform\x18\x04 \x01(\tH\x01R\bplatform\x88\x01\x01\x12\x1b\n" +
	"\x06length\x18\x05 \x01(\rH\x02R\x06length\x88\x01\x01\x12*\n" +
	"\x11is_circular_route\x18\x06 \x01(\bR\x0fisCircularRoute\x124\n" +
	"\x0eprevious_route\x18\a \x01(\v2\r.ServiceRouteR\rpreviousRoute\x12,\n" +
	"\n" +
	"next_route\x18\b \x01(\v2\r.ServiceRouteR\tnextRouteB\v\n" +
	"\t_forecastB\v\n" +
	"\t_platformB\t\n" +
	"\a_length\"\x0e\n" +
	"\fServiceRoute\"\x16\n" +
	"\x14ServiceRouteLocation\"\xb0\x01\n" +
	"\x10DisruptionReason\x12\x1b\n" +
	"\treason_id\x18\x01 \x01(\rR\breasonId\x121\n" +
	"\x12reason_location_id\x18\x02 \x01(\tH\x00R\x10reasonLocationId\x88\x01\x01\x125\n" +
	"\x17reason_is_near_location\x18\x03 \x01(\bR\x14reasonIsNearLocationB\x15\n" +
	"\x13_reason_location_id\"\x95\x06\n" +
	"\bSchedule\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x1a\n" +
	"\bheadcode\x18\x03 \x01(\tR\bheadcode\x12/\n" +
	"\x11retail_service_id\x18\x04 \x01(\tH\x00R\x0fretailServiceId\x88\x01\x01\x12\x15\n" +
	"\x06toc_id\x18\x05 \x01(\tR\x05tocId\x12/\n" +
	"\fservice_type\x18\x06 \x01(\x0e2\f.ServiceTypeR\vserviceType\x122\n" +
	"\rcategory_type\x18\a \x01(\x0e2\r.CategoryTypeR\fcategoryType\x12!\n" +
	"\fis_passenger\x18\b \x01(\bR\visPassenger\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12!\n" +
	"\fis_chartered\x18\n" +
	" \x01(\bR\visChartered\x122\n" +
	"\x15schedule_is_cancelled\x18\v \x01(\bR\x13scheduleIsCancelled\x12X\n" +
	"\x1cschedule_cancellation_reason\x18\f \x01(\v2\x11.DisruptionReasonH\x01R\x1ascheduleCancellationReason\x88\x01\x01\x12M\n" +
	"!schedule_diverted_via_location_id\x18\r \x01(\tH\x02R\x1dscheduleDivertedViaLocationId\x88\x01\x01\x12R\n" +
	"\x19schedule_diversion_reason\x18\x0e \x01(\v2\x11.DisruptionReasonH\x03R\x17scheduleDiversionReason\x88\x01\x01B\x14\n" +
	"\x12_retail_service_idB\x1f\n" +
	"\x1d_schedule_cancellation_reasonB$\n" +
	"\"_schedule_diverted_via_location_idB\x1c\n" +
	"\x1a_schedule_diversion_reason\"\xf8\a\n" +
	"\x10ScheduleLocation\x12-\n" +
	"\n" +
	"activities\x18\x01 \x03(\x0e2\r.ActivityTypeR\n" +
	"activities\x12<\n" +
	"\x12planned_activities\x18\x02 \x03(\x0e2\r.ActivityTypeR\x11plannedActivities\x12H\n" +
	"!location_is_affected_by_diversion\x18\x03 \x01(\bR\x1dlocationIsAffectedByDiversion\x122\n" +
	"\rlocation_type\x18\x04 \x01(\x0e2\r.LocationTypeR\flocationType\x12H\n" +
	"\x1escheduled_working_arrival_time\x18\x05 \x01(\tH\x00R\x1bscheduledWorkingArrivalTime\x88\x01\x01\x12H\n" +
	"\x1escheduled_working_passing_time\x18\x06 \x01(\tH\x01R\x1bscheduledWorkingPassingTime\x88\x01\x01\x12L\n" +
	" scheduled_working_departure_time\x18\a \x01(\tH\x02R\x1dscheduledWorkingDepartureTime\x88\x01\x01\x12F\n" +
	"\x1dscheduled_public_arrival_time\x18\b \x01(\tH\x03R\x1ascheduledPublicArrivalTime\x88\x01\x01\x12J\n" +
	"\x1fscheduled_public_departure_time\x18\t \x01(\tH\x04R\x1cscheduledPublicDepartureTime\x88\x01\x01\x12#\n" +
	"\rrouting_delay\x18\n" +
	" \x01(\rR\froutingDelay\x122\n" +
	"\x15location_is_cancelled\x18\v \x01(\bR\x13locationIsCancelled\x12X\n" +
	"\x1clocation_cancellation_reason\x18\f \x01(\v2\x11.DisruptionReasonH\x05R\x1alocationCancellationReason\x88\x01\x01B!\n" +
	"\x1f_scheduled_working_arrival_timeB!\n" +
	"\x1f_scheduled_working_passing_timeB#\n" +
	"!_scheduled_working_departure_timeB \n" +
	"\x1e_scheduled_public_arrival_timeB\"\n" +
	" _scheduled_public_departure_timeB\x1f\n" +
	"\x1d_location_cancellation_reason\"\xdc\x1c\n" +
	"\bForecast\x120\n" +
	"\x14is_reverse_formation\x18\x01 \x01(\bR\x12isReverseFormation\x12H\n" +
	"\x14schedule_late_reason\x18\x02 \x01(\v2\x11.DisruptionReasonH\x00R\x12scheduleLateReason\x88\x01\x01\x12F\n" +
	"\x1destimated_public_arrival_time\x18\x03 \x01(\tH\x01R\x1aestimatedPublicArrivalTime\x88\x01\x01\x12H\n" +
	"\x1eestimated_working_arrival_time\x18\x04 \x01(\tH\x02R\x1bestimatedWorkingArrivalTime\x88\x01\x01\x12H\n" +
	"\x1eestimated_minimum_arrival_time\x18\x05 \x01(\tH\x03R\x1bestimatedMinimumArrivalTime\x88\x01\x01\x121\n" +
	"\x12arrival_is_delayed\x18\x06 \x01(\bH\x04R\x10arrivalIsDelayed\x88\x01\x01\x12R\n" +
	"$arrival_is_delayed_by_unknown_amount\x18\a \x01(\bH\x05R\x1farrivalIsDelayedByUnknownAmount\x88\x01\x01\x129\n" +
	"\x16estimated_passing_time\x18\b \x01(\tH\x06R\x14estimatedPassingTime\x88\x01\x01\x12H\n" +
	"\x1eestimated_minimum_passing_time\x18\t \x01(\tH\aR\x1bestimatedMinimumPassingTime\x88\x01\x01\x121\n" +
	"\x12passing_is_delayed\x18\n" +
	" \x01(\bH\bR\x10passingIsDelayed\x88\x01\x01\x12R\n" +
	"$passing_is_delayed_by_unknown_amount\x18\v \x01(\bH\tR\x1fpassingIsDelayedByUnknownAmount\x88\x01\x01\x12J\n" +
	"\x1festimated_public_departure_time\x18\f \x01(\tH\n" +
	"R\x1cestimatedPublicDepartureTime\x88\x01\x01\x12L\n" +
	" estimated_working_departure_time\x18\r \x01(\tH\vR\x1destimatedWorkingDepartureTime\x88\x01\x01\x12L\n" +
	" estimated_minimum_departure_time\x18\x0e \x01(\tH\fR\x1destimatedMinimumDepartureTime\x88\x01\x01\x125\n" +
	"\x14departure_is_delayed\x18\x0f \x01(\bH\rR\x12departureIsDelayed\x88\x01\x01\x12V\n" +
	"&departure_is_delayed_by_unknown_amount\x18\x10 \x01(\bH\x0eR!departureIsDelayedByUnknownAmount\x88\x01\x01\x123\n" +
	"\x13actual_arrival_time\x18\x11 \x01(\tH\x0fR\x11actualArrivalTime\x88\x01\x01\x12>\n" +
	"\x19actual_arrival_data_class\x18\x12 \x01(\tH\x10R\x16actualArrivalDataClass\x88\x01\x01\x12@\n" +
	"\x1aactual_arrival_data_source\x18\x13 \x01(\tH\x11R\x17actualArrivalDataSource\x88\x01\x01\x12M\n" +
	"!actual_arrival_data_source_system\x18\x14 \x01(\tH\x12R\x1dactualArrivalDataSourceSystem\x88\x01\x01\x123\n" +
	"\x13actual_passing_time\x18\x15 \x01(\tH\x13R\x11actualPassingTime\x88\x01\x01\x12>\n" +
	"\x19actual_passing_data_class\x18\x16 \x01(\tH\x14R\x16actualPassingDataClass\x88\x01\x01\x12@\n" +
	"\x1aactual_passing_data_source\x18\x17 \x01(\tH\x15R\x17actualPassingDataSource\x88\x01\x01\x12M\n" +
	"!actual_passing_data_source_system\x18\x18 \x01(\tH\x16R\x1dactualPassingDataSourceSystem\x88\x01\x01\x127\n" +
	"\x15actual_departure_time\x18\x19 \x01(\tH\x17R\x13actualDepartureTime\x88\x01\x01\x12B\n" +
	"\x1bactual_departure_data_class\x18\x1a \x01(\tH\x18R\x18actualDepartureDataClass\x88\x01\x01\x12D\n" +
	"\x1cactual_departure_data_source\x18\x1b \x01(\tH\x19R\x19actualDepartureDataSource\x88\x01\x01\x12Q\n" +
	"#actual_departure_data_source_system\x18\x1c \x01(\tH\x1aR\x1factualDepartureDataSourceSystem\x88\x01\x01\x12H\n" +
	"\x14location_late_reason\x18\x1d \x01(\v2\x11.DisruptionReasonH\x1bR\x12locationLateReason\x88\x01\x01\x12=\n" +
	"\x18location_disruption_risk\x18\x1e \x01(\tH\x1cR\x16locationDisruptionRisk\x88\x01\x01\x12]\n" +
	"\x1flocation_disruption_risk_reason\x18\x1f \x01(\v2\x11.DisruptionReasonH\x1dR\x1clocationDisruptionRiskReason\x88\x01\x01\x12$\n" +
	"\vaffected_by\x18  \x01(\tH\x1eR\n" +
	"affectedBy\x88\x01\x01\x129\n" +
	"\x16platform_is_suppressed\x18! \x01(\bH\x1fR\x14platformIsSuppressed\x88\x01\x01\x12E\n" +
	"\x1dplatform_is_suppressed_by_cis\x18\" \x01(\bH R\x19platformIsSuppressedByCis\x88\x01\x01\x12J\n" +
	"\x14platform_data_source\x18# \x01(\x0e2\x13.PlatformDataSourceH!R\x12platformDataSource\x88\x01\x01\x127\n" +
	"\x15platform_is_confirmed\x18$ \x01(\bH\"R\x13platformIsConfirmed\x88\x01\x01\x122\n" +
	"\x15service_is_suppressed\x18% \x01(\bR\x13serviceIsSuppressed\x12?\n" +
	"\x1cservice_detatches_from_front\x18& \x01(\bR\x19serviceDetatchesFromFrontB\x17\n" +
	"\x15_schedule_late_reasonB \n" +
	"\x1e_estimated_public_arrival_timeB!\n" +
	"\x1f_estimated_working_arrival_timeB!\n" +
	"\x1f_estimated_minimum_arrival_timeB\x15\n" +
	"\x13_arrival_is_delayedB'\n" +
	"%_arrival_is_delayed_by_unknown_amountB\x19\n" +
	"\x17_estimated_passing_timeB!\n" +
	"\x1f_estimated_minimum_passing_timeB\x15\n" +
	"\x13_passing_is_delayedB'\n" +
	"%_passing_is_delayed_by_unknown_amountB\"\n" +
	" _estimated_public_departure_timeB#\n" +
	"!_estimated_working_departure_timeB#\n" +
	"!_estimated_minimum_departure_timeB\x17\n" +
	"\x15_departure_is_delayedB)\n" +
	"'_departure_is_delayed_by_unknown_amountB\x16\n" +
	"\x14_actual_arrival_timeB\x1c\n" +
	"\x1a_actual_arrival_data_classB\x1d\n" +
	"\x1b_actual_arrival_data_sourceB$\n" +
	"\"_actual_arrival_data_source_systemB\x16\n" +
	"\x14_actual_passing_timeB\x1c\n" +
	"\x1a_actual_passing_data_classB\x1d\n" +
	"\x1b_actual_passing_data_sourceB$\n" +
	"\"_actual_passing_data_source_systemB\x18\n" +
	"\x16_actual_departure_timeB\x1e\n" +
	"\x1c_actual_departure_data_classB\x1f\n" +
	"\x1d_actual_departure_data_sourceB&\n" +
	"$_actual_departure_data_source_systemB\x17\n" +
	"\x15_location_late_reasonB\x1b\n" +
	"\x19_location_disruption_riskB\"\n" +
	" _location_disruption_risk_reasonB\x0e\n" +
	"\f_affected_byB\x19\n" +
	"\x17_platform_is_suppressedB \n" +
	"\x1e_platform_is_suppressed_by_cisB\x17\n" +
	"\x15_platform_data_sourceB\x18\n" +
	"\x16_platform_is_confirmed*\xd5\x02\n" +
	"\n" +
	"SearchType\x12\x1b\n" +
	"\x17SEARCH_TYPE_RETURN_NONE\x10\x00\x12!\n" +
	"\x1dSEARCH_TYPE_RETURN_DEPARTURES\x10\x01\x12\x1e\n" +
	"\x1aSEARCH_TYPE_RETURN_PASSING\x10\x02\x12-\n" +
	")SEARCH_TYPE_RETURN_PASSING_AND_DEPARTURES\x10\x03\x12\x1f\n" +
	"\x1bSEARCH_TYPE_RETURN_ARRIVALS\x10\x04\x12.\n" +
	"*SEARCH_TYPE_RETURN_ARRIVALS_AND_DEPARTURES\x10\x05\x12+\n" +
	"'SEARCH_TYPE_RETURN_ARRIVALS_AND_PASSING\x10\x06\x12:\n" +
	"6SEARCH_TYPE_RETURN_ARRIVALS_AND_PASSING_AND_DEPARTURES\x10\a*\xea\x01\n" +
	"\vServiceType\x12\x18\n" +
	"\x14SERVICE_TYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12SERVICE_TYPE_TRAIN\x10\x01\x12)\n" +
	"%SERVICE_TYPE_SHORT_TERM_PLANNED_TRAIN\x10\x02\x12\x14\n" +
	"\x10SERVICE_TYPE_BUS\x10\x03\x12'\n" +
	"#SERVICE_TYPE_SHORT_TERM_PLANNED_BUS\x10\x04\x12\x15\n" +
	"\x11SERVICE_TYPE_SHIP\x10\x05\x12(\n" +
	"$SERVICE_TYPE_SHORT_TERM_PLANNED_SHIP\x10\x06*\x9b\x05\n" +
	"\fCategoryType\x12\x19\n" +
	"\x15CATEGORY_TYPE_UNKNOWN\x10\x00\x12&\n" +
	"\"CATEGORY_TYPE_UNDERGROUND_OR_METRO\x10\x01\x12(\n" +
	"$CATEGORY_TYPE_UNADVERTISED_PASSENGER\x10\x02\x12\x1b\n" +
	"\x17CATEGORY_TYPE_PASSENGER\x10\x03\x12\x17\n" +
	"\x13CATEGORY_TYPE_STAFF\x10\x04\x12\x17\n" +
	"\x13CATEGORY_TYPE_MIXED\x10\x05\x12 \n" +
	"\x1cCATEGORY_TYPE_CHANNEL_TUNNEL\x10\x06\x12\x19\n" +
	"\x15CATEGORY_TYPE_SLEEPER\x10\a\x12\x1f\n" +
	"\x1bCATEGORY_TYPE_INTERNATIONAL\x10\b\x12\x1a\n" +
	"\x16CATEGORY_TYPE_MOTORAIL\x10\t\x12&\n" +
	"\"CATEGORY_TYPE_UNADVERTISED_EXPRESS\x10\n" +
	"\x12\x19\n" +
	"\x15CATEGORY_TYPE_EXPRESS\x10\v\x12\"\n" +
	"\x1eCATEGORY_TYPE_SLEEPER_DOMESTIC\x10\f\x12!\n" +
	"\x1dCATEGORY_TYPE_BUS_REPLACEMENT\x10\r\x12\x1d\n" +
	"\x19CATEGORY_TYPE_BUS_SERVICE\x10\x0e\x12\x16\n" +
	"\x12CATEGORY_TYPE_SHIP\x10\x0f\x12&\n" +
	"\"CATEGORY_TYPE_EMPTY_COACHING_STOCK\x10\x10\x12;\n" +
	"7CATEGORY_TYPE_EMPTY_COACHING_STOCK_UNDERGROUND_OR_METRO\x10\x11\x12/\n" +
	"+CATEGORY_TYPE_EMPTY_COACHING_STOCK_OR_STAFF\x10\x12*\xbe\x0e\n" +
	"\fActivityType\x12\x19\n" +
	"\x15ACTIVITY_TYPE_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aACTIVITY_TYPE_TRAIN_BEGINS\x10\x01\x12 \n" +
	"\x1cACTIVITY_TYPE_TRAIN_FINISHES\x10\x02\x12:\n" +
	"6ACTIVITY_TYPE_STOPS_TO_TAKE_UP_AND_SET_DOWN_PASSENGERS\x10\x03\x12-\n" +
	")ACTIVITY_TYPE_STOPS_TO_TAKE_UP_PASSENGERS\x10\x04\x12.\n" +
	"*ACTIVITY_TYPE_STOPS_TO_SET_DOWN_PASSENGERS\x10\x05\x12:\n" +
	"6ACTIVITY_TYPE_STOPS_OR_SHUNTS_FOR_OTHER_TRAINS_TO_PASS\x10\x06\x12@\n" +
	"<ACTIVITY_TYPE_STOPS_TO_ATTACH_OR_DETACH_ASSISTING_LOCOMOTIVE\x10\a\x12'\n" +
	"#ACTIVITY_TYPE_SHOWS_AS_X_ON_ARRIVAL\x10\b\x12.\n" +
	"*ACTIVITY_TYPE_STOPS_FOR_BANKING_LOCOMOTIVE\x10\t\x12,\n" +
	"(ACTIVITY_TYPE_STOPS_TO_CHANGE_TRAIN_CREW\x10\n" +
	"\x12+\n" +
	"'ACTIVITY_TYPE_STOPS_TO_DETATCH_VEHICLES\x10\v\x12'\n" +
	"#ACTIVITY_TYPE_STOPS_FOR_EXAMINATION\x10\f\x125\n" +
	"1ACTIVITY_TYPE_NATIONAL_RAIL_TIMETABLE_DATA_TO_ADD\x10\r\x12G\n" +
	"CACTIVITY_TYPE_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE\x10\x0e\x12M\n" +
	"IACTIVITY_TYPE_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE_TWICE\x10\x0f\x12'\n" +
	"#ACTIVITY_TYPE_PASSENGER_COUNT_POINT\x10\x10\x129\n" +
	"5ACTIVITY_TYPE_TICKET_COLLECTION_AND_EXAMINATION_POINT\x10\x11\x12*\n" +
	"&ACTIVITY_TYPE_TICKET_EXAMINATION_POINT\x10\x12\x12;\n" +
	"7ACTIVITY_TYPE_TICKET_EXAMINATION_POINT_FIRST_CLASS_ONLY\x10\x13\x124\n" +
	"0ACTIVITY_TYPE_TICKET_EXAMINATION_POINT_SELECTIVE\x10\x14\x12-\n" +
	")ACTIVITY_TYPE_STOPS_TO_CHANGE_LOCOMOTIVES\x10\x15\x12%\n" +
	"!ACTIVITY_TYPE_STOP_NOT_ADVERTISED\x10\x16\x123\n" +
	"/ACTIVITY_TYPE_STOPS_FOR_OTHER_OPERATING_REASONS\x10\x17\x12*\n" +
	"&ACTIVITY_TYPE_TRAIN_LOCOMOTIVE_ON_REAR\x10\x18\x121\n" +
	"-ACTIVITY_TYPE_PROPELLING_BETWEEN_POINTS_SHOWN\x10\x19\x12%\n" +
	"!ACTIVITY_TYPE_STOPS_WHEN_REQUIRED\x10\x1a\x12C\n" +
	"?ACTIVITY_TYPE_STOPS_FOR_REVERSING_MOVEMENT_OR_DRIVER_END_CHANGE\x10\x1b\x123\n" +
	"/ACTIVITY_TYPE_STOPS_FOR_LOCOMOTIVE_TO_RUN_ROUND\x10\x1c\x122\n" +
	".ACTIVITY_TYPE_STOPS_FOR_RAILWAY_PERSONELL_ONLY\x10\x1d\x125\n" +
	"1ACTIVITY_TYPE_STOPS_TO_ATTACH_AND_DETACH_VEHICLES\x10\x1e\x120\n" +
	",ACTIVITY_TYPE_DETAIL_CONSIST_FOR_TOPS_DIRECT\x10\x1f\x12;\n" +
	"7ACTIVITY_TYPE_STOPS_OR_PASSES_FOR_TABLET_STAFF_OR_TOKEN\x10 \x12*\n" +
	"&ACTIVITY_TYPE_STOPS_TO_ATTACH_VEHICLES\x10!\x12/\n" +
	"+ACTIVITY_TYPE_STOPS_FOR_WATERING_OF_COACHES\x10\"\x12G\n" +
	"CACTIVITY_TYPE_PASSES_ANOTHER_TRAIN_AT_CROSSING_POINT_ON_SINGLE_LINE\x10#*\xa7\x02\n" +
	"\fLocationType\x12\x19\n" +
	"\x15LOCATION_TYPE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14LOCATION_TYPE_ORIGIN\x10\x01\x12$\n" +
	" LOCATION_TYPE_OPERATIONAL_ORIGIN\x10\x02\x12\x1e\n" +
	"\x1aLOCATION_TYPE_INTERMEDIATE\x10\x03\x12*\n" +
	"&LOCATION_TYPE_OPERATIONAL_INTERMEDIATE\x10\x04\x12&\n" +
	"\"LOCATION_TYPE_INTERMEDIATE_PASSING\x10\x05\x12\x1d\n" +
	"\x19LOCATION_TYPE_DESTINATION\x10\x06\x12)\n" +
	"%LOCATION_TYPE_OPERATIONAL_DESTINATION\x10\a*\x9d\x01\n" +
	"\x12PlatformDataSource\x12 \n" +
	"\x1cPLATFORM_DATA_SOURCE_UNKNOWN\x10\x00\x12 \n" +
	"\x1cPLATFORM_DATA_SOURCE_PLANNED\x10\x01\x12\"\n" +
	"\x1ePLATFORM_DATA_SOURCE_AUTOMATIC\x10\x02\x12\x1f\n" +
	"\x1bPLATFORM_DATA_SOURCE_MANUAL\x10\x03B*Z(github.com/headblockhead/railreader-grpcb\x06proto3"

var (
	file_search_proto_rawDescOnce sync.Once
	file_search_proto_rawDescData []byte
)

func file_search_proto_rawDescGZIP() []byte {
	file_search_proto_rawDescOnce.Do(func() {
		file_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)))
	})
	return file_search_proto_rawDescData
}

var file_search_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_search_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_search_proto_goTypes = []any{
	(SearchType)(0),              // 0: SearchType
	(ServiceType)(0),             // 1: ServiceType
	(CategoryType)(0),            // 2: CategoryType
	(ActivityType)(0),            // 3: ActivityType
	(LocationType)(0),            // 4: LocationType
	(PlatformDataSource)(0),      // 5: PlatformDataSource
	(*SearchRequest)(nil),        // 6: SearchRequest
	(*SearchResponse)(nil),       // 7: SearchResponse
	(*ServiceRoute)(nil),         // 8: ServiceRoute
	(*ServiceRouteLocation)(nil), // 9: ServiceRouteLocation
	(*DisruptionReason)(nil),     // 10: DisruptionReason
	(*Schedule)(nil),             // 11: Schedule
	(*ScheduleLocation)(nil),     // 12: ScheduleLocation
	(*Forecast)(nil),             // 13: Forecast
}
var file_search_proto_depIdxs = []int32{
	0,  // 0: SearchRequest.search_type:type_name -> SearchType
	11, // 1: SearchResponse.schedule:type_name -> Schedule
	12, // 2: SearchResponse.schedule_location:type_name -> ScheduleLocation
	13, // 3: SearchResponse.forecast:type_name -> Forecast
	8,  // 4: SearchResponse.previous_route:type_name -> ServiceRoute
	8,  // 5: SearchResponse.next_route:type_name -> ServiceRoute
	1,  // 6: Schedule.service_type:type_name -> ServiceType
	2,  // 7: Schedule.category_type:type_name -> CategoryType
	10, // 8: Schedule.schedule_cancellation_reason:type_name -> DisruptionReason
	10, // 9: Schedule.schedule_diversion_reason:type_name -> DisruptionReason
	3,  // 10: ScheduleLocation.activities:type_name -> ActivityType
	3,  // 11: ScheduleLocation.planned_activities:type_name -> ActivityType
	4,  // 12: ScheduleLocation.location_type:type_name -> LocationType
	10, // 13: ScheduleLocation.location_cancellation_reason:type_name -> DisruptionReason
	10, // 14: Forecast.schedule_late_reason:type_name -> DisruptionReason
	10, // 15: Forecast.location_late_reason:type_name -> DisruptionReason
	10, // 16: Forecast.location_disruption_risk_reason:type_name -> DisruptionReason
	5,  // 17: Forecast.platform_data_source:type_name -> PlatformDataSource
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_search_proto_init() }
func file_search_proto_init() {
	if File_search_proto != nil {
		return
	}
	file_search_proto_msgTypes[0].OneofWrappers = []any{}
	file_search_proto_msgTypes[1].OneofWrappers = []any{}
	file_search_proto_msgTypes[4].OneofWrappers = []any{}
	file_search_proto_msgTypes[5].OneofWrappers = []any{}
	file_search_proto_msgTypes[6].OneofWrappers = []any{}
	file_search_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_search_proto_goTypes,
		DependencyIndexes: file_search_proto_depIdxs,
		EnumInfos:         file_search_proto_enumTypes,
		MessageInfos:      file_search_proto_msgTypes,
	}.Build()
	File_search_proto = out.File
	file_search_proto_goTypes = nil
	file_search_proto_depIdxs = nil
}
