// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: searchRequest.proto

package railreader_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	LocationId                  string                 `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`                                                         // Only services scheduled at or through this location will be returned.
	FromTime                    string                 `protobuf:"bytes,2,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`                                                               // Services scheduled up to 2 hours before the from_time may be included if they are delayed.
	ToTime                      string                 `protobuf:"bytes,3,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`                                                                     // Services scheduled up to 2 hours after the to_time may be included if they are early.
	IncludeNonPassengerServices bool                   `protobuf:"varint,4,opt,name=include_non_passenger_services,json=includeNonPassengerServices,proto3" json:"include_non_passenger_services,omitempty"` // If true, all services will be included. If false or unspecified, only passenger services will be included.
	ExcludeNonActiveServices    bool                   `protobuf:"varint,5,opt,name=exclude_non_active_services,json=excludeNonActiveServices,proto3" json:"exclude_non_active_services,omitempty"`          // If true, only active services will be included. Be warned: this excludes most historical data. If false or unspecified, all services will be included.
	IncludeCharteredServices    bool                   `protobuf:"varint,6,opt,name=include_chartered_services,json=includeCharteredServices,proto3" json:"include_chartered_services,omitempty"`            // If true, all services will be included. If false or unspecified, only non-chartered services will be included.
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_searchRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_searchRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_searchRequest_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *SearchRequest) GetFromTime() string {
	if x != nil {
		return x.FromTime
	}
	return ""
}

func (x *SearchRequest) GetToTime() string {
	if x != nil {
		return x.ToTime
	}
	return ""
}

func (x *SearchRequest) GetIncludeNonPassengerServices() bool {
	if x != nil {
		return x.IncludeNonPassengerServices
	}
	return false
}

func (x *SearchRequest) GetExcludeNonActiveServices() bool {
	if x != nil {
		return x.ExcludeNonActiveServices
	}
	return false
}

func (x *SearchRequest) GetIncludeCharteredServices() bool {
	if x != nil {
		return x.IncludeCharteredServices
	}
	return false
}

var File_searchRequest_proto protoreflect.FileDescriptor

const file_searchRequest_proto_rawDesc = "" +
	"\n" +
	"\x13searchRequest.proto\"\xa8\x02\n" +
	"\rSearchRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\x12\x1b\n" +
	"\tfrom_time\x18\x02 \x01(\tR\bfromTime\x12\x17\n" +
	"\ato_time\x18\x03 \x01(\tR\x06toTime\x12C\n" +
	"\x1einclude_non_passenger_services\x18\x04 \x01(\bR\x1bincludeNonPassengerServices\x12=\n" +
	"\x1bexclude_non_active_services\x18\x05 \x01(\bR\x18excludeNonActiveServices\x12<\n" +
	"\x1ainclude_chartered_services\x18\x06 \x01(\bR\x18includeCharteredServicesB*Z(github.com/headblockhead/railreader-grpcb\x06proto3"

var (
	file_searchRequest_proto_rawDescOnce sync.Once
	file_searchRequest_proto_rawDescData []byte
)

func file_searchRequest_proto_rawDescGZIP() []byte {
	file_searchRequest_proto_rawDescOnce.Do(func() {
		file_searchRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_searchRequest_proto_rawDesc), len(file_searchRequest_proto_rawDesc)))
	})
	return file_searchRequest_proto_rawDescData
}

var file_searchRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_searchRequest_proto_goTypes = []any{
	(*SearchRequest)(nil), // 0: SearchRequest
}
var file_searchRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_searchRequest_proto_init() }
func file_searchRequest_proto_init() {
	if File_searchRequest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_searchRequest_proto_rawDesc), len(file_searchRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_searchRequest_proto_goTypes,
		DependencyIndexes: file_searchRequest_proto_depIdxs,
		MessageInfos:      file_searchRequest_proto_msgTypes,
	}.Build()
	File_searchRequest_proto = out.File
	file_searchRequest_proto_goTypes = nil
	file_searchRequest_proto_depIdxs = nil
}
