// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: updateLocationsRequest.proto

package railreader_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateLocationsRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CurrentReferenceFileId *string                `protobuf:"bytes,1,opt,name=current_reference_file_id,json=currentReferenceFileId,proto3,oneof" json:"current_reference_file_id,omitempty"` // If not specified, all updates will be returned.
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateLocationsRequest) Reset() {
	*x = UpdateLocationsRequest{}
	mi := &file_updateLocationsRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationsRequest) ProtoMessage() {}

func (x *UpdateLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_updateLocationsRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationsRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationsRequest) Descriptor() ([]byte, []int) {
	return file_updateLocationsRequest_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateLocationsRequest) GetCurrentReferenceFileId() string {
	if x != nil && x.CurrentReferenceFileId != nil {
		return *x.CurrentReferenceFileId
	}
	return ""
}

var File_updateLocationsRequest_proto protoreflect.FileDescriptor

const file_updateLocationsRequest_proto_rawDesc = "" +
	"\n" +
	"\x1cupdateLocationsRequest.proto\"v\n" +
	"\x16UpdateLocationsRequest\x12>\n" +
	"\x19current_reference_file_id\x18\x01 \x01(\tH\x00R\x16currentReferenceFileId\x88\x01\x01B\x1c\n" +
	"\x1a_current_reference_file_idB*Z(github.com/headblockhead/railreader-grpcb\x06proto3"

var (
	file_updateLocationsRequest_proto_rawDescOnce sync.Once
	file_updateLocationsRequest_proto_rawDescData []byte
)

func file_updateLocationsRequest_proto_rawDescGZIP() []byte {
	file_updateLocationsRequest_proto_rawDescOnce.Do(func() {
		file_updateLocationsRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_updateLocationsRequest_proto_rawDesc), len(file_updateLocationsRequest_proto_rawDesc)))
	})
	return file_updateLocationsRequest_proto_rawDescData
}

var file_updateLocationsRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_updateLocationsRequest_proto_goTypes = []any{
	(*UpdateLocationsRequest)(nil), // 0: UpdateLocationsRequest
}
var file_updateLocationsRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_updateLocationsRequest_proto_init() }
func file_updateLocationsRequest_proto_init() {
	if File_updateLocationsRequest_proto != nil {
		return
	}
	file_updateLocationsRequest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_updateLocationsRequest_proto_rawDesc), len(file_updateLocationsRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_updateLocationsRequest_proto_goTypes,
		DependencyIndexes: file_updateLocationsRequest_proto_depIdxs,
		MessageInfos:      file_updateLocationsRequest_proto_msgTypes,
	}.Build()
	File_updateLocationsRequest_proto = out.File
	file_updateLocationsRequest_proto_goTypes = nil
	file_updateLocationsRequest_proto_depIdxs = nil
}
